<?php 
	$videoData  = $this->video; /*echo "<pre>";
	print_r($videoData);die;*/
?>
<!-- TinyMCE -->
<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
         <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						<h3 class="page-title">
							Video Manager
							
						</h3>
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'video','action'=>'videolist', 'module' => 'admin'), null, true);?>">Video Manager</a>
							<span class="divider">/</span>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
							<div class="widget">
								<div class="widget-title">
									<h4><i class="icon-reorder"></i>Video</h4>							
								</div>
								<div class="widget-body">
								</div>
							</div>
							<!-- END EXAMPLE TABLE PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 