<?php $imageData = $this->Images;
?>
<!-- TinyMCE -->
<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
         <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'images','action'=>'imageslist', 'module' => 'admin'), null, true);?>"">Images Manager</a>
							<span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'images','action'=>'updateimage','id'=>base64_encode($this->imageId), 'module' => 'admin'), null, true);?>"">update Image </a>
							<span class="divider">/</span>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                     <div class="widget-title">
									<h4>Update Image</h4>							
								</div>
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form name="videos" id="videos" action="<?php array('controller' =>'images', 'action' =>'updateimage', 'module' =>'admin');?>" enctype="multipart/form-data" method="post" class="form-horizontal" onSubmit="return ImagesValidate();">
                              <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>Image Title:</label>
                                 <div class="controls">
                                    <input type="text"  class="span6 popovers " id="image_title" name="image_title" 
                                    maxlength="50" data-trigger="hover" value="<?php echo $imageData['image_title'];?>" />
                                 	<input type="hidden"  name="old_image"  value="<?php echo $imageData['image_name'];?>" />
                                 	<input type="hidden"  name="id"  value="<?php echo $this->imageId;?>" />
                                 </div>
                              </div>
                               
                              <div class="control-group">
                                 <label class="control-label Grey" for="inputRemarks"><span class="error">*</span>Image File</label>
                                 <div class="controls">
                                    <input type="file"  class="filestyle"  title="Search for a Image to add" id="image" name="image"/>
                                 </div>
                              </div>
                             
                              <div class="form-actions">
                                 <button type="submit" class="btn btn-primary">Update</button>
                                 <button type="button" class="btn" onClick="returnPage('images','imageslist');">Cancel</button>
                              </div>
                           </form>
                           <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 
