<script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php  $perPage = $this->perpage;
//echo "<pre>";print_r($this->categoryData);die;
?>
<!-- BEGIN PAGE -->

<div id="body">
  <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <div id="widget-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button">×</button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">
      <p>Here will be a configuration form</p>
    </div>
  </div>
  <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <!-- BEGIN PAGE CONTAINER-->
  <div class="container-fluid">
    <?php if(isset($this->success) && $this->success != ''){?>
    <div id="success" class="alert alert-success">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->success;?></div>
    <?php }?>
    <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>
    <div id="exception" class="alert alert-error">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->error;?> </div>
    <?php     	
        		 }
        	 ?>
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
      <div class="span12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <ul class="breadcrumb">
          <li> <i class="icon-home"></i> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span> </li>
          <li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'categorylist', 'module' => 'admin'), null, true);?>">Category Manager</a></li>
          <li style="float:right;text-align: center;"> <a  href="<?php echo $this->url(array('controller'=>'questions','action'=>'addcategory', 'module' => 'admin'), null, true);?>"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/add_trophy.png" /></a></a></li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div id="page" class="dashboard">
      <div class="row-fluid">
        <div class="span12">
          <!-- BEGIN EXAMPLE TABLE PORTLET-->
          <div class="widget">
            <div class="widget-title">
              <h4>Category List</h4>
            </div>
            <div class="widget-body">
              <form id="searchfilter" class="Margin_0" method="post" name="searchfilter" action="<?php array('controller' =>'questions', 'action' =>'categorylist', 'module' =>'admin');?>">
                <div class="row-fluid">
                  <div class=""> </div>
                </div>
                <div class="row-fluid">
                  <div class="control-group Left">
                    <input type="text"  class="span7 popovers" id="seachdata" placeholder="Search Keyword" name="seachdata" value="<?php  echo $this->searchdata;?>"/>
                    <input type ="submit" class="btn btn-primary serach_Button"  value="Search">
                  </div>
                </div>
              </form>
              <?php if($this->searchdata != ''){?>
              <ul class="breadcrumb">
                <li> You have searched for : </li>
                <li> <?php echo $this->searchdata;?> </li>
                <li><span class="divider">/</span> <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'categorylist', 'module' => 'admin'), null, true);?>">Clear search</a> </li>
              </ul>
              <?php }?>
              <div class="">
              <table class="table table-striped table-bordered overFlow" id="categorylist">
                <thead>
                  <tr>
                    <th class="fontsize15">Category</th>
                    <th class="fontsize15">Framework Name</th>
                    <!--<th class="hidden-phone fontsize15">Grade</th>-->
                    <th class="hidden-phone fontsize15">Domain Name</th>
                    <th class="hidden-phone fontsize15">Sub Topic</th>
                    <th class="hidden-phone fontsize15">Created By</th>
					<th class="hidden-phone fontsize15">Created Date</th>
					<th class="hidden-phone fontsize15">Modified By</th>
					<th class="hidden-phone fontsize15">Modified Date</th>
                    <th class="hidden-phone fontsize15" style="width:92px;">Operation</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
										 if($this->totalRecord>0){
									   foreach($this->categoryData as $caq){
									   //echo "<pre>";print_r($caq);
									   	$questCount = $this->getCategoryStatus($caq['category_id']);
									   	$categoryId = $caq['category_id'];
									  // 	$grade = $caq['grade_name'];
									   	/*$psvCode =  'psv.'.strtolower($caq['stnd_name']).'.'.strtolower($caq['subject_name']).'.'.strtolower($caq['grade_name']).'.'.strtolower($caq['code']).'.'.strtolower($caq['subtopic_code']);
									   	$tblQuestionCat = new Application_Model_DbTable_QuestionCategories();
									   	$updatedataArray =  array('psv_code' =>$psvCode);
									   	$where = "category_id = '$categoryId'";
									    $updateQuestionsCategory = $tblQuestionCat->update($updatedataArray, $where);*/
									   
									   	?>
                  <tr class="odd gradeX">
                    <td class="hidden-phone ">&nbsp;<?php echo wordwrap(strtoupper($caq['psv_code']),20,"<br />\n",true);?></td>
                    <td class="hidden-phone ">&nbsp;<?php echo strtoupper($caq['subject_name']);?></td>
                    <!--<td class="hidden-phone fontsize15">&nbsp;<?php //echo $caq['grade_name'];?></td>-->
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo wordwrap($caq['name'],25,"<br />\n",true);?></td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo wordwrap($caq['subtopic_name'],25,"<br />\n",true);?></td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo $caq['created_by']?$caq['created_by']:'--';?></td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo $caq['created_date'];?></td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo $caq['modified_by']?$caq['modified_by']:'--';?></td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo ($caq['modified_date'] !='' && $caq['modified_by'] !='')?$caq['modified_date']:'--';?></td>
                    <td class="hidden-phone center fontsize15">&nbsp; <a href="<?php echo $this->url(array('controller' =>'questions','action'=>'viewcategorydata','module'=>'admin','id' =>$categoryId),null,true);?>"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/preview.png" alt="View this category" title="View this category" border="0"/></a> <a href="<?php echo $this->url(array('controller' =>'questions','action'=>'editcategory','module'=>'admin','id' =>$categoryId),null,true);?>"><img border="0" title="Edit this category" alt="Edit this category" src="<?php echo $this->baseUrl();?>/assets_admin/images/edit_icon.png"></a>
                      <?php if($questCount==0){?>
                      <a href="javascript:void(0);"><img src="<?php  echo $this->baseUrl();?>/assets_admin/images/del.png" alt="Delete Category" title="Delete this category" border="0" onClick="deleteData(<?php echo $categoryId;?>,'questions','deletecategory')"/></a>
                      <?php }else{?>
                      <img style="opacity:0.2;" src="<?php  echo $this->baseUrl();?>/assets_admin/images/del.png"  border="0"/>
                      <?php }?>
                    </td>
                  </tr>
                  <?php }
										 }else{	?>
                  <tr class="odd gradeX">
                    <td class="hidden-phone" colspan="9" style="text-align: center">NO RECORD FOUND</td>
                  </tr>
                  <?php }?>
                </tbody>
              </table>
              </div>
            </div>
          </div>
          <?php 
								   if($this->totalRecord >$perPage){?>
          <form name="searchFormSort" id="searchFormSort" action="<?php  echo $this->url(array('controller' => 'questions', 'action' => 'categorylist', 'module' => 'admin'),null,true);?>" method="post" class="RecordPerPage">
            <span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" onchange="javascript:sub_per_page();" class="span6" tabindex="1" id="">
              <option value="10" <?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
              <option value="25" <?php if($perPage == '25'){ echo 'selected=selected';}?>>25</option>
              <option value="50" <?php if($perPage == '50'){ echo 'selected=selected';}?>>50</option>
              <option value="100" <?php if($perPage == '100'){ echo 'selected=selected';}?>>100</option>
              <option value="250" <?php if($perPage == '250'){ echo 'selected=selected';}?>>250</option>
              <option value="500" <?php if($perPage == '500'){ echo 'selected=selected';}?>>500</option>
            </select><span class="RecordPerPageSpan">&nbsp;entries</span>
            <input type="hidden" name="seachdata" class="searchdata" value="<?php  echo $this->searchdata;?>" />
          </form>
          <?php }?>
          <script language="javascript">
							function sub_per_page()
							{
							$('.searchdata').val($('#seachdata').val());
							document.searchFormSort.submit();
							}
							</script>
          <?php  
														      // pagination start
					 if($this->totalRecord>0){
						if($this->totalRecord >$perPage){
							echo $this->paginationControl($this->categoryData, 'Sliding', 'paginationquestion.phtml',array('seachdata' =>$this->searchdata,'perpage' =>$perPage));
						}else{
						}
					}
					// pagination ends ?>
          <!-- END EXAMPLE TABLE PORTLET-->
        </div>
      </div>
    </div>
    <!-- END PAGE CONTENT-->
  </div>
  <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>
	$(document).ready(function(){
		var sorting =[1,3,4,5];
		applyDataTable('categorylist',sorting);
	});
	$("#categorylist_length").css('display','none');
	$("#categorylist_filter").css('display','none');
	$("#categorylist_paginate").css('display','none');
	
	</script>
<script>
	function applyDataTable(tableid,sorting)
	{
		$(document).ready(function() {
			oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
				               {
				                  bSortable: false,
				                  aTargets: sorting
				               }
				             ]
	        
				
			});
		} );
	}
	
	
	</script>
