<script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php 
 if(isset($this->standard_id)) 
 {
 	$standard_ids	= $this->standard_id;
 }
 require_once APPLICATION_PATH.'/../library/function_image_array.php';
?>
<?php $perPage = $this->perpage;
$actionName = str_replace(' ', '', Zend_Controller_Front::getInstance()->getRequest()->getActionName());?>
<!-- BEGIN PAGE -->

<div id="body">
  <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <div id="widget-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button">×</button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">
      <p>Here will be a configuration form</p>
    </div>
  </div>
  <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <!-- BEGIN PAGE CONTAINER-->
  <div class="container-fluid">
    <?php if(isset($this->success) && $this->success != ''){?>
    <div id="success" class="alert alert-success">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->success;?></div>
    <?php }?>
    <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>
    <div id="exception" class="alert alert-error">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->error;?> </div>
    <?php     	
        		 }
        	 ?>
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
      <div class="span12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <ul class="breadcrumb">
          <li> <i class="icon-home"></i> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span> </li>
          <li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlist', 'module' => 'admin'), null, true);?>">Question Manager</a> <span class="divider">/</span> </li>
          <li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'draftquestionlist', 'module' => 'admin'), null, true);?>">Draft Questions</a> </li>
          <li style="float:right"><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'question', 'module' => 'admin', 'type'=> $actionName), null, true);?>" style="cursor:pointer;"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/add_trophy.png" /></a></li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div id="page" class="dashboard">
      <div class="row-fluid">
        <div class="span12">
          <!-- BEGIN EXAMPLE TABLE PORTLET-->
          <div class="widget">
            <div class="widget-title TabsTop">
              <ul>
                  <li>
                      <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlist', 'module' => 'admin'), null, true);?>">
	              Questions
	              </a>
                  </li>
                  <li>
	              <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'expiringquestionlist', 'module' => 'admin'), null, true);?>">
	              Expiring Questions
	              </a>
                  </li>
                  <li>
	              <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'expiredquestionlist', 'module' => 'admin'), null, true);?>" >
	              Expired Questions
	              </a>
                  </li>
                  <li>
                      <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'draftquestionlist', 'module' => 'admin'), null, true);?>" class="active">
          		  Draft Questions
          	      </a> 
                  </li>
              </ul>
            </div>
            <div class="widget-body">
              <form id="searchfilter" method="post" name="searchfilter"  class="Margin_0">
                <div class="row-fluid">
                  <div class="">
                    <div id="standard_div" class="dataTables_length">
                      <label class="filter_padding">
                      <select name="standard" id="standard" class="standardbox" size="1" aria-controls="sample_1" onchange="getGradeInfoUsingStandardId(this.value);">
                        <option value="" selected="selected">Standard</option>
                        <?php 
															$standard 	=	$this->standard;
															foreach ($standard as $std)
															{
														?>
                        <option value="<?php echo $std->standard_id;?>" ><?php echo $std->name;?></option>
                        <?php	
															}
														?>
                      </select>
                      </label>
                    </div>
                      <div id="grade_div" class="dataTables_length">
                      <label class="filter_padding">
                      <select name="grades" class="gradebox" id="grades" size="1" aria-controls="sample_1">
                        <option value="" selected="selected">Grade</option>
                      </select>
                      </label>
                    </div>
                    <div id="framework_div" class="dataTables_length">
                      <label class="filter_padding">
                      <select name="framework" class="frameworkbox" size="1" aria-controls="sample_1" id="framework" >
                        <option value="" selected="selected">Framework</option>
                      </select>
                      </label>
                    </div>
                    <div id="domain_div" class="dataTables_length">
                      <label class="filter_padding">
                      <select name="domain" class="domainbox" id="domain" size="1" aria-controls="sample_1">
                        <option value="" selected="selected">Domain</option>
                      </select>
                      </label>
                    </div>
                    <input type ="button" class="btn btn-primary" id="search_category" value="Search" onclick="getfilteredsearch('draftquestionlist');">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                     
                      <select name="creator" class="domainbox" id="creator" size="1" aria-controls="sample_1" onchange="GetCreatedModifiedSearch(this.value,'draftquestionlist')">
                        <option value="" selected="selected">Created By</option>
                        <?php foreach ($this->adminUser as $adminUser){?>
                         	<option value="<?php echo $adminUser['admin_user_id'];?>" <?php if($this->searchBy == $adminUser['admin_user_id']){echo 'selected="selected"';}?> ><?php echo $adminUser['name'];?></option>
                        <?php }?>
                      </select>
                  </div>
                </div>
                <?php 
						$search_val='';$search_qval="";
						if($this->standard_id != '' || $this->frame || $this->grade || $this->domain || $this->search_question) {
				   if($this->standard_id != ''){
					 $standard 	=	$this->standard;
					 foreach ($standard as $std)
						{
						if(isset($standard_ids) && $standard_ids == $std->standard_id)
						{
						$search_val= "Standard : ".$std->name;
						}
                      }
					 }
					if($this->grade != ''){
						if($search_val != '')
					 	{
							$search_val= $search_val." | Grade : ".$this->grade->grade_name;
					 	}
					 	else 
					 	{
					 		$search_val= "Grade : ".$this->grade->grade_name;
					 	}	
					 }
                                         if($this->frame != ''){
					 	if($search_val != '')
					 	{
					 		$search_val= $search_val." | Framework : ".$this->frame->subject_name;
					 	}
					 	else 
					 	{
					 		$search_val = "Framework : ".$this->frame->subject_name;
					 	}
					}
					if($this->domain != ''){
						if($search_val != '')
					 	{
							$search_val=$search_val." | Domain : ".$this->domain->code.' ('.$this->domain->name.')';	
					 	}
					 	else 
					 	{
					 		$search_val="Domain : ".$this->domain->code.' ('.$this->domain->name.')';
					 	}
					 }
					if($this->search_question != '')
					$search_val= $this->search_question;	
				}			
				
							?>
                <div class="row-fluid">
                <div class="control-group">
                <label class="control-label" for="input3">
                <input type="text"  class="span6 popovers SearchAdmin" placeholder="Search Keyword"  id="search_question" name="search_question" value="<?php  echo $search_va;?>"/>
                <input type =""button"" class="btn btn-primary SearchButton" id="searchquestion" value="Search Question" onclick="getfilterequestion('draftquestionlist');">
                </div>
                </div>
              </form>
              <?php if($search_val != '') {
				 
							?>
              <ul class="breadcrumb">
                <li> You have searched for : </li>
                <li> <?php echo $search_val;?> </li>
                <li><span class="divider">/</span> <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'draftquestionlist', 'module' => 'admin'), null, true);?>">Clear search</a> </li>
              </ul>
              <?php }?>
              <div class="overFlow">
              <table class="table table-striped table-bordered" id="questionlist">
                <thead>
                  <tr>
                    <th style="width:10%">#</th>
                    <th style="width:24%">Category</th>
                    <th style="width:27%">Question</th>
                    <th style="width:10%">Grade</th>
                    <th class="hidden-phone fontsize15" style="width:15%">Created By / Date</th>
                    <th style="width:14%">Actions</th>
                  </tr>
                </thead>
                <tbody>
   
                  <?php   $i=(($this->currentPage-1)*$perPage)+1; if($this->totalRecord > 0){ foreach ($this->questions as $q){
                  if(empty($q['grade_name']))
                  	{
                  		$tblCategoryGrade	= new Application_Model_DbTable_QuestionCategoryGrade();
                  		$gradeData			= $tblCategoryGrade->getgradesInfoUsingCategory($q['category_id']);
                  		$gradeVal = '';
                  		for($k=0;$k<count($gradeData);$k++)
                  		{
   							if($k == 0){
   								$gradeVal = $gradeData[$k]['grade_name'];
   							}   
   							if($k == (count($gradeData)-1)){
   								$gradeVal = $gradeVal." - ".$gradeData[$k]['grade_name'];
   							}            			
                  		}
                 	}
                 	$questionView = My_Functions::generateImages($q['question_equation_images'], $q['question_display']);
                 	
                  	?>
                  <tr class="odd gradeX">
                    <td><?php echo $i;?>&nbsp;</td>
                    <td><?php echo strtoupper($q['category_code']);?>&nbsp;</td>
                    <td>
                    	<?php 
                    	
                    	if(!empty($questionView)){
                    	echo nl2br($questionView);
                    	}else{
                    	echo nl2br($q['question']);}?>
                    </td>
                    <td><?php if(!empty($q['grade_name'])){echo $q['grade_name'];}else{echo $gradeVal;}?>&nbsp;</td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo $q['created_by']?$q['created_by']:'--';?><br>
                    <?php echo formatDate($q['created_date']);?>
                    </td>
                    <td class="center">&nbsp; 
                    <a href="<?php echo $this->url(array('controller' =>'questions','action'=>'questiondetail','module'=>'admin','id' =>$q['bal_question_id'],'type' => $actionName),null,true);?>" class='iframe' title="View this question">
                    <img src="<?php echo $this->baseUrl();?>/assets_admin/images/preview.png"   border="0" />
                    </a> &nbsp;&nbsp; 
                    <a href="<?php echo $this->url(array('controller' =>'questions','action'=>'question','module'=>'admin','edit_id' =>$q['bal_question_id'],'type' => $actionName),null,true);?>" class='iframe' title="Edit this question">
                    <img border="0" title="Edit" alt="Edit" src="<?php echo $this->baseUrl();?>/assets_admin/images/edit_icon.png">
                    </a>&nbsp;&nbsp;  
                     <a href="javascript:void(0)" class='iframe' onclick="approveQuestion('<?php echo curPageURL();?>',<?php echo $q['bal_question_id'];?>)" title="Approve this question">
                    <img src="<?php echo $this->baseUrl();?>/assets_admin/images/approve.png"  border="0" />
                    </a> 
                    </td>
                  </tr>
               
                  <?php $i++;} }else{ ?>
                  <tr class="odd gradeX">
                    <td colspan="6" style="text-align: center">NO RECORD FOUND</td>
                  </tr>
                  <?php }?>
                </tbody>
              </table>
              </div>
            </div>
          </div>
          <!-- END EXAMPLE TABLE PORTLET-->
          <?php if($this->totalRecord > $perPage){?>
          <form name="searchFormSort" id="searchFormSort" action="<?php  echo $this->url(array('controller' => 'questions', 'action' => 'questionlist', 'module' => 'admin'),null,true);?>" method="post" class="RecordPerPage">
            <span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" onchange="javascript:sub_per_page('<?php echo curPageURL();?>',this.value);" class="span6" tabindex="1" id="">
              <option value="10" <?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
              <option value="25" <?php if($perPage == '25'){ echo 'selected=selected';}?>>25</option>
              <option value="50" <?php if($perPage == '50'){ echo 'selected=selected';}?>>50</option>
              <option value="100" <?php if($perPage == '100'){ echo 'selected=selected';}?>>100</option>
              <option value="250" <?php if($perPage == '250'){ echo 'selected=selected';}?>>250</option>
              <option value="500" <?php if($perPage == '500'){ echo 'selected=selected';}?>>500</option>
            </select><span class="RecordPerPageSpan">&nbsp;entries</span>
            <input type="hidden" name="search_question" class="searchdata" value="<?php  echo $search_val;?>" />
          </form>
          <?php }?>
          <?php  	// pagination start
					 	if($this->totalRecord !='')
					 	{
							if($this->totalRecord > $perPage)
							{
								echo $this->paginationControl($this->questions, 'Sliding', 'paginationquestion.phtml', array('perpage' =>$perPage));
							}
						}
						
					// pagination ends ?>
          <script language="javascript">
							function sub_per_page(url,value)
							{
								var p =url.indexOf("/perpage");
								if(p == -1)
								{
									var urlone = url;
								}
								else
								{
									var urlone = url.split('/perpage')[0];		
								}
								url = urlone+'/perpage/'+value;
								window.location= url;
							}
							</script>
        </div>
      </div>
    </div>
    <!-- END PAGE CONTENT-->
  </div>
  <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>
	
	/*$(document).ready(function(){
		var sorting =[0,5];
		applyDataTable('questionlist',sorting);
	});
	$("#questionlist_length").css('display','none');
	$("#questionlist_filter").css('display','none');
	$("#questionlist_paginate").css('display','none');
	*/
	</script>
<script>
	/*function applyDataTable(tableid,sorting)
	{
		$(document).ready(function() {
			oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
				               {
				                  bSortable: false,
				                  aTargets: sorting,
				               }
				             ]				
			});
		} );
	}*/
	</script>
