<script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php 
 if(isset($this->standard_id)) 
 {
 	$standard_ids	= $this->standard_id;
 }
?>
<?php $perPage = $this->perpage;
$actionName = str_replace(' ', '', Zend_Controller_Front::getInstance()->getRequest()->getActionName());?>
<!-- BEGIN PAGE -->

<div id="body">
  <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <div id="widget-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button">×</button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">
      <p>Here will be a configuration form</p>
    </div>
  </div>
  <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <!-- BEGIN PAGE CONTAINER-->
  <div class="container-fluid">
    <?php if(isset($this->success) && $this->success != ''){?>
    <div id="success" class="alert alert-success">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->success;?></div>
    <?php }?>
    <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>
    <div id="exception" class="alert alert-error">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->error;?> </div>
    <?php     	
        		 }
        	 ?>
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
      <div class="span12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <ul class="breadcrumb">
          <li> <i class="icon-home"></i> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span> </li>
          <li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlist', 'module' => 'admin'), null, true);?>">Question Manager</a> <span class="divider">/</span> </li>
          <li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'expiredquestionlist', 'module' => 'admin'), null, true);?>">Expired Questions</a> </li>
          <li style="float:right"><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'question', 'module' => 'admin', 'type'=> $actionName), null, true);?>" style="cursor:pointer;"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/add_trophy.png" /></a></li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div id="page" class="dashboard">
      <div class="row-fluid">
        <div class="span12">
          <!-- BEGIN EXAMPLE TABLE PORTLET-->
          <div class="widget">
            <div class="widget-title TabsTop">
              <ul>
                  <li>
                      <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlist', 'module' => 'admin'), null, true);?>">
	              Questions
	              </a>
                  </li>
                  <li>
	              <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'expiringquestionlist', 'module' => 'admin'), null, true);?>">
	              Expiring Questions
	              </a>
                  </li>
                  <li>
                      <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'expiredquestionlist', 'module' => 'admin'), null, true);?>" class="active" >
	              Expired Questions
	              </a>
                  </li>
                  <li>
          		  <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'draftquestionlist', 'module' => 'admin'), null, true);?>">
          		  Draft Questions
          	      </a> 
                  </li>
              </ul>
            </div>
            <div class="widget-body">
              <form id="searchfilter" method="post" name="searchfilter"  class="Margin_0">
                <?php 
						$search_val='';
						if($this->search_question) {
				  
					if($this->search_question != '')
					$search_val= $this->search_question;	
				}			
				
							?>
                <div class="row-fluid">
                <div class="control-group">
                <label class="control-label" for="input3">
                <input type="text"  class="span6 popovers SearchAdmin" placeholder="Search Keyword"  id="search_question" name="search_question" />
                <input type =""button"" class="btn btn-primary SearchButton" id="searchquestion" value="Search Question" onclick="getfiltereexpiredquestion();">
                </div>
                </div>
              </form>
              <?php if($search_val != '') {
				 
							?>
              <ul class="breadcrumb">
                <li> You have searched for : </li>
                <li> <?php echo $search_val;?> </li>
                <li><span class="divider">/</span> <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'expiredquestionlist', 'module' => 'admin'), null, true);?>">Clear search</a> </li>
              </ul>
              <?php }?>
              <div class="overFlow">
              <table class="table table-striped table-bordered" id="questionlist">
                <thead>
                  <tr>
                    <th style="width:6%">#</th>
                    <th style="width:17%">Category</th>
                    <th style="width:23%">Question</th>
                    <th style="width:10%">Grade</th>
                    <th style="width:15%">Created By / Date</th>
                    <th style="width:15%">Modified By / Date</th>
                    <th style="width:14%">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <?php   $i=(($this->currentPage-1)*$perPage)+1; if($this->totalRecord > 0){  foreach ($this->questions as $q){
                  if(empty($q['grade_name']))
                  	{
                  		$tblCategoryGrade	= new Application_Model_DbTable_QuestionCategoryGrade();
                  		$gradeData			= $tblCategoryGrade->getgradesInfoUsingCategory($q['category_id']);
                  		$gradeVal = '';
                  		for($k=0;$k<count($gradeData);$k++)
                  		{
   							if($k == 0){
   								$gradeVal = $gradeData[$k]['grade_name'];
   							}   
   							if($k == (count($gradeData)-1)){
   								$gradeVal = $gradeVal." - ".$gradeData[$k]['grade_name'];
   							}            			
                  		}
                 	}
                  	?>
                  <tr class="odd gradeX">
                    <td><?php echo $i;?>&nbsp;</td>
                    <td><?php echo strtoupper($q['category_code']);?>&nbsp;</td>
                    <td><?php echo nl2br($q['question']);?>&nbsp;</td>
                    <td><?php if(!empty($q['grade_name'])){echo $q['grade_name'];}else{echo $gradeVal;}?>&nbsp;</td>
                    <td class="hidden-phone center fontsize15">&nbsp;<?php echo $q['created_by']?$q['created_by']:'--';?><br>
                    <?php echo formatDate($q['created_date']);?></td>
					<td class="hidden-phone center fontsize15">&nbsp;<?php echo $q['modified_by']?$q['modified_by']:'--';?><br>
					<?php echo $q['modified_Date']?formatDate($q['modified_Date']):'';?>
					</td>
                    <td class="center">&nbsp; 
                    	<a href="<?php echo $this->url(array('controller' =>'questions','action'=>'questiondetail','module'=>'admin','id' =>$q['bal_question_id'],'type' => $actionName),null,true);?>" class='iframe'>
                    	<img src="<?php echo $this->baseUrl();?>/assets_admin/images/preview.png" alt="View Category Detail" title="View this question" border="0" />
                    	</a>&nbsp;&nbsp; 
                    	<a href="<?php echo $this->url(array('controller' =>'questions','action'=>'question','module'=>'admin','id' =>$q['bal_question_id'],'type' => $actionName),null,true);?>"  value="Create a copy" class='iframe'>
                    	<img border="0" title="Create a copy" alt="Create a copy" src="<?php echo $this->baseUrl();?>/assets_admin/images/copy.png" height="17px;" width="17px;">
                    	</a>
                    </td>
                  </tr>
                  <?php $i++;}} else {	?>
                  <tr class="odd gradeX">
                    <td class="hidden-phone" colspan="7" style="text-align: center">NO RECORD FOUND</td>
                  </tr>
                  <?php }?>
                </tbody>
              </table>
              </div>
            </div>
          </div>
          <!-- END EXAMPLE TABLE PORTLET-->
          <?php if($this->totalRecord > $perPage){?>
          <form name="searchFormSort" id="searchFormSort" action="<?php  echo $this->url(array('controller' => 'questions', 'action' => 'questionlist', 'module' => 'admin'),null,true);?>" method="post" class="RecordPerPage">
            <span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" onchange="javascript:sub_per_page('<?php echo curPageURL();?>',this.value);" class="span6" tabindex="1" id="">
              <option value="10" <?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
              <option value="25" <?php if($perPage == '25'){ echo 'selected=selected';}?>>25</option>
              <option value="50" <?php if($perPage == '50'){ echo 'selected=selected';}?>>50</option>
              <option value="100" <?php if($perPage == '100'){ echo 'selected=selected';}?>>100</option>
              <option value="250" <?php if($perPage == '250'){ echo 'selected=selected';}?>>250</option>
              <option value="500" <?php if($perPage == '500'){ echo 'selected=selected';}?>>500</option>
            </select><span class="RecordPerPageSpan">&nbsp;entries</span>
            <input type="hidden" name="search_question" class="searchdata" value="<?php  echo $search_val;?>" />
          </form>
          <?php }?>
          <?php  	// pagination start
					 	if($this->totalRecord !='')
					 	{
							if($this->totalRecord > $perPage)
							{
								echo $this->paginationControl($this->questions, 'Sliding', 'paginationquestion.phtml', array('perpage' =>$perPage));
							}
						}
						
					// pagination ends ?>
          <script language="javascript">
							function sub_per_page(url,value)
							{
								var p =url.indexOf("/perpage");
								if(p == -1)
								{
									var urlone = url;
								}
								else
								{
									var urlone = url.split('/perpage')[0];		
								}
								url = urlone+'/perpage/'+value;
								window.location= url;
							}
							</script>
        </div>
      </div>
    </div>
    <!-- END PAGE CONTENT-->
  </div>
  <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>
	
	$(document).ready(function(){
		var sorting =[0,4];
		applyDataTable('questionlist',sorting);
	});
	$("#questionlist_length").css('display','none');
	$("#questionlist_filter").css('display','none');
	$("#questionlist_paginate").css('display','none');
	
	</script>
<script>
	function applyDataTable(tableid,sorting)
	{
		$(document).ready(function() {
			oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
				               {
				                  bSortable: false,
				                  aTargets: sorting,
				               }
				             ]				
			});
		} );
	}
	</script>
