<?php require_once APPLICATION_PATH.'/../library/function_image_array.php';
$dataQuestion = $this->detailData;
if(!empty($dataQuestion['question']['question_equation_images'])){
	$questionImages = My_Functions::generateImages($dataQuestion['question']['question_equation_images'],$dataQuestion['question']['question_display']);
}else{
	$questionImages = $dataQuestion['question']['question'];
}

if(!empty($dataQuestion['question']['explanation_equation_image_name'])){
	$explanationImages = My_Functions::generateImages($dataQuestion['question']['explanation_equation_image_name'],$dataQuestion['question']['explanation_equation']);
}else{
	$explanationImages = $dataQuestion['question']['explanation'];
}

	 if($dataQuestion['option']['answer'] == 'Y'){
	 	if(!empty($dataQuestion['option']['option_equation_image_name'])){
			$rightAnswer = My_Functions::generateImages($dataQuestion['option']['option_equation_image_name'],$dataQuestion['option']['option_equation']);
	 	}else{
	 		$rightAnswer = $dataQuestion['option']['option'];
	 	}
}
?>
<!-- BEGIN PAGE -->
<div id="body">
	<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<div id="widget-config" class="modal hide">
		<div class="modal-header">
			<button data-dismiss="modal" class="close" type="button">×</button>
			<h3>Widget Settings</h3>
		</div>
		<div class="modal-body">
			<p>Here will be a configuration form</p>
		</div>
	</div>
	<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<!-- BEGIN PAGE CONTAINER-->
	<div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->
		<div class="row-fluid">
			<div class="span12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<ul class="breadcrumb">
					<li><i class="icon-home"></i> <a
						href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a>
						<span class="divider">/</span></li>
					<li><a
						href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlist', 'module' => 'admin'), null, true);?>"">Question
							Manager</a> <span class="divider">/</span></li>
					<li><a
						href="#">Questiondetail</a>
						<span class="divider">/</span></li>
				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>
		<!-- END PAGE HEADER-->
		<!-- BEGIN PAGE CONTENT-->
		<div id="page">
			<div class="row-fluid">
				<div class="span12">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="widget">
						<div class="widget-title">
                     	
									<h4>Question Detail</h4>
									
								</div>
						<div class="widget-body form">
							<!-- BEGIN FORM-->
							
							
							<form name="questions_form" id="questions_form"
								action="<?php echo $this->url(array('controller' =>'questions', 'action' =>'question', 'module' =>'admin'),null,true);?>"
								enctype="multipart/form-data" method="post"
								class="form-horizontal" onSubmit="return questionValidate('<?php echo $id ?>');">
                                                                <input type="hidden" name="csvEqImages" id="csvEqImages" value="<?php echo $csvEqImages; ?>"/>
								<table cellpadding="5" cellspacing="0" width="100%">
									
								
									


									<!-- Block for math quations -->


									<tr>
										    <td colspan="2"><label class="control-label Grey" for="input3"><span
												class="error"></span>Question:</label>
											<div class="controls">
                                                       <?php echo $questionImages;?>                                        
											</div></td>
</tr>											
                                                                                    

									<tr>
										<td colspan="2"><label class="control-label Grey" for="input3">Explanation:</label>
											<div class="controls">
											 <?php echo $explanationImages;?> 
													</div></td>
									</tr>
								
									
									<tr>
										<td><label class="control-label Grey" for="input3"><span
												class="error"></span>Right Answer:</label>
											<div class="controls">
											<?php echo $rightAnswer;?> 
											</div></td>
									</tr>
								</table>
								<div class="form-actions">
									<input type="hidden" name="returnPageUrl" id="returnPageUrl" value="<?php echo $page;?>">
									<input type="button" class="btn"
										 onClick="returnPage('questions','<?php echo $page; ?>');" 
										value="Back">
								</div>
							</form>
							<!-- END FORM-->
						</div>
					</div>
					<!-- END SAMPLE FORM PORTLET-->
				</div>
			</div>
		</div>
		<!-- END PAGE CONTENT-->
	</div>
	<!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
<script type="text/javascript">
 	$(document).ready(function(){ 
	 var category_id_hidden = $("#category_id_hidden").val();
	 if(category_id_hidden != '')
	 {
		 getgrade(category_id_hidden);
	 }	
 	});
 	var a=new EqTextArea('question_equation_image','question_equation');
	EqEditor.add(a,false);
	var src = $('#question_equation_image').attr('src');
	$('#question_equation_image1').val(src);
	var a=new EqTextArea('explanation_equation_image','explanation_equation');
	EqEditor.add(a,false);
	var src1 = $('#explanation_equation_image1').attr('src');
	$('#question_equation_image1').val(src1);
	var a=new EqTextArea('right_equation_image','right_answer_equation');
	EqEditor.add(a,false);
	var src2 = $('#right_equation_image').attr('src');
	$('#right_equation_image1').val(src2);
	var a=new EqTextArea('wrong_equation_image','wrong_answer1_equation');
	EqEditor.add(a,false);
	var src3 = $('#wrong_equation_image').attr('src');
	$('#wrong_equation_image1').val(src3);
	var a=new EqTextArea('wrong_answer2_equation_image','wrong_answer2_equation');
	EqEditor.add(a,false);
	var src4 = $('#wrong_answer2_equation_image').attr('src');
	$('#wrong_answer2_equation_image2').val(src4);
	var a=new EqTextArea('wrong_answer3_equation_image','wrong_answer3_equation');
	EqEditor.add(a,false);
	var src5 = $('#wrong_answer3_equation_image').attr('src');
	$('#wrong_answer2_equation_image3').val(src5);
        
        tinymce.remove('textarea');
</script>
