<?php 
require_once APPLICATION_PATH.'/../library/function_image_array.php';
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets_admin/css/colorbox.css"/>
<script src="<?php echo $this->baseUrl();?>/assets_admin/js/jquery.colorbox.js"></script>
<script>
  $(function() {
    $( "#expiryDate" ).datepicker({
    	dateFormat: "yy-mm-dd",minDate: +1});
  });
</script>
<?php
$serverUrl = new Zend_View_Helper_ServerUrl();
$baseUrl = new Zend_View_Helper_BaseUrl();
$alliasStr = uniqid ();
$adminInfoSession = new Zend_Session_Namespace ( 'adminInfo' );
$category_id = $question = $answerExplanation = $difficulty_level = "";
if (! empty ( $adminInfoSession->questionData )) {
	$data = $adminInfoSession->questionData;
	
	unset ( $adminInfoSession->questionData );
	$question = $data ['question'];
	$difficulty_level = $data ['difficulty_level'];
	$grade_id = $data ['grade_id'];
	$category_id = $data ['category_id'];
	$url_of_question = $data ['url_of_question'];
	$question_image_url = $data ['question_image_url'];
	$answer_image_url = $data ['answer_image_url'];
	$explanation = $data ['explanation'];
	$set_question = $data ['set_question'];
	$refer_book_name = $data ['refer_book_name'];
	$refer_book_chapter = $data ['refer_book_chapter'];
	$refer_article_url = $data ['refer_article_url'];
	$wolframalphaquery = $data ['wolframalphaquery'];
	$wrongoption [1] = $data ['wrong_answer1'];
	$wrongoption [2] = $data ['wrong_answer2'];
	$wrongoption [3] = $data ['wrong_answer3'];
	$rightOption = $data ['right_answer'];
	$rightOption = $data ['right_answer'];
	$expiryDate = $data['expiryDate'];
}
if ($this->edit_id != '' || $this->id != '') {
	if($this->edit_id != ''){
		$id = $this->edit_id;
	}
	if($this->id != ''){
		$copyId = $this->id;
 	}
 	
 	
  	$question = $this->question->question;
        $question_display = $this->question->question_display;
        $csvEqImages = $this->question->question_equation_images;
	$questionEquation = $this->question->question_equation;
	$questionEquationImage = $this->question->question_equation_image_name;
	$difficulty_level = $this->question->difficulty_level;
	$grade_id = $this->question->grade_id;
	$category_id = $this->question->category_id;
	$url_of_question = $this->question->url_of_question;
	$question_image_url = $this->question->question_image_url;
	$answer_image_url = $this->question->answer_image_url;
	$explanation = $this->question->explanation;
	$explanationEquation = $this->question->explanation_equation;
	$explanationEquationImage = $this->question->explanation_equation_image_name;
        
        
        $answerExplanation = $this->question->answer_explanation;
	$anserExplanationEquation = $this->question->answer_explanation_equation;
	$answerexplanationEquationImages = $this->question->answer_explanation_image_name;
        
        
        
                                                                            
                                                                            
        
	$set_question = $this->question->set_question;
	$refer_book_name = $this->question->refer_book_name;
	$refer_book_chapter = $this->question->refer_book_chapter;
	$refer_article_url = $this->question->refer_article_url;
	$wolframalphaquery = $this->question->wolframalphaquery;
	
	/***************block for generate image for view*****************/
	$questionImages = My_Functions::generateImages($csvEqImages,$question_display);
	$explanationImages = My_Functions::generateImages($explanationEquationImage,$explanationEquation);
        $anserExplanationImage = My_Functions::generateImages($answerexplanationEquationImages,$anserExplanationEquation);
	
    if($this->edit_id != ''){
		$expiryDate = $this->question->expiry_date;
	} else {
		$expiryDate = null;
	}
	$i = 1;
	
	
	foreach ( $this->options as $options ) {
		if ($options->answer == 'N') {
			$wrongoption [$i] = htmlentities($options->option);
			$wrongoptionid [$i] = $options->question_option_id;
			$wrongoptionequation [$i] = $options->option_equation;
			$wrongoptionEquationImageName [$i] = $options->option_equation_image_name;
			$wrongImages[$i] = My_Functions::generateImages($options->option_equation_image_name, $options->option_equation);
			$i ++;
		} else {
			$rightOption = htmlentities($options->option);
			$rightoptionid = $options->question_option_id;
			$rightOptionEquation = $options->option_equation;
			$rightOptionEquationImage = $options->option_equation_image_name;
			$rightImages = My_Functions::generateImages($options->option_equation_image_name, $options->option_equation);
		}
	}
}

$categories = $this->categories;
foreach ( $categories as $cat ) {
	if ($category_id == $cat->category_id) {
	$str = $cat->category_code;
			if(substr($str,0,17) == 'ccss.math.content'){
				$frameId = 7;
			}elseif (substr($str,0,9) == 'bal.maths'){
				$frameId = 26;
			}
			elseif (substr($str,0,18) == 'bal.currentaffairs'){
				$frameId = 23;
			}
}
}
?>
					
<input type ="hidden" id ="frameWorkEdit" value ="<?php echo $frameId;?>">
<input type ="hidden" id ="frameWorkHidden" value ="<?php echo $frameId;?>">
<!-- BEGIN PAGE -->
<div id="body">
	<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<div id="widget-config" class="modal hide">
		<div class="modal-header">
			<button data-dismiss="modal" class="close" type="button">×</button>
			<h3>Widget Settings</h3>
		</div>
		<div class="modal-body">
			<p>Here will be a configuration form</p>
		</div>
	</div>
	<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<!-- BEGIN PAGE CONTAINER-->
	<div class="container-fluid">
         <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success">
			<button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php
									if (isset ( $this->error ) && $this->error != '') {
										?>		 <div id="exception" class="alert alert-error">
			<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php
									}
									?>
            <!-- BEGIN PAGE HEADER-->
		<div class="row-fluid">
			<div class="span12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->

				<ul class="breadcrumb">
					<li><i class="icon-home"></i> <a
						href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a>
						<span class="divider">/</span></li>
					<li><a
						href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlist', 'module' => 'admin'), null, true);?>"">Question
							Manager</a> <span class="divider">/</span></li>
					<li><a
						href="#"><?php if(isset($id) && $id != ''){echo "Edit";}else{echo "Add";}?> Question</a>
						</li>
				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>
		<!-- END PAGE HEADER-->
		<!-- BEGIN PAGE CONTENT-->
		<div id="page">
			<div class="row-fluid">
				<div class="span12">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="widget">
						<div class="widget-title">
                     	<?php if($this->edit_id != ''){?>
									<h4>Edit Question</h4>
							<?php }else{?>
									<h4>Add Question</h4>
							<?php }?>								
								</div>
						<div class="widget-body form">
							<!-- BEGIN FORM-->
							<div
								class="control-group<?php if($id != ''){echo ' DivHidden';}?>">
								<div class="row-fluid">
									<div class="">
										<div id="standard_div" class="dataTables_length">
											<label class="filter_padding"> <select name="standard"
												id="standard" class="standardbox" size="1"
												aria-controls="sample_1"
												onchange="getGradeInfoUsingStandardId(this.value);">
													<option value="" selected="selected">Standard</option>
														<?php
														$standard = $this->standard;
														foreach ( $standard as $std ) {
															?>
														<option value="<?php echo $std->standard_id;?>"><?php echo $std->name;?></option>
														<?php
														}
														?>
													</select>
											</label>
										</div>
                                                                                <div id="grade_div" class="dataTables_length">
											<label class="filter_padding"> <select name="grades"
												class="gradebox" id="grades" size="1"
												aria-controls="sample_1">
													<option value="" selected="selected">Grade</option>
											</select>
											</label>
										</div>
										<div id="framework_div" class="dataTables_length">
											<label class="filter_padding"> <select name="framework"
												class="frameworkbox" size="1" aria-controls="sample_1"
												id="framework">
													<option value="" selected="selected">Framework</option>
											</select>

											</label>
										</div>
										<div id="domain_div" class="dataTables_length">
											<label class="filter_padding"> <select name="domain"
												class="domainbox" id="domain" size="1"
												aria-controls="sample_1">
													<option value="" selected="selected">Domain</option>
											</select>
											</label>
										</div>
										<input type="button" class="btn btn-primary"
											id="search_category" value="Search Category"
											onclick="searchCategory()">
									</div>
								</div>
							</div>
							<hr>
							<form name="questions_form" id="questions_form"
								action="<?php echo $this->url(array('controller' =>'questions', 'action' =>'question', 'module' =>'admin'),null,true);?>"
								enctype="multipart/form-data" method="post"
								class="form-horizontal" onSubmit="return questionValidate('<?php echo $id ?>');">
                                                                <input type="hidden" name="csvEqImages" id="csvEqImages" value="<?php echo $csvEqImages; ?>"/>
								<table cellpadding="5" cellspacing="0" width="100%">
									<tr>
										<td width="50%"><label class="control-label Grey" for="input3"><span
												class="error">*</span>Category ID:</label>
											<div class="controls" id="category_div">
												<select class="span8" name="category" id="category" size="1"
													aria-controls="sample_1" onchange="getgrade(this.value);"
													<?php if(!empty($id) && !empty($copyId)){echo 'disabled="disabled"';}?>>
													<option value="" selected="selected">Select</option>
														<?php
														if ($id != '' || $copyId != '') {
															foreach ( $categories as $cat ) {
																if ($category_id == $cat->category_id) {
																	?>
														<option value="<?php echo $cat->category_id;?>"
														selected="selected"><?php echo $cat->category_code;?></option>
														<?php
																}
															}
														}
														?>
												</select>
												<div style="color:#FF0000;display:none" id="category_error"></div>
											</div></td>
										<td width="50%"> <?php if(isset($id) && $id != ''){?>
											<div class="FloatLeft">
												<button type="button" class="btn btn-primary"
													onClick="makeCategoryEditable();">Edit</button>
											</div>
		                                 	<?php }?>
		                                </td>
									</tr>
									<tr class="expiryDateDIV">
										<td colspan="2"><label class="control-label Grey" for="input3"><span
												class="error">*</span>Expiry Date:</label>
											<div class="controls">
												<input class="span6 popovers ReadOnlyDate" id="expiryDate"
													name="expiryDate" type="text" disabled="disabled" readonly="readonly"
													value="<?php echo $expiryDate;?>" />
                                                                                                <div style="color:#FF0000;display:none" id="expiryDate_error"></div>
												<input type="hidden" name="copyId" id="copyId" value="<?php if(isset($copyId) && !empty($copyId)){echo $copyId;}?>">
											</div>
											</div></td>

									</tr>
									<tr class="TrHidden">
									<?php //if(isset($id) && $id != ''){?>
									<input type="hidden" name="frameHidden" id="frameHidden">
									<?php //}?>
										<td><label class="control-label Grey" for="input3">Framework:</label>
											<div class="controls">
												<input class="span8 popovers" id="frameworkDetail"
													type="text" disabled="disabled" />
											</div></td>
										<td><label class="control-label Grey" for="input3">Grade:</label>
											<div class="controls">
												<input class="span8 popovers" id="gradeDetail" type="text"
													disabled="disabled" />
											</div></td>
									</tr>
									<tr class="TrHidden">
										<td><label class="control-label Grey" for="input3">Domain:</label>
											<div class="controls">
												<input class="span8 popovers" id="domainDetail" type="text"
													disabled="disabled" />
											</div></td>
										<td><label class="control-label Grey" for="input3">Sub Topic
												Detail:</label>
											<div class="controls">
												<input class="span8 popovers" id="subtopicDetail"
													type="text" disabled="disabled" />
											</div></td>
									</tr>
									<tr>
										<td><label class="control-label Grey" for="input3">Question
												Image URL:</label>
											<div class="controls">
												<input type="text" class="span8 popovers"
													id="question_image_url" name="question_image_url"
													value="<?php if (isset($question_image_url)){echo $question_image_url;}?>" />
                                             <div style="color:#FF0000;display:none" id="question_image_url_error"></div>
                                            </div></td></tr>
                                    <tr><td colspan="2"><label class="control-label Grey" for="input3">URL of
												Question:</label>
											<div class="controls">
		                                 	<?php if(!empty($id) && !empty($url_of_question)){?>
                                                <?php //$question_url = HOST_NAME."/question/questiondetail/".QUESTION_KEY."/".$url_of_question; ?>
                                                <?php $question_url = $serverUrl->serverUrl() . $baseUrl->baseUrl("/question/questiondetail/".QUESTION_KEY."/".$url_of_question); ?>
			                                    <a target="_blank"
                                                   href="<?php echo $question_url; ?>"><?php echo $question_url; ?></a><input
													type="hidden" class="span6 popovers" id="url_of_question"
													name="url_of_question"
													value="<?php echo $url_of_question;?>" onblur="GetImageOfText(this.id,'question_equation_image','question_equation_image1');" />
			                                <?php }else{?>
			                                	<input type="text"
													class="span8 popovers" id="url_of_question"
													name="url_of_question"
													value="<?php if(!empty($id)){echo $alliasStr;}?>"
													readonly="readonly" onblur="GetImageOfText(this.id,'question_equation_image','question_equation_image1');" />
			                                <?php }?>
		                                 	</div></td>

									</tr>


									<!-- Block for math quations -->


									<tr>
										    <td colspan="2"><label class="control-label Grey" for="input3"><span
												class="error">*</span>Question:</label>
											<div class="controls">
                                                <textarea class = "span8" id="question" name="question" onblur="getQuestionDescriptionWithImages(this.value,'questionIimage');"><?php echo $question;?></textarea>
                                                <div style="color:#FF0000;display:none" id="question_error"></div>&nbsp;<a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a>
                                                                                                <!--<input type="text" id="question" name="question" class="span8 popovers" style="width:700px;" onblur="getQuestionDescriptionWithImages(this.value);" value="<?php //if (isset ( $question )) { echo $question; } ?>" />-->
                                                                                                <input type="hidden" name="edit_id" value="<?php echo $id;?>" /> 
                                                                                                <input type="hidden" name="category_id_hidden" id="category_id_hidden" value="<?php echo $category_id;?>" />
												<input type="hidden" name="grade_id_hidden" id="grade_id_hidden" value="<?php echo $grade_id;?>" /> 
                                                                                                <input type="hidden" name="alliase" id="alliase" value="<?php echo $alliasStr;?>">
											</div></td>
</tr>											
                                                                                    
<tr>
    <td colspan="2"><!--<label class="control-label Grey" for="input3"><span
												class="error"></span>Equation in question:</label>-->
											<div class="controls">
                                                                                            <!--
                                                                                            <input type="text" class="span8 popovers"
													id="question_equation" name="question_equation"
													value="&nbsp;<?php // if (isset ( $question )) { echo $questionEquation; } ?>"
												<a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation">
													<img src="<?php //echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" />
												</a>
                                                                                            <br>
                                                                                            -->
                                                                                                <div id="questionIimage" class = "ImamgeBlock">
                                                                                                    <?php if(isset($questionImages) && $questionImages != ''){
                                                                                                       echo  $questionImages;
                                                                                                    }?>
                                                                                                    </div>
												<input type="hidden"
													value="<?php echo HOST_NAME.'images/equation_image/'.$questionEquationImage;?>"
													id="question_equation_image1"
													name="question_equation_image1"> <input type="hidden"
													name="old_image_name_question"
													value="<?php if(isset($csvEqImages) && !empty($csvEqImages)){ echo $csvEqImages;};?>">
												
											</div></td>
</tr>
									<tr>
										<td colspan="2"><label class="control-label Grey" for="input3">Factoid:</label>
											<div class="controls">
												<textarea rows="" class="span8" cols="" id="explanation" onblur="getQuestionDescriptionWithImages(this.value,'explanationImage');"
													name="explanation"><?php if (isset($explanation)){echo $explanation;} ?></textarea> <div style="color:#FF0000;display:none" id="explanation_error"></div><a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a>
											</div></td>
									</tr>
									<tr>
										<td colspan="2" class="">
										<div class="controls">
												<div id="explanationImage"  class = "ImamgeBlock">
												<?php if(isset($explanationImages) && $explanationImages != ''){
                                                                                                       echo  $explanationImages;
                                                                                                    }?>
                                                                                                </div>
												<input type="hidden"
													value="<?php echo HOST_NAME.'images/equation_image/'.$explanationEquationImage?>"
													id="explanation_equation_image1"
													name="explanation_equation_image1">
													<input type="hidden"
													name="old_image_name_explation"
													value="<?php if(isset($explanationEquationImage) && !empty($explanationEquationImage)){ echo $explanationEquationImage;};?>">
												
											</div></td>

									</tr>
									<tr>
										<td colspan="6">

											<hr>
										</td>
									</tr>
									<tr>
										<td><label class="control-label Grey" for="input3"><span
												class="error">*</span>Right Answer:</label>
											<div class="controls">
												<input type="text" class="span8 popovers" id="right_answer"
													name="right_answer"
													value="<?php if (isset($rightOption)){echo $rightOption;}?>"  onblur="getQuestionDescriptionWithImages(this.value,'rightImage');"/>
													<div style="color:#FF0000;display:none" id="right_answer_error"></div>
													<a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a>
												<input type="hidden" name="rightoptionid" id="rightoptionid"
													value="<?php echo $rightoptionid;?>" />
											</div></td>
										<td id=""><label class="control-label Grey"
											for="input3">Answer Image URL:</label>
											<div class="controls">
												<input type="text" class="span8 popovers"
													id="answer_image_url" name="answer_image_url"
													value="<?php if (isset($answer_image_url)){echo $answer_image_url;} ?>" />
													<div style="color:#FF0000;display:none" id="answer_image_url_error"></div>
											</div></td>
									</tr>
									<tr>
									<td>
									<div class="controls">
										<div id="rightImage"  class = "ImamgeBlock">
										<?php if(isset($rightImages) && $rightImages != ''){
                                                                                                       echo  $rightImages;
										}?>
                                                                                </div>
										<input type="hidden"
													value="<?php echo HOST_NAME.'images/equation_image/'.$rightOptionEquationImage;?>"
													id="right_equation_image1" name="right_equation_image1">
													<input type="hidden"
													name="old_image_name_right"
													value="<?php if(isset($rightOptionEquationImage) && !empty($rightOptionEquationImage)){ echo $rightOptionEquationImage;};?>">
													</div>
										
										</td>
										<td>
									<div class="controls">
											</div>
										</td>			
									
									</tr>
									
									<tr>
                                                                            
                                                                            <td><label class="control-label Grey" for="input3">Factoid:</label>
											<div class="controls">
												<input type="text" class="span8 popovers" onblur="getQuestionDescriptionWithImages(this.value,'anserExplanationImage');"
													id="answer_explanation" name="answer_explanation"
                                                                                                        value="<?php echo htmlentities($answerExplanation); ?>" />
													<div style="color:#FF0000;display:none" id="answer_explanation_error"></div><a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a> 
											</div></td>
										<td id=""><label class="control-label Grey"
											for="input3"><span class="error">*</span>Wrong Answer 1:</label>
											<div class="controls">
												<input type="text" class="span8 popovers" id="wrong_answer1" onblur="getQuestionDescriptionWithImages(this.value,'wrongImage');"
													name="wrong_answer1"
													value="<?php if (isset($wrongoption[1])){echo $wrongoption[1];}?>" /> 
													<div style="color:#FF0000;display:none" id="wrong_answer1_error"></div><a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a>
												<input type="hidden" name="wrongoptionid1"
													id="wrongoptionid1"
													value="<?php if (isset($wrongoptionid[1])){echo $wrongoptionid[1];} ?>" />
											</div></td>
									</tr>
										<tr>
										<td>
									<div class="controls">
                                                                            			<div id="anserExplanationImage"  class = "ImamgeBlock">
												<?php if(isset($answerexplanationEquationImages) && !empty($answerexplanationEquationImages)){
                                                                                                       echo  $anserExplanationImage;
                                                                                                    }?>
                                                                                                </div>
													<input type="hidden"
													name="old_image_name_answer_explation"
													value="<?php if(isset($answerexplanationEquationImages) && !empty($answerexplanationEquationImages)){ echo $answerexplanationEquationImages;};?>">
											
											</div>
										</td>
									<td>
									<div class="controls">
									<div id="wrongImage"  class = "ImamgeBlock">
									<?php if(isset($wrongImages[1]) && $wrongImages[1] != ''){
                                                                                                       echo  $wrongImages[1];
										}?>
                                                                        </div>
												<input type="hidden"
													value="<?php echo HOST_NAME.'images/equation_image/'.$wrongoptionEquationImageName[1];?>"
													id="wrong_equation_image1" name="wrong_equation_image1">
													<input type="hidden"
													name="old_image_name_wrong1"
													value="<?php if(isset($wrongoptionEquationImageName[1]) && !empty($wrongoptionEquationImageName[1])){ echo $wrongoptionEquationImageName[1];}?>">
												
											</div>
										</td>
									</tr>
									<tr>
										<td><label class="control-label Grey" for="input3"><span
												class="error">*</span>Wrong Answer 2:</label>
											<div class="controls">
												<input type="text" class="span8 popovers" id="wrong_answer2" onblur="getQuestionDescriptionWithImages(this.value,'wrong2Image');"
													name="wrong_answer2"
													value="<?php if (isset($wrongoption[2])){echo $wrongoption[2];}?>" /> 
													<div style="color:#FF0000;display:none" id="wrong_answer2_error"></div><a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a>
												<input type="hidden" name="wrongoptionid2" onblur="getQuestionDescriptionWithImages(this.value,'wrong2Image');"
													id="wrongoptionid2"
													value="<?php if (isset($wrongoptionid[2])){echo $wrongoptionid[2];}?>" />
											</div></td>
										
										<td id=""><label class="control-label Grey"
											for="input3"><span class="error">*</span>Wrong Answer 3:</label>
											<div class="controls">
												<input type="text" class="span8 popovers" id="wrong_answer3" onblur="getQuestionDescriptionWithImages(this.value,'wrong3image');"
													name="wrong_answer3"
													value="<?php if (isset($wrongoption[3])){echo $wrongoption[3];}?>" />
													<div style="color:#FF0000;display:none" id="wrong_answer3_error"></div><a
													href="http://www.codecogs.com/latex/eqneditor.php" title="Create equation"
													target="_blank" class="CreateEqualation TrHiddenQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/equation.png" border="0" /></a>
												<input type="hidden" name="wrongoptionid3"
													id="wrongoptionid3" value="<?php echo $wrongoptionid[3];?>" />
											</div></td>
									</tr>
									
									
										<tr>
										<td>
										<div class="controls">													
										<div id="wrong2Image"  class = "ImamgeBlock">
										<?php if(isset($wrongImages[2]) && $wrongImages[2] != ''){
                                                                                                       echo  $wrongImages[2];
										}?>
                                                                                </div>
												<input type="hidden"
													value="<?php echo HOST_NAME.'images/equation_image/'.$wrongoptionEquationImageName[2];?>"
													id="wrong_answer2_equation_image2"
													name="wrong_answer2_equation_image2">
													<input type="hidden"
													name="old_image_name_wrong2"
													value="<?php if(isset($wrongoptionEquationImageName[2]) && !empty($wrongoptionEquationImageName[2])){ echo $wrongoptionEquationImageName[2];}?>">
												
											</div></td>
										
										<td>
										<div class="controls">	
										<div id="wrong3image"  class = "ImamgeBlock">
										<?php if(isset($wrongImages[3]) && $wrongImages[3] != ''){
                                                                                                       echo  $wrongImages[3];
										}?>
                                                                                </div>
												<input type="hidden"
													value="<?php echo HOST_NAME.'images/equation_image/'.$wrongoptionEquationImageName[3];?>"
													id="wrong_answer2_equation_image3"
													name="wrong_answer2_equation_image3">
													<input type="hidden"
													name="old_image_name_wrong3"
													value="<?php if(isset($wrongoptionEquationImageName[3]) && !empty($wrongoptionEquationImageName[3])){ echo $wrongoptionEquationImageName[3];}?>">
												
											</div></td>
									</tr>
									
									<tr>
										<td><label class="control-label Grey" for="input3"><span
												class="error">*</span>Difficulty Level:</label>
											<div class="controls">
												<select name="difficulty_level" class="span8"
													id="difficulty_level" size="1" aria-controls="sample_1">
													<option value="" selected="selected">Select</option>
													<option value="H"
														<?php if($difficulty_level == 'H'){echo "selected";}?>>High</option>
													<option value="M"
														<?php if($difficulty_level == 'M'){echo "selected";}?>>Medium</option>
													<option value="L"
														<?php if($difficulty_level == 'L'){echo "selected";}?>>Low</option>
												</select>
												<div style="color:#FF0000;display:none" id="difficulty_level_error"></div>
											</div></td>
										<td><label class="control-label Grey" for="input3"><span
												class="error">*</span>Grade:</label>
											<div class="controls" id="grades_div">
												<select class="span8" name="grades_val" id="grades_val"
													size="1" aria-controls="sample_1"
													<?php if($id != ''){echo 'disabled="disabled"';}?>>
													<option value="" selected="selected">Select</option>
												</select>
												<div style="color:#FF0000;display:none" id="grades_val_error"></div>
											</div></td>
									</tr>
									
									
									
									<tr>
										<td><label class="control-label Grey" for="input3">SAT
												Question:</label>
											<div class="controls">
												<input type="radio" class="satradio margineZero" id="Y"
													name="set_question"
													<?php if(isset($set_question) && $set_question == 'Y'){echo "checked='checked'";} ?>
													value="Y">Y &nbsp;&nbsp; <input type="radio"
													class="satradio margineZero" id="N" name="set_question"
													<?php if(isset($set_question) && $set_question == 'N'){echo "checked='checked'";} ?>
													value="N">N
											</div></td>
										<td><label class="control-label Grey" for="input3">Refer Book
												Chapter:</label>
											<div class="controls">
												<input type="text" class="span8 popovers"
													id="refer_book_chapter" name="refer_book_chapter"
													value="<?php if (isset($refer_book_chapter)){echo $refer_book_chapter;}?>" />
													<div style="color:#FF0000;display:none" id="refer_book_chapter_error"></div> 
											</div></td>
									</tr>
									<tr>
										<td><label class="control-label Grey" for="input3">Refer Book
												Name:</label>
											<div class="controls">
												<input type="text" class="span8 popovers"
													id="refer_book_name" name="refer_book_name"
													value="<?php if (isset($refer_book_name)){echo $refer_book_name;}?>" />
													<div style="color:#FF0000;display:none" id="refer_book_name_error"></div>
											</div></td>

									</tr>
									<tr>
										<td colspan="2"><label class="control-label Grey" for="input3">Refer
												Article URL:</label>
											<div class="controls">
												<input type="text" class="span8 popovers"
													id="refer_article_url" name="refer_article_url"
													value="<?php if (isset($refer_article_url)){echo $refer_article_url;}?>" />
													<div style="color:#FF0000;display:none" id="refer_article_url_error"></div>
											</div></td>
									</tr>
									<tr>
										<td colspan="2"><label class="control-label Grey" for="input3">Wolframalphaquery:</label>
											<div class="controls">
												<input type="text" class="span8 popovers"
													id="wolframalphaquery" name="wolframalphaquery"
													value="<?php if (isset($wolframalphaquery)){echo $wolframalphaquery;}?>" />
													<div style="color:#FF0000;display:none" id="wolframalphaquery_error"></div>
											</div></td>
									</tr>
								</table>
								<div class="form-actions">
									<input type="hidden" name="returnPageUrl" id="returnPageUrl" value="<?php echo $this->returnPage;?>">
									<button type="button" class="btn btn-primary" onclick="questionValidate('','preview');">Preview</button>
									<button type="submit" class="btn btn-primary">Save</button>
							<input type="button" class="btn"
										 onClick="returnPage('questions','<?php echo $this->returnPage; ?>');" 
										value="Cancel">
								</div>
							</form>
							<!-- END FORM-->
						</div>
					</div>
					<!-- END SAMPLE FORM PORTLET-->
				</div>
			</div>
		</div>
		<!-- END PAGE CONTENT-->
	</div>
	<!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
<script type="text/javascript">
 	$(document).ready(function(){ 
	 var category_id_hidden = $("#category_id_hidden").val();
	 if(category_id_hidden != '')
	 {
		 getgrade(category_id_hidden);
	 }	
 	});
 	var a=new EqTextArea('question_equation_image','question_equation');
	EqEditor.add(a,false);
	var src = $('#question_equation_image').attr('src');
	$('#question_equation_image1').val(src);
	var a=new EqTextArea('explanation_equation_image','explanation_equation');
	EqEditor.add(a,false);
	var src1 = $('#explanation_equation_image1').attr('src');
	$('#question_equation_image1').val(src1);
	var a=new EqTextArea('right_equation_image','right_answer_equation');
	EqEditor.add(a,false);
	var src2 = $('#right_equation_image').attr('src');
	$('#right_equation_image1').val(src2);
	var a=new EqTextArea('wrong_equation_image','wrong_answer1_equation');
	EqEditor.add(a,false);
	var src3 = $('#wrong_equation_image').attr('src');
	$('#wrong_equation_image1').val(src3);
	var a=new EqTextArea('wrong_answer2_equation_image','wrong_answer2_equation');
	EqEditor.add(a,false);
	var src4 = $('#wrong_answer2_equation_image').attr('src');
	$('#wrong_answer2_equation_image2').val(src4);
	var a=new EqTextArea('wrong_answer3_equation_image','wrong_answer3_equation');
	EqEditor.add(a,false);
	var src5 = $('#wrong_answer3_equation_image').attr('src');
	$('#wrong_answer2_equation_image3').val(src5);
        
        tinymce.remove('textarea');
</script>