<script>
  $(function() {
    $( "#fromDate" ).datepicker({
    	dateFormat: "yy-mm-dd"});
    $( "#endDate" ).datepicker({dateFormat: "yy-mm-dd"});
  });
</script>

<?php
 function seconds2humanP($ss)
	{
		$s = $ss%60;
		$m = floor(($ss%3600)/60);
		$h = floor(($ss%86400)/3600);
		$d = floor(($ss%2592000)/86400);
		$M = floor($ss/2592000);
		return "$h:$m:$s";
	}
?>
<script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php 
 if(isset($this->standard_id)) 
 {
 	$standard_ids	= $this->standard_id;
 }
?>
<?php $perPage = $this->perpage;?>
<!-- BEGIN PAGE -->

<div id="body">
  <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <div id="widget-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button">×</button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">
      <p>Here will be a configuration form</p>
    </div>
  </div>
  <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
  <!-- BEGIN PAGE CONTAINER-->
  <div class="container-fluid">
    <?php if(isset($this->success) && $this->success != ''){?>
    <div id="success" class="alert alert-success">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->success;?></div>
    <?php }?>
    <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>
    <div id="exception" class="alert alert-error">
      <button class="close" data-dismiss="alert">×</button>
      <?php echo $this->error;?> </div>
    <?php     	
        		 }
        	 ?>
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
      <div class="span12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <ul class="breadcrumb">
          <li> <i class="icon-home"></i> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span> </li>
          <li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlog', 'module' => 'admin'), null, true);?>">Question Log Manager</a> </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div id="page" class="dashboard">
      <div class="row-fluid">
        <div class="span12">
          <!-- BEGIN EXAMPLE TABLE PORTLET-->
          <div class="widget">
            <div class="widget-title">
              <h4>Question Log</h4>
            </div>
            <div class="widget-body">
              <!--<form id="searchfilter" method="post" name="searchfilter"  class="Margin_0">
                <div class="row-fluid">
                  <div class="">
                  	<div id="grade_div" class="dataTables_length">
                      <label class="filter_padding">
                      <select name="grade_level" class="gradebox" id="grade_level" size="1" aria-controls="sample_1" onchange="getSubjectList(this.value);">
                        <option value="" selected="selected">Grade</option>
                        <?php foreach ($this->grades as $grades){?>
                        <option value="<?php echo $grades['grades_id'];?>" ><?php echo $grades['grade_name'];?></option>
                        <?php }?>
                      </select>
                      </label>
                    </div>
                    <div id="framework_div" class="dataTables_length">
                      <label class="filter_padding">
                      <select name="framework" class="frameworkbox" size="1" aria-controls="sample_1" id="framework" >
                        <option value="" selected="selected">Framework</option>
                      </select>
                      </label>
                    </div>
                    <div id="framework_div" class="dataTables_length">
                      <label class="filter_padding">
                      <div class="controls">
                     	<input type="text" class="span12 popovers" name="fromDate" id="fromDate" placeholder="Start date">
                     </div>
                      </label>
                    </div>
                    <div id="grade_div" class="dataTables_length">
                      <label class="filter_padding">
                      <div class="controls">
                     <input type="text" class="span12 popovers" name="endDate" id="endDate" placeholder="End date">
                      </div>
                      </label>
                    </div>
                    <input type ="button" class="btn btn-primary" id="search_category" value="Search" onclick="getfiltersearch();">
                  </div>
                </div>
                <?php 
				    $search_val='';$search_qval="";
					if($this->frame || $this->grade || $this->fromDate || $this->endDate) {
						if($this->grade != ''){
							if($search_val != ''){
								$search_val= $search_val." | Grade : ".$this->grade->grade_name;
					 		}
					 		else{
					 			$search_val= "Grade : ".$this->grade->grade_name;
					 		}	
					 	}
						if($this->frame != ''){
					 		if($search_val != ''){
					 			$search_val= $search_val." | Framework : ".$this->frame->subject_name;
					 		}
					 		else{
					 			$search_val = "Framework : ".$this->frame->subject_name;
					 		}
						}
						if($this->fromDate != ''){
					 		if($search_val != ''){
					 			$search_val= $search_val." | From date  : ".$this->fromDate;
					 		}
					 		else{
					 			$search_val = "From date : ".$this->fromDate;
					 		}
						}
						if($this->endDate != ''){
					 		if($search_val != ''){
					 			$search_val= $search_val." | End date : ".$this->endDate;
					 		}
					 		else{
					 			$search_val = "End date : ".$this->endDate;
					 		}
						}
					}			
				
							?>
              </form>
              <?php if($search_val != '') {
				 
							?>
              <ul class="breadcrumb">
                <li> You have searched for : </li>
                <li> <?php echo $search_val;?> </li>
                <li><span class="divider">/</span> <a href="<?php echo $this->url(array('controller'=>'questions','action'=>'questionlog', 'module' => 'admin'), null, true);?>">Clear search</a> </li>
              </ul>
              <?php }?> -->
              <div class="overFlow">
              <table class="table table-striped table-bordered" id="questionlist">
                <thead>
                  <tr>
                    <th>Question</th>
                    <th>Correct Answer</th>
                    <th>No. of times question asked</th>
                    <th>% Correct answer</th>
                    <th>% Incorrect answer</th>
                    <th>% Unanswered</th>
                    <th>CAART</th>
                    <th>IAART</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
                  $i=(($this->currentPage-1)*$perPage)+1;
                  if($this->totalRecord > 0){
                      foreach ($this->questions as $q){
//                           $countAskedQuestion 			= $this->getQuestionAskedTime($q['question_id']);
//                           $countQuestionRightTime		= $this->getQuestionRightAnswerTime($q['question_id']);
//                           $countQuestionWrongTime		= $this->getQuestionWrongAnswerTime($q['question_id']);
//                           $countQuestionUnanswerdTime	= $this->getQuestionUnAnswerTime($q['question_id']);

                          // generate image for question and options
                          if(!empty($q['question_equation_images']) && $q['question_equation_images'] != null) {
                               $questionView = My_Functions::generateImages($q['question_equation_images'], $q['question_display']);
                               //$questionArray[$i]['question']						= $questionView;
                           } else {
                               $questionView = $q['question'];
                           }
                           
                           if(!empty($q['option_equation_image_name']) && $q['option_equation_image_name'] != null) {
                               $optionView = My_Functions::generateImages($q['option_equation_image_name'], $q['option_equation']);
                               //$questionArray[$i]['option']						= $optionView;
                           } else {
                               $optionView = $q['option'];
                           }
                  ?>
                  <tr class="odd gradeX">
                    <td><?php 
                    //if(!empty($q['question_equation_images'])) {
                    //    $questionView = My_Functions::generateImages($q['question_equation_images'], $q['question_display']);
                    //}
                    echo nl2br($questionView);
                    ?>&nbsp;
                    </td>
                    <td><?php echo $optionView; //$q['option'];?>&nbsp;</td>
                    <td><?php echo $q['countAskedQuestion'];?>&nbsp;</td>
                    <td><?php echo number_format(($q['countQuestionRightTime']/$q['countAskedQuestion'])*100,2);?>&nbsp;</td>
                    <td><?php echo number_format(($q['countQuestionWrongTime']/$q['countAskedQuestion'])*100,2);?>&nbsp;</td>
                    <td><?php echo number_format(($q['countQuestionUnanswerdTime']/$q['countAskedQuestion'])*100,2);?>&nbsp;</td>
                    <td><?php echo seconds2humanP($q['countcorrectResponceTime']);?>&nbsp;</td>
                    <td><?php echo seconds2humanP($q['countWrongResponceTime']);?>&nbsp;</td>
                  </tr>
                  <?php $i++;}} else {	?>
                  <tr class="odd gradeX">
                    <td class="hidden-phone" colspan="8" style="text-align: center">NO RECORD FOUND</td>
                  </tr>
                  <?php }?>
                </tbody>
              </table>
              </div>
            </div>
          </div>
          <!-- END EXAMPLE TABLE PORTLET-->
          <?php if($this->totalRecord > $perPage){?>
          <form name="searchFormSort" id="searchFormSort" action="<?php  echo $this->url(array('controller' => 'questions', 'action' => 'questionlist', 'module' => 'admin'),null,true);?>" method="post" class="RecordPerPage">
            <span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" onchange="javascript:sub_per_page('<?php echo curPageURL();?>',this.value);" class="span6" tabindex="1" id="">
              <option value="10" <?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
              <option value="20" <?php if($perPage == '20'){ echo 'selected=selected';}?>>20</option>
              <option value="30" <?php if($perPage == '30'){ echo 'selected=selected';}?>>30</option>
            </select><span class="RecordPerPageSpan">&nbsp;entries</span>
            <input type="hidden" name="search_question" class="searchdata" value="<?php  echo $search_val;?>" />
          </form>
          <?php }?>
          <?php  	// pagination start
					 	if($this->totalRecord !='')
					 	{
							if($this->totalRecord > $perPage)
							{
								echo $this->paginationControl($this->questions, 'Sliding', 'paginationquestion.phtml', array('perpage' =>$perPage));
							}
						}
						
					// pagination ends ?>
          <script language="javascript">
							function sub_per_page(url,value)
							{
								var p =url.indexOf("/perpage");
								if(p == -1)
								{
									var urlone = url;
								}
								else
								{
									var urlone = url.split('/perpage')[0];		
								}
								url = urlone+'/perpage/'+value;
								window.location= url;
							}
							</script>
        </div>
      </div>
    </div>
    <!-- END PAGE CONTENT-->
  </div>
  <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>
	
	$(document).ready(function(){
		var sorting =[0,1,2,6,7];
		applyDataTable('questionlist',sorting);
	});
	$("#questionlist_length").css('display','none');
	$("#questionlist_filter").css('display','none');
	$("#questionlist_paginate").css('display','none');
	
	</script>
<script>
	function applyDataTable(tableid,sorting)
	{
		$(document).ready(function() {
			oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
				               {
				                  bSortable: false,
				                  aTargets: sorting,
				               }
				             ]				
			});
		} );
	}
	</script>
