<?php 
	$categoryId			= $this->categoryData['category_id'];
	$category_code			= $this->categoryData['category_code'];
	$framework				= $this->categoryData['subject_name'];
	$psvCode				= $this->categoryData['psv_code'];
	$grade					= $this->grd;
	$domain			        = $this->categoryData['code'];
	$domainName		        = $this->categoryData['name'];
	$subtopicCode		    = $this->categoryData['subtopic_code'];
	$subtopicName		    = $this->categoryData['subtopic_name'];
	$headLine			    = $this->categoryData['headline'];
	$description			= $this->categoryData['description'];
	if($this->categoryData['standard_id']==1){
		//echo $subtopicCode;die;
            $removeStdForUrl = str_replace('ccss.','',$category_code);
            $subtopicOfUrl = $subtopicCode;
            $lengthSub = strlen($subtopicOfUrl);
            $n = strpos($subtopicOfUrl,'.');
            if($n != '' && !empty($n)){
                if(($n == 1 && $lengthSub == 3)  || $n == 2 && $lengthSub == 4){
                    $subtopicOfUrl = substr($subtopicOfUrl, 0, $n).'.'.  strtolower(substr($subtopicOfUrl,$n+1));
                }else{
                    $subtopicOfUrl = substr($subtopicOfUrl, 0, $n+2).strtolower(substr($subtopicOfUrl,$n+2));
                }
            }else{
                $subtopicOfUrl = substr($subtopicOfUrl, 0, 1).'.'.  strtolower(substr($subtopicOfUrl,1));
            }
            $categoryUrl = strtoupper($removeStdForUrl);
            $categoryUrl = str_replace(strtoupper($subtopicCode), $subtopicOfUrl,$categoryUrl);
            $categoryUrl = str_replace('ELA-LITERACY','ELA-Literacy',$categoryUrl);
            $categoryUrl = str_replace('MATH.CONTENT','Math.Content',$categoryUrl);
            $categoryUrl = str_replace('.','/',$categoryUrl);

            $url                    = 'http://www.corestandards.org/'.$categoryUrl;
            $lastChar = substr(trim($url), -1);
            if($lastChar != '/'){
               $url = $url.'/'; 
            }
	}else{
		$url = '-';
	}
	//$psvCode = 'PSV.'.strtoupper($this->categoryData['stnd_name']).'.'.strtoupper($this->categoryData['subject_name']).'.'.strtoupper($grade).'.'.strtoupper($this->categoryData['code']).'.'.strtoupper($this->categoryData['subtopic_code']);
	
	$breakPsvCode = explode('.',$psvCode);
        if($framework != 'ela-literacy.ccra'){
            $grade = $breakPsvCode[3];
        }else{
            $grade = $breakPsvCode[4];
        }
	$i=1;

?>

<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
    
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
					
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'questions','action'=>'categorylist', 'module' => 'admin'), null, true);?>"">Category Manager</a>
							<span class="divider">/</span>
							</li>
							<li><a href="#">Categories Details</a>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                       <div class="widget-title">
                           <h4>View Category</h4>
                          
                        </div>
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
								<table cellpadding="5px;" class="detailtable" border="1">
									<tr class="tablehead">
									<th>Level</th>
										<th>Description</th>
			                            <th>Value</th>
									</tr>
									<tr class="tablealternaterow">
									<td>L2</td>
										<td><?php if($this->categoryData['standard_id']==1){ echo 'CCSS';}else if($this->categoryData['standard_id']==2){ echo 'BAL';}?> Code Value</td>
			                            <td><?php echo strtoupper($category_code);?></td>
									</tr>
									<tr>
									<td>L3</td>
										<td>Framework</td>
										<td><?php echo ucwords($framework);?></td>
									</tr>
									
									<tr class="tablealternaterow">
									<td>L4</td>
										<td>Grade</td>
										<td><?php echo $grade;?></td>
									</tr>
									<tr>
										<td>L5</td>
										<td>Domain Initial</td>
										<td><?php echo $domain;?></td>
									</tr>
									
									<tr class="tablealternaterow">
										<td>L6</td>
										<td>Domain Name</td>
										<td><?php echo $domainName;?></td>
									</tr>
									<tr>
										<td>L7</td>
										<td>SubTopic Code</td>
										<td><?php echo strtoupper($subtopicCode);?></td>
		                            </tr>
		                            <tr class="tablealternaterow">
										<td>L8</td>
										<td>SubTopic Name</td>
										<td><?php echo $subtopicName;?></td>
									</tr>
									<tr>
										<td>L9</td>
										<td>Standard Url</td>
                                                                                <td><?php $descWithoutHtml = '';
                                    $descWithoutHtml = strip_tags($description);if(!empty($descWithoutHtml)){ ?>
                                            <a href="<?php echo $url;?>" target="_blank"><?php echo $url;?></a><?php } ?></td>
		                            </tr>
		                            <tr class="tablealternaterow">
										<td>L10</td>
										<td>HeadLine</td>
										<td> <?php echo $headLine;?> </td>
									</tr>
									<tr>
										<td>L11</td>
										<td>Description</td>
										<td> <?php echo substr($description,0,100);?> </td>
									</tr>
                                  
									  <tr class="tablealternaterow">
                                    
										<td> L12 </td>
										<td> Top Level Code PSV </td>
										<td> <?php echo strtoupper($psvCode);?> </td>
									</tr>
                                    
								
							
								</table>
								<br>
								<button type="button" class="btn" onClick="returnPage('questions','categorylist');">Go Back</button>
                           <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 
      