	<!-- BEGIN CONTAINER -->
	
		<!-- BEGIN PAGE -->
		<div id="body">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE CONTAINER-->
			<div class="container-fluid">
				 
				<div class="row-fluid">
					<div class="span12">
						<h3 class="page-title">
							Access Denied
						</h3>
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="#">Home</a> <span class="divider">/</span>
							</li>
							
						</ul>
					</div>
				</div>
				<div id="page" class="dashboard">
					<h1>You don't have permission to access that section</h1>
					</div>
			<!-- END PAGE CONTAINER-->		
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
