            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <a class="active" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'admin'), null, true); ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#">
								<i class="fa fa-bar-chart-o fa-fw"></i>
								Products<span class="fa arrow"></span>
							</a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->url(array('controller' => 'product', 'action' => 'add', 'module' => 'admin'), null, true); ?>">
									<i class="fa fa-edit fa-fw"></i>
									Add Products</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array('controller' => 'product', 'action' => 'list', 'module' => 'admin'), null, true); ?>"><i class="fa fa-table fa-fw"></i> View All Products</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

						<!-- Client menu -->
						<li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> Client<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                 <li>
                                    <a href="<?php echo $this->url(array('controller' => 'client', 'action' => 'add', 'module' => 'admin'), null, true); ?>">
									<i class="fa fa-edit fa-fw"></i>
									Add Client</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array('controller' => 'client', 'action' => 'list', 'module' => 'admin'), null, true); ?>"><i class="fa fa-table fa-fw"></i> View All Client</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

						<li>
                            <a href="#"><i class="fa fa-edit fa-fw"></i>Receipt<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
								<li>
                                    <a href="<?php echo $this->url(array('controller' => 'receipt', 'action' => 'purchase-order', 'module' => 'admin'), null, true); ?>"><i class="fa fa-edit fa-fw"></i>Create Purchase Order</a>
                                </li>
								<li>
                                    <a href="<?php echo $this->url(array('controller' => 'receipt', 'action' => 'all-purchase-order', 'module' => 'admin'), null, true); ?>"><i class="fa fa-table fa-fw"></i>Purchase Order</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'order', 'action' => 'index', 'module' => 'admin'), null, true); ?>">
								<i class="fa fa-sitemap fa-fw"></i> Orders
							</a>
                        </li>
                       <!-- <li>
                            <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Reports</a>
                        </li>-->


                      <!--  <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Stock <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Add List</a>
                                </li>
                                <li>
                                    <a href="#">View</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                       <!-- </li>-->

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>