<?php
/**
 * Admin dashboard
 * Author: Abinav Bhardwaj
 * Dated: March 23, 2016
 */
$auth = Zend_Auth::getInstance();
$data = $auth->getStorage()->read(); // Retrieve the Login User Info

if (isset($auth->getIdentity()->admin_name) && !empty($auth->getIdentity()->admin_name)) {
    $adminName = $auth->getIdentity()->admin_name;
}
// Retrieving the Login User name
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName(); // Get the Controller Name
$action = $request->getActionName(); // Get the action Name
$adminInfoSession = new Zend_Session_Namespace('adminInfo');
$adminName = $adminInfoSession->adminData['name'];

$adminImage = 'images/no-image.png';
if ($adminInfoSession->adminData['image'] != '') {
    $adminImage = AWS_S3_URL . 'admin/' .$adminInfoSession->adminData['image'];
}
?>
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');

$this->headLink()
        ->appendStylesheet($this->baseUrl() . '/assets_admin/css/bootstrap.min.css')
        ->appendStylesheet($this->baseUrl() . '/assets_admin/css/plugins/metisMenu/metisMenu.min.css')
        ->appendStylesheet($this->baseUrl() . '/assets_admin/css/plugins/timeline.css')
        ->appendStylesheet($this->baseUrl() . '/assets_admin/css/sb-admin-2.css')
        ->appendStylesheet($this->baseUrl() . '/assets_admin/css/plugins/morris.css')
        ->appendStylesheet($this->baseUrl() . '/assets_admin/font-awesome-4.1.0/css/font-awesome.min.css');


if ($controller == 'index' && $action == 'dashboard') {
    $this->headScript()->appendFile('https://www.google.com/jsapi');
    $this->headScript()->appendFile($this->baseUrl() . '/assets_admin/js/my.charts.js');
}
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link rel='shortcut icon' type='image/x-icon' href = '<?php echo HOST_NAME ?>/images/fav.ico' />

        <?php echo $this->headMeta(); ?> 
        <?php
        $actionName = str_replace(' ', '', $action);
        $controllerName = str_replace(' ', '', $controller);
        $arrayHeadTitle = array(
            'login' => ADMIN_LOGIN,
            'resetpassword' => ADMIN_RESETPASS,
            'forgotpassword' => ADMIN_FORGOTPASS,
            'changepassword' => ADMIN_CHANGEPASS,
            'dashboard' => ADMIN_DASHBOARD,
            'aboutus' => ADMIN_ABOUTUS,
            'privacypolicy' => ADMIN_PRIVACY,
            'eula' => ADMIN_EULA,
            'support' => ADMIN_SUPPORT,
            'faqlist' => ADMIN_FAQLIST,
            'faq' => '',
            'videolist' => ADMIN_VIDEOLIST,
            'updatevideo' => ADMIN_UPDATEVIDEO,
            'categorylist' => ADMIN_CATELIST,
            'viewcategorydata' => ADMIN_CATEVIEW,
            'editcategory' => ADMIN_CATEEDIT,
            'updatecategorycode' => ADMIN_CATEUPDATE,
            'addcategory' => ADMIN_CATEADD,
            'questionlist' => ADMIN_QUESLIST,
            'expiringquestionlist' => ADMIN_EXPIRINGQUESLIST,
            'expiredquestionlist' => ADMIN_EXPIREDQUESLIST,
            'draftquestionlist' => ADMIN_DREAFTQUESLIST,
            'questionlog' => ADMIN_QUESLOG,
            'questiondetail' => ADMIN_VIEWQUES,
            'list' => ADMIN_ADD_ADMINUSERSLIST,
            'edit' => ADMIN_EDITADMINUSER,
            'add' => ADMIN_ADDADMINUSER,
            'resetpassword' => ADMIN_ADMINRESETPASS,
            'index' => ADMIN_STATS_GRADEWISE,
            'statslist' => ADMIN_STATS_SUBJECTWISE,
            'personstats' => ADMIN_STATS_PERSONWISE,
            'personstatslist' => ADMIN_STATS_PERSONANDWEEKWISE,
            'parentlist' => ADMIN_PARENTLIST,
            'childlist' => ADMIN_CHILDLIST_PARENTWISE
        );
        if ($controller != 'lclock' && $controller != 'lcquestion') {
            foreach ($arrayHeadTitle as $key => $value) {
                if ($key == $actionName) {
                    $this->headTitle('Admin');
                    $this->headTitle($value);
                }
            }
        } else {
            $this->headTitle('');
        }
        echo $this->headTitle();
        ?> 

        <script type="text/javascript">
            var base_url = '<?php echo $this->baseUrl(); ?>';
            var SITE_URL = '<?php echo HOST_NAME; ?>';
        </script>

        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>

        
    </head>

    <!-- END HEAD -->
    <!-- BEGIN BODY -->
   
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><img src="ashita_logo.png"></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->