<!-- BEGIN PAGE -->
<div id="body">
  <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
 	<div id="widget-config" class="modal hide">
    	<div class="modal-header">
      		<button data-dismiss="modal" class="close" type="button">×</button>
      		<h3>Widget Settings</h3>
    	</div>
    	<div class="modal-body">
      		<p>Here will be a configuration form</p>
    	</div>
  	</div>
	<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<!-- BEGIN PAGE CONTAINER-->
  	<div class="container-fluid" id = "messageDiv">
    	<div id="success" class="alert alert-success displayNone"></div>
    	<div id="exception" class="alert alert-error displayNone"></div>
    	<!-- BEGIN PAGE HEADER-->
    	<div class="row-fluid">
      		<div class="span12">
        		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
        		<ul class="breadcrumb">
          			<li> <i class="icon-home"></i> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span> </li>
          			<li><a href="<?php echo $this->url(array('controller'=>'parentmanager','action'=>'parentlist', 'module' => 'admin'), null, true);?>">Parent Manager</a> <span class="divider">/</span> </li>
          			<li><a  href="#">Child List</a></li>
        		</ul>
        		<!-- END PAGE TITLE & BREADCRUMB-->
      		</div>
    	</div>
    	<!-- END PAGE HEADER-->
    	<!-- BEGIN PAGE CONTENT-->
    	<div id="page" class="dashboard">
      		<div class="row-fluid">
        		<div class="span12">
          		<!-- BEGIN EXAMPLE TABLE PORTLET-->
          		<div class="widget">
            		<div class="widget-title">
             			<h4>Child List</h4>
             			<div class="FloatRight BackLink">
             			<form action="<?php echo $this->url(array('controller'=>'parentmanager','action'=>'parentlist', 'module' => 'admin'), null, true);?>" method="post">
                                    <input type="submit" class="btn btn-primary" value="Back to Parent Listing" >
             			</form>
             			</div>
            		</div>
            		<div class="widget-body">
            		<div class="Outer">
              <table cellpadding="8" width="100%" cellspacing="0" border="0">
              <?php foreach ($this->childInfo as $childInfo){
              	/* echo "<pre>";
              	print_r($childInfo); */
                  $image = $this->baseUrl('images/no-image-child.png');
                				if(!empty($childInfo['image'])) {
                					$image = AWS_S3_URL . 'child/'. $childInfo['image'];
                				}  
                				?>
                				 <tr>
                	<td align="left" valign="top"><div class="Units">
                  <div class="InfoBox">
                  <div class="BlockLeft"> <a href="#"><img
					src="<?php echo $image; ?>"
					class="UserImg" id="childMaimImage" alt="photo" height="70"
					width="70"></a>
                    <div class="Block-1 paddingTop">
                      <div class="InfoBoxBtm">
                        <table width="100%" border="0" cellspacing="0" cellpadding="7">
                          <tr>
                            <td align="left" width="20%" valign="middle" class="Color"><strong>Name:</strong></td>
                            <td align="left" width="80%" valign="middle"><?php echo $childInfo['name'];?></td>
                          </tr>
                          <tr>
                            <td align="left" valign="middle" class="Color"><strong>Grade:</strong></td>
                            <td align="left" valign="middle"><?php echo $childInfo['grade_name'];?></td>
                          </tr>
                          <tr>
                              <td align="left" valign="middle" class="Color"><strong># of System Questions:</strong></td>
                              <td align="left" valign="middle"><?php echo $childInfo['totalquestion']; ?></td>
                          </tr>                          
                          <tr>
                              <td align="left" valign="middle" class="Color"><strong># of Quiz Questions:</strong></td>
                              <td align="left" valign="middle"><?php echo $childInfo['totalquizquestion']; ?></td>
                          </tr>
                          <tr>
                              <td align="left" valign="middle" class="Color"><strong>COPPA Consent:</strong></td>
                              <td align="left" valign="middle"><?php echo $childInfo['coppa_accepted'] ? 'Accepted' : 'Pending'; ?></td>
                          </tr>
                                                            
                        </table>
                      </div>
                    </div>
                    </div>
                    <div class="InfoBoxBtm" id="deviceInfoList"
					style="margin-bottom: 0px;">
                      <h2 class="Tittle">Device List</h2>
                      <table width="100%" border="0" cellspacing="0" cellpadding="2">
                      <?php 
                      if (!empty($childInfo['phoneArray'])) {
                						foreach ($childInfo['phoneArray'] as $phoneArray)
                						{
                							if($phoneArray['lock_status'] == 0) {
                								$lockImage 	= "unlock.png";
			                				} else if($phoneArray['lock_status'] == 1){
			                					$lockImage 	= "lock.png";
			                				}?>
                        <tr>
                          <td class="Colored"><?php echo $phoneArray['phone_number'];?></td>
                          <td width="10%" align="left" valign="middle" >
                          	<?php if($phoneArray['lock_status'] == 1){?>
                          	<a  id = "lockUnlockButton_<?php echo $phoneArray['child_device_id']; ?>" href="javascript:void(0)" onclick="unlockdevice('<?php echo $phoneArray['child_device_id']; ?>','<?php echo $phoneArray['notification_id']; ?>','<?php echo $childInfo['child_id'];?>')" title="Unlock Device"><?php }?>
                          	<img src="<?php echo $this->baseUrl().'/assets_admin/images/'.$lockImage;?>" height="20" width="20">
                          	<?php if($phoneArray['lock_status'] == 1){?></a><?php }?></td>
                          
                  
                        </tr>
              			<?php }
                                } else {
                                    echo "No devices assigned";
                                }
                                ?>
                      </table>
                    </div>
                  </div>
                </div></td>
                   </tr>
              	
                	<?php } ?>
                      </table>
                    </div>
            		
              			
          		</div>
          		<!-- END EXAMPLE TABLE PORTLET-->
        	</div>
      	</div>
    </div>
    <!-- END PAGE CONTENT-->
  </div>
  <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->