<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
        <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'parentmanager','action'=>'parentlist', 'module' => 'admin'), null, true);?>">Parent List</a>
							<span class="divider">/</span>
							<li><a href="#">Delete Parent</a>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form name="parentDelete" id="parentDelete" action="<?php echo $this->url(array('controller' =>'parentmanager', 'action' =>'deleteparent', 'module' =>'admin'), null, true);?>" method="post" class="form-horizontal">
                              <div class="control-group">
                                 <label class="control-label Grey" for="inputRemarks"><span class="error">*</span>Parent Email(s):</label>
                                 <div class="controls width585">
                                     <textarea class="span6" maxlength="5000" rows="3" id="parentEmail" name="parentEmail" style="width:700px;height: 200px;" placeholder="Use comma to separate each email. Maximum 100 emails are allowed."><?php echo (empty($this->parentEmail)) ? '' : $this->parentEmail;?></textarea>
                                 <div style="color:#FF0000;display:none" id="parentEmailError"></div>
                                 </div>
                              </div>
                              <div class="control-group">
                                 <label class="control-label Grey" for="inputRemarks"><span class="error">*</span>Password:</label>
                                 <div class="controls width585">
                                     <input type="password" class="span6 popovers" id="password" name="password" />
                                 <div style="color:#FF0000;display:none" id="passwordError"></div>
                                 </div>
                              </div>
                              <div class="form-actions">
                                 <button type="submit" class="btn btn-primary" onclick="return validateDeleteParent();">Submit</button>
								  <button type="button" class="btn" onClick="returnPage('parentmanager','parentlist');">Cancel</button>
                              </div>
                           </form>
                           <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->