 <!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
<?php if(isset($this->success) && $this->success != ''){ ?>
	<script language="javascript">
		/* window.setInterval(function() {
  			parent.$.fn.colorbox.close();
		}, 2000); */
	</script>
<?php ?>
    <div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
<?php }?>
<?php if(isset($this->error) && $this->error != ''){ ?>		 
	<div id="exception" class="alert alert-error">
    	<button class="close" data-dismiss="alert">×</button>
         <?php echo $this->error;?>
    </div>
<?php } ?>
<div id="page">
	<div class="row-fluid">
    	<div class="span12">
       		<!-- BEGIN SAMPLE FORM PORTLET-->
       		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<ul class="breadcrumb">
					<li><i class="icon-home"></i> <a
						href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a>
						<span class="divider">/</span>
					</li>
					<li><a
						href="<?php echo $this->url(array('controller'=>'parentmanager','action'=>'parentlist', 'module' => 'admin'), null, true);?>">parent
							Manager</a> <span class="divider">/</span>
					</li>
					<li><a class='iframe'
						href="javascript:void(0)">Reset Password
					</a></li>
				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->	
            <div class="widget">
            	<div class="widget-title">
                	<h4><i class="icon-reorder"></i>Reset Password</h4>
                </div>
				<div class="widget-body form">
                	<!-- BEGIN FORM-->
                    <form name="resetpass" id="resetpass" action="<?php array('controller' =>'parentmanager', 'action' =>'resetpassword', 'module' =>'admin');?>" method="post" class="form-horizontal" onsubmit="return ValidateResetPass();" >
                        <div class="control-group">
                   	  		<label class="control-label Grey" for="input3"><span class="error">*</span>Password:</label>
                   	   			<div class="controls">
                   	   				<input type="password"  class="span3 popovers" id="passWord" name="passWord" data-trigger="hover" maxlength="16"/>
                                 	<div style="display:none" class="error" id="newPasswordError"></div>
                                 	<input type="hidden" name="userId" id="userId" value="<?php echo $this->userId;?>">
                                 </div>
                             </div>
				  			 <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>Confirm password:</label>
                                 <div class="controls">
                                 
					   				<input type="password" class="span3 popovers" id="confirmPassword" name="confirmPassword" data-trigger="hover" maxlength="16"/>
					   				<div style="display:none" class="error" id="confirmPasswordError" ></div>
                               	</div>
                               	</div>
                      	<div class="form-actions">
                        <input type ="submit" class="btn btn-primary" id="reset" value="Reset Password" >
                       <input type="button" class="btn"
										 onClick="returnPage('parentmanager','parentlist');" 
										value="Cancel">
                     	<div id="display_categoryfileds" ></div> 
                     	</div>           
                    </form>
                <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 