<script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php $perPage = $this->perpage;?>
<!-- BEGIN PAGE -->

<div id="body">
  <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
 	<div id="widget-config" class="modal hide">
    	<div class="modal-header">
      		<button data-dismiss="modal" class="close" type="button">×</button>
      		<h3>Widget Settings</h3>
    	</div>
    	<div class="modal-body">
      		<p>Here will be a configuration form</p>
    	</div>
  	</div>
	<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<!-- BEGIN PAGE CONTAINER-->
  	<div class="container-fluid">
    	<?php if(isset($this->success) && $this->success != ''){?>
    	<div id="success" class="alert alert-success">
      		<button class="close" data-dismiss="alert">×</button>
      		<?php echo $this->success;?>
      	</div>
    	<?php }?>
    	<?php if(isset($this->error) && $this->error != ''){?>
    	<div id="exception" class="alert alert-error">
      		<button class="close" data-dismiss="alert">×</button>
      		<?php echo $this->error;?> 
      	</div>
    	<?php } ?>
    	<!-- BEGIN PAGE HEADER-->
    	<div class="row-fluid">
      		<div class="span12">
        		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
        		<ul class="breadcrumb">
          			<li> <i class="icon-home"></i> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span> </li>
          			<li><a href="#">Virtual Children</a>  </li>
        		</ul>
        		<!-- END PAGE TITLE & BREADCRUMB-->
      		</div>
    	</div>
    	<!-- END PAGE HEADER-->
    	<!-- BEGIN PAGE CONTENT-->
    	<div id="page" class="dashboard">
      		<div class="row-fluid">
        		<div class="span12">
          		<!-- BEGIN EXAMPLE TABLE PORTLET-->
          		<div class="widget">
            		<div class="widget-title">
             			<h4>Virtual Children</h4>
            		</div>
            		<div class="widget-body">
              			<form id="searchfilter" class="Margin_0" method="post" name="searchfilter" action="<?php array('controller' =>'parentmanager', 'action' =>'virtualchildren', 'module' =>'admin');?>">
                			<div class="row-fluid">
                  				<div class="control-group Left">
                    				<input type="text"  class="span7 popovers" id="search" placeholder="Search Keyword" name="search" value="<?php  echo $this->search;?>"/>
                    				<input type ="button" class="btn btn-primary serach_Button"  value="Search" onclick="getfilteredvirtualchildsearch();">
                  				</div>
                			</div>
              			</form>
              			
              			<div class="overFlow">
              			<?php if($this->search != ''){?>
             	 		<ul class="breadcrumb">
                			<li> You have searched for : </li>
                			<li> <?php echo $this->search;?> </li>
               				<li><span class="divider">/</span> <a href="<?php echo $this->url(array('controller'=>'parentmanager','action'=>'virtualchildren', 'module' => 'admin'), null, true);?>">Clear search</a> </li>
              			</ul>
              			<?php }?>
              				<table class="table table-striped table-bordered" id="virtualchildrenlist" width="100%" >
                				<thead>
				                  	<tr>
					                    <th class="hidden-phone fontsize15" width="25%">Name</th>
					                    <th class="hidden-phone fontsize15" width="10%">Grade</th>
					                    <th class="hidden-phone fontsize15" width="20%"># of System Questions</th>
					                    <th class="hidden-phone fontsize15" width="20%"># of Quiz Questions</th>
                                                            <th class="hidden-phone fontsize15" width="15%">Created Date </th>
                                                            <th class="hidden-phone fontsize15" width="10%">Status</th>
				                  	</tr>
                				</thead>
                				<tbody>
                  				<?php
                                                
                                                //echo "<pre>"; print_r($this->childInfo); exit;
                                                
                                                if($this->totalRecord > 0){ 
                                                    foreach($this->childInfo as $pData){
                  					$name = trim($pData['name']);
                  					$grade = trim($pData['grade_name']);
                  					?>
                  					<tr>
					                    <td class="hidden-phone center fontsize15"><?php if(!empty($name)){echo $name;}else{echo '-';}?></td>
                                                            <td class="hidden-phone center fontsize15"><?php if(!empty($grade)){echo $grade;}else{echo '-';}?></td>
                                                            <td class="hidden-phone center fontsize15"><?php echo $pData['totalquestion']; ?></td>
                                                            <td class="hidden-phone center fontsize15"><?php echo $pData['totalquizquestion']; ?></td>
                                                            <td class="hidden-phone center fontsize15"><?php echo date("M d, Y H:i:s", strtotime($pData['created'])); ?> (PST)</td>
                                                            <td class="hidden-phone center fontsize15"><?php echo $pData['status']; ?></td>
					                     
                  					</tr>
                  					<?php } }else{	?>
                  					<tr class="odd gradeX">
                    					<td class="hidden-phone" colspan="8" style="text-align: center">NO RECORD FOUND</td>
                  					</tr>
                  					<?php }?>
                				</tbody>
              				</table>
                                    
                                    
              			</div>
            		</div>
          		</div>
          		<?php if($this->totalRecord > $perPage){
                            
                             ?>
          		<form name="searchFormSort" id="searchFormSort" action="<?php  echo $this->url(array('controller' => 'parentmanager', 'action' => 'virtualchildren', 'module' => 'admin'),null,true);?>" method="post" class="RecordPerPage">
            		<span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" class="span6" onchange="javascript:sub_per_page('<?php echo curPageURL();?>',this.value);" tabindex="1" id="">
                                <option value="10" <?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
                                <option value="25" <?php if($perPage == '25'){ echo 'selected=selected';}?>>25</option>
                                <option value="50" <?php if($perPage == '50'){ echo 'selected=selected';}?>>50</option>
                                <option value="100" <?php if($perPage == '100'){ echo 'selected=selected';}?>>100</option>
                                <option value="250" <?php if($perPage == '250'){ echo 'selected=selected';}?>>250</option>
                                <option value="500" <?php if($perPage == '500'){ echo 'selected=selected';}?>>500</option>
            		</select><span class="RecordPerPageSpan">&nbsp;entries</span>
            		<input type="hidden" name="search" class="search" value="<?php  echo $this->search;?>" />
          		</form>
          		<?php }?>
          		<?php  
					// pagination start
					 if($this->totalRecord> 0){
						if($this->totalRecord > $perPage){
							echo $this->paginationControl($this->childInfo, 'Sliding', 'paginationquestion.phtml',array('search' => $this->search,'perpage' =>$perPage));
						}else{
						}
					}
					// pagination ends ?>
          		<!-- END EXAMPLE TABLE PORTLET-->
                        
                        
                        
                        
                        
        	</div>
      	</div>
    </div>
    <!-- END PAGE CONTENT-->
  </div>
  <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->

<link
	rel="stylesheet"
	href="<?php echo $this->baseUrl();?>/assets_admin/css/colorbox.css" />
<script
	src="<?php echo $this->baseUrl();?>/assets_admin/js/jquery.colorbox.js"></script>
<script>
			$(document).ready(function(){
				//Examples of how to assign the Colorbox event to elements
				
				//$(".iframe").colorbox({iframe:true, width:"70%", height:"90%"});
				//$(".iframe").colorbox({iframe:true, width:"50%", height:"50%",onClosed:function(){ location.href='<?php $_SERVER["REQUEST_URI"];?>'  }});
				
			});
		</script>
<script>
	$(document).ready(function(){
		var sorting = '_all';
		applyDataTable('virtualchildrenlist',sorting);
	});
	$("#virtualchildrenlist_length").css('display','none');
	$("#virtualchildrenlist_filter").css('display','none');
	$("#virtualchildrenlist_paginate").css('display','none');
	
	</script>
<script>
	function applyDataTable(tableid,sorting)
	{
		$(document).ready(function() {
			oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
                                    {
                                        bSortable: false,
                                        aTargets: sorting,
                                    }
                                ]
			});
		});
	}
	
	
	</script>
<script language="javascript">
	function sub_per_page(url,value)
	{
		var p =url.indexOf("/perpage");
		if(p == -1)
		{
			var urlone = url;
		}
		else
		{
			var urlone = url.split('/perpage')[0];		
		}
		url = urlone+'/perpage/'+value;
		window.location= url;
	}
</script>
