   <!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
           <?php if(isset($this->success) && $this->success != ''){
		 ?>
		 <?php
		 ?>
		 
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
<div id="page">
               <div class="row-fluid">
                  <div class="span12">
                  	<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<ul class="breadcrumb">
					<li><i class="icon-home"></i> <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                                            <span class="divider">/</span>
                                        </li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'trophies', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">Trophy Manager</a> 
                                            <span class="divider">/</span>
                                        </li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">Trophy (Subject)</a> 
                                            <span class="divider">/</span>
                                        </li>
					<li><a class='iframe'
						href="javascript:void(0)">Add
					</a></li>
				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
                  
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                         <div class="widget-title">
                           <h4><i class="icon-reorder"></i>Add Trophy</h4>
                        
                        </div>
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form name="cms" id="cms" action="<?php array('controller' =>'trophiessub', 'action' =>'addtrophy', 'module' =>'admin');?>" method="post" class="form-horizontal" onsubmit="return validateTrophy()" enctype="multipart/form-data">
                              
                              <table width="90%" class="" cellspacing="8" cellpadding="8">
                   			     <tr>
                   				   <td width="15%"><label class="control-label Grey" for="input3"><span class="error">*</span>Subject:</label></td>
                   				   <td width="85%" colspan="3">
                   				   	<select name="subject_id" id="subject_id">
									<?php foreach($this->sub_std as $val){ ?>
									<option value="<?php echo $val['subject_id'] ?>" <?php if($val['subject_id']==$this->subject_id){ ?> selected="selected" <?php }?> ><?php echo $val['subject_name'] ?>-<?php echo $val['name'] ?></option>
									<?php } ?>
									</select>		
											
                                 			
                                 	</td>
                              </tr>
                              <tr>
                   				   <td width="15%"><label class="control-label Grey" for="input3"><span class="error">*</span>Grade:</label></td>
                   				   <td width="85%" colspan="3">
                                                        <select name="grade_id" id="grade_id">
									<?php for($grade_id = 1; $grade_id <= 12; $grade_id++){ ?>
                                                                        <option value="<?php echo $grade_id; ?>" <?php if($this->grade_id==$grade_id){ ?> selected="selected"  <?php }?>><?php echo $grade_id ?></option>
									<?php } ?>
									</select>
                                 			
                                 	</td>
                              </tr>
								
								
                   				  <tr>
                   				   <td width="15%"><label class="control-label Grey" for="input3"><span class="error">*</span>Title:</label></td>
                   				   <td width="85%" colspan="3">
                   				   			<input type="text"  class="span6 popovers" id="title" name="title" data-trigger="hover" value="<?php  echo htmlentities($this->title); ?>" maxlength="150"  />
                                 			<div style="color:#FF0000;display:none" id="title_error" ></div>
                                 	</td>
                              </tr>
							  
							  <tr>
                   				   <td width="15%"><label class="control-label Grey" for="input3"><span class="error">*</span>Description:</label></td>
                   				   <td width="85%" colspan="3">
								   <textarea class="span6" rows="3"  name="description" id="description" maxlength="500"><?php  echo htmlentities($this->description); ?></textarea>
                   				   			<div style="color:#FF0000;display:none" id="des"></div>
                                 			
                                 	</td>
                              </tr>
							  
							  <tr>
                   				   <td width="15%"><label class="control-label Grey" for="input3"><span class="error">*</span>Coins:</label></td>
                   				   <td width="85%" colspan="3">
                   				   			<input type="text"  class="span6 popovers" id="points" name="points" data-trigger="hover"  value="<?php  echo $this->points; ?>" maxlength="10" />
                                 			<div style="color:#FF0000;display:none" id="points_error" ></div>
                                 	</td>
                              </tr>
							  
							  <tr>
               				    <td width="14%"><label class="control-label Grey" for="input3"><span class="error">*</span>Upload Image:</label><br /> </td>
                   				   <td colspan="2">
								    <img src="<?php echo $this->baseUrl();?>/assets_admin/images/loading.gif" id="load" style="display:none;">
                   				   			<div class="UsrBrowseImg"> 
							   <input type="file" name="images" id="images" title="Add Image" class="Browse4"> 
     <div style="color:#FF0000;display:none" id="image_error" ></div>
    </div>
                                 			
                               	</td>
									<td width="68%"> <div href="#" id="imageblock">
	  <?php if($this->image!=''){?>
	  <img id="image-item" src="<?php echo $this->baseUrl();?>/images/trophy/<?php echo $this->image;?>" class="UserImgBig" height="100px" width="100px" alt="photo">
	 <?php } else {?>
     <img id="image-item" src="<?php echo $this->baseUrl();?>/images/no-trophy.jpg" class="UserImgBig"  alt="photo"  height="100px" width="100px">
	 <?php }?>
	   
     			   </div> <br />
     			   <span class="error">*</span> PNG / BMP / JPEG / JPG / TIFF / GIF</td>
                              </tr>
							  
                              </table>
							 
							  <div class="form-actions">
							   <input type="hidden" name="controller_pathImage" id="controller_pathImage" value="admin/trophiessub/uploadimage" >
							   <input type="hidden" name="image_file_name" id="image_file_name" value="<?php echo $this->image; ?>"><br />
                              <input type ="submit" class="btn btn-primary" id="checkcategorybutton" value="Add" >
                             <input type="hidden" name="SITE_URL" id="SITE_URL" value="<?php echo $this->baseUrl();?>" >
                                 
									<input type="button" class="btn"
										 onClick="returnPage('trophiessub','trophylist');" 
										value="Cancel">
                     <div id="display_categoryfileds" >          
                               

                  </div>            
                           </div>  
                           </form>
                          <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->
<script src="<?php echo $this->baseUrl();?>/assets_admin/js/upload.js"></script>
<script language="javascript">

$('#points').keyup(function () { 
    this.value = this.value.replace(/[^0-9\.]/g,'');
});

</script>