<script src="<?php echo $this->baseUrl(); ?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php
$perPage = $this->perpage;
?>
<!-- BEGIN PAGE -->

<div id="body">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="widget-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            <h3>Trophy Manager</h3>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
<?php if (isset($this->success) && $this->success != '') { ?>
            <div id="success" class="alert alert-success">
                <button class="close" data-dismiss="alert">×</button>
            <?php echo $this->success; ?></div>
        <?php } ?>
        <?php
        if (isset($this->error) && $this->error != '') {
            ?>
            <div id="exception" class="alert alert-error">
                <button class="close" data-dismiss="alert">×</button>
            <?php echo $this->error; ?> </div>
            <?php
        }
        ?>
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->

                <ul class="breadcrumb">
                    <li><i class="icon-home"></i> <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                        <span class="divider">/</span>
                    </li>
                    <li><a href="<?php echo $this->url(array('controller' => 'trophies', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">Trophy Manager</a> 
                        <span class="divider">/</span>
                    </li>
                    <li><a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">Trophy (Subject)</a> 
                        <span class="divider">/</span>
                    </li>
                    <li><a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">List</a> 
                    </li>
                    <li style="float:right"><a class='iframe' href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'addtrophy', 'module' => 'admin'), null, true); ?>"><img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/add_trophy.png" /></a></li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
            <!--<a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'addtrophy', 'module' => 'admin'), null, true); ?>">ADD</a>-->
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div id="page" class="dashboard">
            <div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="widget">
                        <div class="widget-title TabsTop">
                            <ul>
                                <li><a
                                        href="<?php echo $this->url(array('controller' => 'trophies', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>"
                                        class="active">Point Wise</a></li>
                                <li><a
                                href="<?php echo $this->url(array('controller' => 'streak', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>"
                                >Streak Wise</a></li>
                            </ul>
                        </div>
                        <div class="widget-title TabsTop">
                            <ul>
                                <li><a href="<?php echo $this->url(array('controller' => 'trophies', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">Overall Trophy</a></li>
                                <li><a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>" class="active">Subject Trophy</a></li>
                            </ul>
                        </div>
                        <div class="widget-body">
                            <form id="searchfilter" class="Margin_0" method="post" name="searchfilter" action="<?php array('controller' => 'trophiessub', 'action' => 'trophylist', 'module' => 'admin'); ?>">
                                <div class="row-fluid">
                                    <div class=""> </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="control-group Left" style="width: 460px;">
                                        <input type="text"  class="span7 popovers" id="seachdata" placeholder="Search Keyword" name="seachdata" value="<?php echo $this->searchdata; ?>"/>
                                        <select name="gradesearch" style="width: 105px;height: 34px;" class="span7 popovers">
                                            <option value="">All Grades</option>
                                            <?php for ($counter = 1; $counter <= 12; $counter++): ?>
                                                <option value="<?php echo $counter; ?>" <?php echo $this->gradesearchdata == $counter ? 'selected="selected"' : ''; ?>><?php echo $counter; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                        <input type ="submit" class="btn btn-primary serach_Button"  value="Search">
                                    </div>
                                </div>
                            </form>
<?php if ($this->searchdata != '' || $this->gradesearchdata != '') { ?>
                                <ul class="breadcrumb">
                                    <?php if($this->searchdata != ''): ?>
                                    <li> You have searched for : </li>
                                    <li> <?php echo $this->searchdata; ?> </li>
                                    <?php endif; ?>
                                    <?php if ($this->searchdata != '' && $this->gradesearchdata != '') echo '<li>|</li>' ?>
                                    <?php if($this->gradesearchdata != ''): ?>
                                    <li> Grade : </li>
                                    <li> <?php echo $this->gradesearchdata; ?> </li>
                                    <?php endif; ?>
                                    <li><span class="divider">/</span> <a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'trophylist', 'module' => 'admin'), null, true); ?>">Clear search</a> </li>
                                </ul>
<?php } ?>
                            <table class="table table-striped table-bordered" id="trophylist">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Subject</th>
                                        <th class="hidden-phone">Grade</th>
                                        <th class="hidden-phone">Title</th>
                                        <th class="hidden-phone">Coins</th>
                                        <th class="hidden-phone" style="width: 300px;">Description</th>
                                        <th class="hidden-phone">Image</th>
                                        <th class="hidden-phone">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    if ($this->totalRecord > 0) {
                                        $i = (($this->currentPage - 1) * $perPage) + 1;
                                        foreach ($this->trophyData as $caq) {
                                            ?>
                                            <tr class="odd gradeX">
                                                <td class="hidden-phone"><?php echo $i; ?>&nbsp; </td>
                                                <td class="hidden-phone"><?php echo $this->sub_std[$caq['subject_id']]; ?>&nbsp;</td>
                                                <td class="hidden-phone"><?php echo $caq['grade_id']; ?>&nbsp;</td>
                                                <td class="hidden-phone"><?php
                                    echo nl2br(htmlentities($caq['title']));
                                    ?>
                                                    &nbsp;</td>
                                                <td class="hidden-phone"><?php echo number_format($caq['points']); ?>
                                                </td>
                                                <td class="hidden-phone center"><?php
                                            echo (nl2br(htmlentities($caq['description'])) );
                                            ?>
                                                    &nbsp;</td>
                                                <td class="hidden-phone center"><?php
                                                if ($caq['image'] != '')
                                                    $image = AWS_S3_URL . 'trophy/' . $caq['image'];
                                                else
                                                    $image = $this->baseUrl('images/no-trophy.jpg');
                                                ?> <img
                                                            src="<?php echo $image; ?>"
                                                            border="0" style="width: 100px; height: 100px;" />&nbsp;</td>
                                                <td class="hidden-phone center">&nbsp; <a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'viewtrophydata', 'module' => 'admin', 'id' => $caq['subject_trophy_id']), null, true); ?>" class='iframe'><img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/preview.png" alt="View Detail" title="View this trophy" border="0" /></a> <a href="<?php echo $this->url(array('controller' => 'trophiessub', 'action' => 'edittrophy', 'module' => 'admin', 'id' => $caq['subject_trophy_id']), null, true); ?>" class='iframe'><img border="0" title="Edit this trophy" alt="Edit" src="<?php echo $this->baseUrl(); ?>/assets_admin/images/edit_icon.png"></a> <a href="javascript:void(0);"><img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/del.png" alt="Delete" title="Delete this trophy" border="0" onClick="deleteData(<?php echo $caq['subject_trophy_id']; ?>, 'trophiessub', 'deletetrophy')"/></a> </td>
                                            </tr>
                                                    <?php $i++;
                                                }
                                            }else {
                                                ?>
                                        <tr class="odd gradeX">
                                            <td class="hidden-phone" colspan="6" style="text-align: center">NO RECORD FOUND</td>
                                        </tr>
<?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
<?php if ($this->totalRecord > $perPage) { ?>
                        <form name="searchFormSort" id="searchFormSort" action="<?php  echo $this->url(array('controller' => 'questions', 'action' => 'questionlist', 'module' => 'admin'),null,true);?>" method="post" class="RecordPerPage">
                        <span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" onchange="javascript:sub_per_page('<?php echo curPageURL();?>',this.value);" class="span6" tabindex="1" id="">
                          <option value="10" <?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
                          <option value="25" <?php if($perPage == '25'){ echo 'selected=selected';}?>>25</option>
                          <option value="50" <?php if($perPage == '50'){ echo 'selected=selected';}?>>50</option>
                          <option value="100" <?php if($perPage == '100'){ echo 'selected=selected';}?>>100</option>
                          <option value="250" <?php if($perPage == '250'){ echo 'selected=selected';}?>>250</option>
                          <option value="500" <?php if($perPage == '500'){ echo 'selected=selected';}?>>500</option>
                        </select><span class="RecordPerPageSpan">&nbsp;entries</span>
                        <input type="hidden" name="search_question" class="searchdata" value="<?php  echo $search_val;?>" />
                      </form>
                    <?php } ?>
                    <?php
                    // pagination start
                    if ($this->totalRecord > 0) {
                        if ($this->totalRecord > $perPage) {
                            echo $this->paginationControl($this->trophyData, 'Sliding', 'paginationquestion.phtml', array('seachdata' => $this->searchdata, 'perpage' => $perPage));
                        } else {
                            
                        }
                    }
                    // pagination ends 
                    ?>
                    <script language="javascript">
                        function sub_per_page(url,value)
                        {
                                var p =url.indexOf("/perpage");
                                if(p == -1)
                                {
                                        var urlone = url;
                                }
                                else
                                {
                                        var urlone = url.split('/perpage')[0];		
                                }
                                url = urlone+'/perpage/'+value;
                                window.location= url;
                        }
                    </script>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<!--  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets_admin/css/colorbox.css" />
<script src="<?php echo $this->baseUrl(); ?>/assets_admin/js/jquery.colorbox.js"></script>
<script>
                        $(document).ready(function(){
                                //Examples of how to assign the Colorbox event to elements
                                
                                //$(".iframe").colorbox({iframe:true, width:"70%", height:"90%"});
                                $(".iframe").colorbox({iframe:true, width:"70%", height:"88%",onClosed:function(){ location.href='<?php $_SERVER["REQUEST_URI"]; ?>'  }});
                                
                        });
                </script>-->
<?php if ($this->totalRecord > 0) { ?>
    <script>
        $(document).ready(function() {
            var sorting = [0,5,6,7];
            applyDataTable('trophylist', sorting);




        });
        $("#trophylist_length").css('display', 'none');
        $("#trophylist_filter").css('display', 'none');
        $("#trophylist_paginate").css('display', 'none');

    </script>
    <script>
        function applyDataTable(tableid, sorting)
        {
            $(document).ready(function() {
                oTable = $('#' + tableid).dataTable({
                    "bPaginate": false,
                    "bFilter": false,
                    "bInfo": false,
                    "aaSorting": [],
                    "aoColumns": [
                        {"sWidth": "5%"},
                        {"sWidth": "15%"},
                        {"sWidth": "5%"},
                        {"sWidth": "15%"},
                        {"sWidth": "10%"},
                        {"sWidth": "27%"},
                        {"sWidth": "13%"},
                        {"sWidth": "10%"}
                    ],
                    aoColumnDefs: [
                        {
                            bSortable: false,
                            aTargets: sorting,
                        }
                    ]


                });
            });
        }


    </script>
<?php } ?>
