<?php 
	$faqData  = $this->faqData; 
	$adminInfoSession = new Zend_Session_Namespace ( 'adminInfo' );
	if (!empty($faqData) || $faqData != null) {
		$faqId = $faqData->id;
		$faqQuestion = $faqData->question;
		$faqAnswer = $faqData->answer;
		$faqSortOrder = $faqData->sort_order;
	}
	if(!empty($adminInfoSession->faqData) && $adminInfoSession->faqData != null){
		$data = $adminInfoSession->faqData;
		unset ( $adminInfoSession->faqData );
		$faqId = $data['faqId'];
		$faqQuestion = $data['quesTion'];
		$faqAnswer = $data['ansWer'];
		$faqSortOrder = $data['sortOrder'];
	}

?>
<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
        <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'cms','action'=>'faqlist', 'module' => 'admin'), null, true);?>">FAQ List</a>
							<span class="divider">/</span>
							<li><a href="#"><?php if (!empty($faqData) && $faqData != null){echo "Edit";}else{echo "Add";}?> FAQ</a>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form name="cms" id="cms" action="<?php echo $this->url(array('controller' =>'cms', 'action' =>'faq', 'module' =>'admin'), null, true);?>" method="post" class="form-horizontal">
                              <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>Sort Order:</label>
                                 <div class="controls">
                                    <input type="text" class="span6 popovers" id="sortOrder" name="sortOrder" maxlength="2"   value="<?php if(!empty($faqSortOrder)){echo $faqSortOrder;}?>" />
                                 	<div style="color:#FF0000;display:none" id="sortOrderError"></div>
                                 	<input type="hidden"  name="faqId" id="faqId"  value="<?php if(!empty($faqId)){echo $faqId;}?>" />
                                 	<input type="hidden"  name="type" id="type"  value="<?php if (!empty($faqData) && $faqData != null){echo "Edit";}else{echo "Add";}?>" />
                                 </div>
                              </div>
                               
                              <div class="control-group">
                                 <label class="control-label Grey" for="inputRemarks"><span class="error">*</span>Question:</label>
                                 <div class="controls width585">
                                     <textarea class="span6" maxlength="5000" rows="3" id="quesTion" name="quesTion" style="width:700px;height: 200px;"><?php if(!empty($faqQuestion)){echo stripcslashes($faqQuestion);}?></textarea>
                                 <div style="color:#FF0000;display:none" id="quesTionError"></div>
                                 </div>
                              </div>
                              <div class="control-group">
                                 <label class="control-label Grey" for="inputRemarks"><span class="error">*</span>Answer:</label>
                                 <div class="controls width585">
                                     <textarea class="span6" maxlength="5000" rows="3" id="ansWer" name="ansWer" style="width:700px;height: 200px;"><?php if(!empty($faqAnswer)){echo stripcslashes($faqAnswer);}?></textarea>
                                 <div style="color:#FF0000;display:none" id="ansWerError"></div>
                                 </div>
                              </div>
                             
                              <div class="form-actions">
                                 <button type="submit" class="btn btn-primary" onclick="return validateFaq();"><?php echo (!empty($faqId)) ? 'Update' : 'Add'; ?></button>
								  <button type="button" class="btn" onClick="returnPage('cms','faqlist');">Cancel</button>
                              </div>
                           </form>
                           <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 