<!-- TinyMCE -->
<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
         <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'cms','action'=>'faqlist', 'module' => 'admin'), null, true);?>">FAQ List</a>
							<li style="float:right"><a onClick="returnPage('cms','faq');" style="cursor:pointer;" title="Add FAQ"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/add_trophy.png" /></a></li>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
							<div class="widget">
								<div class="widget-title">
									<h4>FAQ List</h4>							
								</div>
								<div class="widget-body">
									<table class="table table-striped table-bordered" id="sample_1">
										<thead>
											<tr>
												<th width="7%">Sort Order</th>
												<th width="43%">Question</th>
												<th width="43%">Answer</th>
												<th width="6%">Actions</th>
											</tr>
										</thead>
										<tbody>
										<?php if($this->totalRecord>0){foreach ($this->faqData as $faqDataArray){?>
											<tr class="odd gradeX">
												<td><?php echo $faqDataArray['sort_order'];?></td>
                                                                                                <td><?php echo nl2br(stripslashes($faqDataArray['question']));?></td>
												<td ><?php echo nl2br(stripslashes($faqDataArray['answer']));?></td>
												<td class="center">
													<a href="<?php echo $this->url(array('controller'=>'cms','action'=>'faq',
													'id'=>base64_encode($faqDataArray['id']),'type' => 'edit', 'module' => 'admin'), null, true);?>" 
													class="icon huge" title="Edit FAQ"><i class="icon-pencil"></i></a>&nbsp;
													<a href="javascript:void(0);" <?php if($this->totalRecord <= 1) { echo 'class="disableanchor"';} ?>><img
													src="<?php  echo $this->baseUrl();?>/assets_admin/images/del.png"
													alt="Delete" title="Delete FAQ" border="0"
													<?php if($this->totalRecord > 1) {?> onClick="deleteData(<?php echo $faqDataArray['id'];?>,'cms','deletefaq')"
                                                                                                        <?php }else{ echo 'class="disableanchor"';} ?>/>
										</a>
												</td>
											</tr>
											<?php }}else{ ?>	
											<tr class="odd gradeX">
												<td class="center" colspan="4">
													<div align="center">NO RECORD FOUND</div>
												</td>
											</tr>
											<?php }?>
										</tbody>
									</table>
								</div>
							</div>
							<?php 	$perPage = $this->perpage;if($this->totalRecord > $perPage){ ?>
					<form name="searchFormSort" id="searchFormSort"
						action=""
                                                method="post" class="RecordPerPage">
                                            <span class="RecordPerPageSpan">Show&nbsp;</span><select name="perpage" onchange="javascript:sub_per_page('<?php echo curPageURL();?>',this.value);"
							class="span6" tabindex="1" id="">
							<option value="10"
							<?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
							<option value="25"
							<?php if($perPage == '25'){ echo 'selected=selected';}?>>25</option>
                                                        <option value="50"
							<?php if($perPage == '50'){ echo 'selected=selected';}?>>50</option>
                                                        <option value="100"
							<?php if($perPage == '100'){ echo 'selected=selected';}?>>100</option>
                                                </select><span class="RecordPerPageSpan">&nbsp;entries</span>
					</form>
					<?php }?>
					<?php  
			
						
					// pagination start
					if($this->totalRecord>0){
						if($this->totalRecord >$perPage){
							echo $this->paginationControl($this->faqData, 'Sliding', 'paginationquestion.phtml',array('perpage' =>$perPage));
						}else{
						}
					}
					// pagination ends ?>
					<script language="javascript">
					function sub_per_page(url,value)
					{
						var p =url.indexOf("/perpage");
						if(p == -1)
						{
							var urlone = url;
						}
						else
						{
							var urlone = url.split('/perpage')[0];		
						}
						url = urlone+'/perpage/'+value;
						window.location= url;
					}
					</script>
							<!-- END EXAMPLE TABLE PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 