<!-- BEGIN CONTAINER -->

<!-- BEGIN PAGE -->
<div id="body">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="widget-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            <h3>Widget Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here will be a configuration form</p>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <h3 class="page-title">An Error Occured</h3>

            </div>
        </div>
        <div id="page" class="dashboard" style = "font-size: 16px;" ><?php echo $this->message; ?></div>
        <!-- END PAGE CONTAINER-->		


        <?php if (isset($this->exception)): ?>

            <h3>Exception information:</h3>
            <p>
                <b>Message:</b> <?php echo $this->exception->getMessage() ?>
            </p>

            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?>
            </pre>

            <h3>Request Parameters:</h3>
            <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
            </pre>

        <?php endif ?>
    </div>
    <!-- END PAGE -->
</div>
<!-- END CONTAINER -->