<script type="text/javascript">
$(":file").filestyle({classButton: "btn btn-primary"});
</script>
<?php 
	$videoData  = $this->video; 
?>
<!-- TinyMCE -->
<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
         <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'video','action'=>'videolist', 'module' => 'admin'), null, true);?>"">Video Manager</a>
							<span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'video','action'=>'updatevideo', 'module' => 'admin'), null, true);?>"">Update Video</a>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                     <div class="widget-title">
									<h4>Update Video</h4>							
								</div>
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form name="videos" id="videos" action="<?php array('controller' =>'video', 'action' =>'updatevideo', 'module' =>'admin');?>" enctype="multipart/form-data" method="post" class="form-horizontal" onSubmit="return videoValidate();">
                              <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>Video Title:</label>
                                 <div class="controls">
                                    <input type="text"  class="span6 popovers " id="video_title" name="video_title" maxlength="50" data-trigger="hover" data-content="Enter Video title." data-original-title="Video Title" value="<?php echo $videoData->video_title;?>" />
                                 	<div style="color:#FF0000;display:none" id="video_title_erorr"></div>
                                 	<input type="hidden"  name="old_video"  value="<?php echo $videoData->video_file;?>" />
                                 	<input type="hidden"  name="id"  value="<?php echo $videoData->id;?>" />
                                 </div>
                              </div>
                               
                              <div class="control-group">
                                 <label class="control-label Grey" for="inputRemarks"><span class="error">*</span>Video URL</label>
                                 <div class="controls">
                                    <!-- <input type="file"  class="filestyle"  title="Search for a video to add" id="video" name="video"/> -->
                                    <input type="text"  class="span6 popovers " id="video_url" name="video_url" maxlength="50" data-trigger="hover" data-content="Enter Video URL." data-original-title="Video URL" value="<?php echo $videoData->video_url;?>" />
                                    <div style="color:#FF0000;display:none" id="video_url_error"></div>
                                 </div>
                              </div>
                             
                              <div class="form-actions">
                                 <button type="submit" class="btn btn-primary">Update</button>
                                 <button type="button" class="btn" onClick="returnPage('video','videolist');">Cancel</button>
                              </div>
                           </form>
                           <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 
      
      <script>$(document).ready(function(){$('input[type=file]').bootstrapFileInput();});</script>