 <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
          <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <?php if (isset($this->success) && $this->success != '') { ?>
                                    <div id="success" class="alert alert-success">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->success; ?>
                                    </div>
                                <?php } ?>
                                <?php
                                if (isset($this->error) && $this->error != '') {
                                    ?>
                                    <div id="exception" class="alert alert-error">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->error; ?>
                                    </div>
                                    <?php
                                }
                            ?>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                        <tr>
                                            <th>P.O.ID</th>
                                            <th>Client</th>
                                            <th>Product</th>
                                            <th>Quentity</th>
                                            <th>Amount</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                            <!--<th>Action</th>-->
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    $i          =   1;
                                    foreach($this->purchaseOrder as $data):
                                    $class      =   (($i%2)==0) ? "even gradeA" : "odd gradeA";
                                    ?>
                                        <tr class="<?php echo $class ?>">
                                            <td><?php echo $data['id'] ?></td>
                                            <td><?php echo $data['client_name'] ?></td>
                                            <td><?php echo $data['product_name'] ?></td>
                                            <td><?php echo $data['ordered_quentity'].''.$data['unit'] ?></td>
                                            <td class="center"><?php echo $data['amount'] ?></td>
                                            <td class="center"><?php echo $data['status'] ?></td>
                                            <td class="center">
                                            <a href="<?php echo $this->url(array('controller' => 'receipt', 'action' => 'print-purchase-order', 'module' => 'admin', 'orderId' => $data['id']), null, true); ?> " class="btn btn-info">
                                                <span > Print</span>
                                            </a>
                                            <a href="<?php echo $this->url(array('controller' => 'receipt', 'action' => 'create-challan', 'module' => 'admin', 'orderId' => $data['id']), null, true); ?> " class="btn btn-info">
                                                <span >Challan</span>
                                            </a>
                                            <a href="<?php echo $this->url(array('controller' => 'receipt', 'action' => 'create-invoice', 'module' => 'admin', 'orderId' => $data['id']), null, true); ?> " class="btn btn-info">
                                               <span >Invoice</span>
                                            </a>
                                            </td>
                                           <!--

                                           <td class="center">
                                            <a href="#" class="btn btn-info btn-lg">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                            <a href="#" class="btn btn-info btn-lg">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </a>
                                            </td>-->



                                        </tr>
                                    <?php endforeach;?>


                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->