<?php
$adminInfoSession 		= 		new Zend_Session_Namespace('adminInfo');
$remaning_quentity		= 		(int)($this->purchaseOrder['ordered_quentity'] - $this->purchaseOrder['given_quentity']);
$remaning_quentity		=		($remaning_quentity > 0 ) ? $remaning_quentity : 0 ;
?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
           <div class="row">

<div class="receipt-content">
    <div class="container bootstrap snippet">
 <?php if (isset($this->success) && $this->success != '') { ?>
                                    <div id="success" class="alert alert-success">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->success; ?>
                                    </div>
                                <?php } ?>
                                <?php
                                if (isset($this->error) && $this->error != '') {
                                    ?>
                                    <div id="exception" class="alert alert-error">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->error; ?>
                                    </div>
                                    <?php
                                }
                            ?>
		<div class="row">
<form role="form" action="" method="post" id="saveForm"  enctype="multipart/form-data" >
			<div class="col-lg-12"  id="print-div">
				<div class="invoice-wrapper">
					<div class="intro">
						<div class="col-md-2">
						<div class="img">
						<img src="<?php echo $this->baseUrl()?>/images/ashita_logo.png" alt="Ashita Export" />
						</div>
						</div>
						<div class="col-md-10">
						<center><?php echo $this->header?></center>
						<h1><center><?php echo $this->companyName ?></center></h1>

						<center><strong>Supplier Of:</strong> <?php echo $this->supplierOf ?></center>

						<center><?php echo $this->companyAddress ?></center>
						<center>Ph:- <?php echo $this->companyPhone ?></center>
						<center>TIN:- <?php echo $this->companyTin ?></center>
						</div>
					</div>

					<div class="payment-info">
						<div class="row">
							<div class="col-sm-6">

								  <div class="form-group">
                                            <label>Vat Challan No.</label>
                                            <strong>
												<input class="form-control"  name="challan_no" required="required" value="<?php echo $this->challanNo?>"></strong>
                                        </div>
							</div>
							<div class="col-sm-6 text-right">





            <div class="form-group">
			<label>Payment Date</label>
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control"  name="payment_date" required="true"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>









							</div>
						</div>
					</div>

					<div class="payment-details">
						<div class="row">
							<div class="col-sm-6">
								<span>Client</span>
								    <div class="form-group">

                                            <input type="text" readonly="readonly" class="form-control" value="<?php echo $this->purchaseOrder['client_name']  ?>">
											<input type="hidden" class="form-control" name="client_id" value="<?php echo $this->purchaseOrder['client_id']  ?>">
                                        </div>

									 <div class="form-group">

                                            <p>
												<input type="text" readonly="readonly" class="form-control" value="<?php echo $this->purchaseOrder['client_address']  ?>">
											</p>
											 <p>
												<input type="text" readonly="readonly" class="form-control" value="<?php echo $this->purchaseOrder['client_zip']  ?>">
											 </p>
                                        </div>


							</div>
							<div class="col-sm-6 text-left">
												<div class="col-sm-6 text-left">

													<div class="form-group">
													<p>Order No.<input class="form-control" name="order_no" readonly="readonly" value="<?php echo $this->purchaseOrder['id']  ?>"></p>
												  </div>

												  <div class="form-group">
													<p>Bill No.<input class="form-control" name="bill_no" required="true"></p>
												  </div>



													</div>


												<div class="col-sm-6 text-left">
												 <div class="form-group">
																   Date
											 <input class="form-control" name="po_date" readonly="readonly"
													value="<?php echo date("m/d/Y H:i A", strtotime($this->purchaseOrder['payment_date']))  ?>">
											</div>

													 <div class="form-group">
																   Date<div class='input-group date'   id='datetimepicker2'>
												<input type='text' class="form-control" name="bill_date"  />
												<span class="input-group-addon">
													<span class="glyphicon glyphicon-calendar"></span>
												</span>
											</div>
											</div>



										</div>



								</div>


							</div>
						</div>


					<div class="line-items">
						<div class="headers clearfix">
							<div class="row">
							<div class="col-xs-1">S.No.</div>
								<div class="col-xs-3">Description</div>
								<div class="col-xs-3">Packing</div>
								<div class="col-xs-3">Rate</div>
								<div class="col-xs-2 text-right" title="This is a remaning quantity which has to be provided">Remaining Quantity</div>
							</div>
						</div>
						<div class="items">

							<div class="row item">
								<div class="col-xs-1 desc">
									1
								</div>
						<div class="col-xs-3 qty">
							<div class="form-group">
								<input type="text" class="form-control" readonly="readonly" value="<?php echo $this->purchaseOrder['product_name']  ?>">
								<input type="hidden" name="product_id" class="form-control" value="<?php echo $this->purchaseOrder['product_id']  ?>">
								<input type="hidden" name="order_product_id" class="form-control" value="<?php echo $this->purchaseOrder['order_product_id']  ?>">


							</div>
						</div>

						<div class="col-xs-3 pack">
							<div class="form-group">
								<input type="number" class="form-control quantity"  name="quantity" style="width: 60%; float: left;" required="true" placeholder="50" min="1" max="<?php echo $remaning_quentity?>">
								<span class="unit_rate" style="line-height:2"> <?php echo $this->purchaseOrder['unit']  ?></span>

						  </div>
						</div>

						<div class="col-xs-3 pack">
							<div class="form-group">
								<input type="number" class="form-control productRate" name="rate"  style="width: 60%; float: left;" required="true" value="<?php echo $this->purchaseOrder['rate']  ?>">
								<span class="unit_rate" style="line-height:2"> /<?php echo $this->purchaseOrder['unit']  ?></span>

						  </div>
						</div>


								<div class="col-xs-2 pack" title="This is a remaning quantity which has to be provided">
									<div class="form-group">
                             <input type="text" class="form-control" readonly="readonly" value="<?php
							 echo  $remaning_quentity.' ' .$this->purchaseOrder['unit']  ?>">
							  </div>
								</div>


							</div>


						</div>
						<div class="total text-right">
							<p class="extra-notes text-left" style="color:#7a7a7a; float: left;font-size:13px; line-height:20px; text-align:left; width: 40%">
								<strong>Terms & Conditions</strong>
								1. Subject to Jaipur Jurisdiction Only.<br>
								2. No Claim for shortage or breakage will be entertained after the delivery of Goods.<br>
								3. Interest @20% p.a. will be charged extra on the total invoice amount if not paid to due date.
							<strong>This is an industrial thinner to be used for industrial purpose<br>
							We are not responsible for any missuse.</strong><br>
							</p>

							<div class="field">
								Subtotal <span> <input type="text" class="sub_total" required="required"  name="sub_total"></span>
							</div>
							<div class="field">
								VAT <?php echo  ($this->vat > 0) ? "(".$this->vat."%)" : ""?>
								<span>
									<input type="text" class="vat" value="0" vat="<?php echo $this->vat?>" name="vat">
								</span>
							</div>
							<div class="field">
								Shipping
								<span>
									<input type="text" value="0" class="shipping"  shipping="<?php echo $this->shipping?>" name="shipping">
								</span>
							</div>
							<div class="field">
								Discount <?php echo  ($this->discount > 0) ? "(".$this->discount."%)" : ""?>
								<span>
									<input type="text" value="0" class="discount"  discount="<?php echo $this->discount?>" name="discount">
								</span>
							</div>
							<div class="field ">
								Total <span> <input type="text"  class="total" required="required" required="true" name="total"></span>
							</div>


						</div>

						<!--<div class="total text-left">
							<div class="col-md-12">
								<p class="AmountInWords" style="display: none">
									<strong>Amount In words</strong>

								</p>
								<input type="hidden"  class="totalInWords" readonly="readonly"  name="totalInWords">
							</div>
						</div>-->


					</div>
				</div>
				<div class="footer" style="padding-top:15%;" >
				<div class="col-md-6 text-left">
				Receiver's Signature
				</div>
				<div  class="col-md-6 text-right" >
				Authorised Signatory
				</div>
				<div class="col-md-12" style="text-align:center">
					Copyright © 2016. Ashita Chemicals
					</div>
				</div>

			</div>

			<div class="col-lg-12 text-center">
						<div class="prints">
									<input type="hidden" class="form-control" name="added_by" value="<?php echo $adminInfoSession->adminData['admin_user_id']?>">
									<button class="btn btn-default" type="submit">Create challan</button>
						</div>

			</div>

</form>
		</div>

	</div>
</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
