<?php $order  =  $this->purchaseOrder[0]; ?>
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">

<div class="receipt-content">
    <div class="container bootstrap snippet">
		<div class="row">
			<div class="col-lg-12" id="print-div">
				<div class="invoice-wrapper">
                     <?php if(!empty($this->success)){  ?>
						<div id="success" class="alert alert-success">
						   <button class="close" data-dismiss="alert">×</button>
								 <?php echo $this->success;?>
						</div>
                        <?php } if(!empty($this->error)){ ?>
                        <div id="exception" class="alert alert-error">
                              <button class="close" data-dismiss="alert">×</button>
                              <?php echo $this->error;?>
                          </div>
                        <?php } ?>

						<div class="intro">
						<!--<div class="col-md-2">
						<div class="img">
						<img src="ashita_logo.png" alt="Ashita Export" />
						</div>
						</div>-->
						<div class="col-md-12">
						<center><?php echo $this->header?></center>
						<h1><center><?php echo $order['client_company_name']?></center></h1>

						<center><?php  $address = $order['client_address'].", ".$order['client_city']."-".$order['client_zip'].", ".$order['client_state'].", India"; echo $address;?> </center>
						<center>Ph:- <?php echo $order['client_phone']?></center>

						</div>
					</div>

        <div class="payment-info">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                                <label>Client</label>
								 <input type="text" readonly="readonly" value="<?php echo $order['client_name']?>"  class="form-control">

                    </div>
                </div>
		<div class="col-sm-6 text-right">

            <div class="form-group">
			<label>Payment Date</label>
                <div class="form-group">
					<input type="text" readonly="readonly" value="<?php echo date("m-d-Y", strtotime($order['payment_date']))?>"  class="form-control">

                    </div>
            </div>









							</div>
						</div>
					</div>

					<div class="client-details" >
						<div class="row">
							<div class="col-sm-12">
								<span>Client Detail</span>
								    <div class="form-group">

                                            <input class="form-control" value="<?php echo $order['client_company_name']?>" readonly="readonly" >
                                        </div>

									 <div class="form-group">

                                            <p><input class="form-control" value="<?php echo $address?>" readonly="readonly" ></p>
											 <p><input class="form-control" value="<?php echo $order['client_phone']?>" readonly="readonly" ></p>
                                        </div>


							</div>



							</div>
						</div>


					<div class="line-items">
						<div class="headers clearfix">
							<div class="row">
								<div class="col-xs-4">Description</div>
								<div class="col-xs-2">Quantity</div>
								<div class="col-xs-2">Rate</div>
								<div class="col-xs-4">Remarks</div>
							</div>
						</div>
						<div class="items">
							<div class="row item">

								<div class="col-xs-4 desc">
									<div class="form-group">
                                    <input class="form-control" value="<?php echo $order['product_name']?>" readonly="readonly" >

							  </div>

								</div>
                                <div class="col-xs-2 qty">
									<div class="form-group">
                                         <input class="form-control" value="<?php echo $order['ordered_quentity']." ". $order['unit']?>" readonly="readonly" >
									</div>
								</div>

								<div class="col-xs-2 rate text-left">
									    <input class="form-control" value="<?php echo $order['rate']."/". $order['unit']?>" readonly="readonly" >
								</div>
								<div class="col-xs-4 rate text-right">
									 <input class="form-control" value="<?php echo $order['remark']?>" readonly="readonly" >
								</div>
							</div>

						</div>
						<div class="total text-right">






							<div class="field grand-total">
								Total &#8377 <input type="text" value="<?php echo $order['amount']?>" readonly="readonly" >
							</div>


						</div>
						<div style="clear:both"></div>



					</div>

			<div class="payment-info">
            <div class="row">
                <div class="col-sm-6">

                    <div class="form-group">
                                <label> Date of Delivery </label>

                        <div class="form-group">
					<input type="text" readonly="readonly" value="<?php echo date("m-d-Y", strtotime($order['delivery_date']))?>"  class="form-control">

                    </div>
                    </div>
                </div>

		<div class="col-sm-6">
            <div class="form-group" style="margin-left: 15%;">
			<label>For</label>
                <input class="form-control" value="<?php echo $order['order_for']?>" readonly="readonly" >
            </div>
		</div>
						</div>

			 <div class="row">
                <div class="col-sm-12">

                    <div class="form-group">
						<?php echo (!empty($order['term'])) ? "<label>  Payment Term  </label> <br>".$order['term'] : "";?>


                    </div>
                </div>

		 <div class="col-sm-12">


                    <div class="form-group">
                        <?php echo (!empty($order['condition'])) ? "<label>  Other Conditions   </label> <br>".$order['condition'] : "";?>

                    </div>
                </div>
						</div>
					</div>

				</div>

				<div class="footer">

				<div style="padding-top:30px;" class="col-md-6 text-left">
				Supplier's Signature
				</div>
				<div style="padding-top:30px;" class="col-md-6 text-right" >
				Authorised Signatory
				</div>
				<div class="col-md-12">
					Please Provide original P.O. with bill. After Delivery date goods will be accapted after reasonable discount
					</div>
				</div>



            </div>
			<div class="col-lg-12 text-center">
						<div class="print">
							<a href="javascript:void(0);">
								<i class="fa fa-print"></i>
								Print this receipt
							</a>
						</div>
				</div>
		</div>

	</div>
</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
