<?php
$adminInfoSession 		= 		new Zend_Session_Namespace('adminInfo');
?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
           <div class="row">

<div class="receipt-content">
    <div class="container bootstrap snippet">

		<div class="row">
			 <?php if (isset($this->success) && $this->success != '') { ?>
                                    <div id="success" class="alert alert-success">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->success; ?>
                                    </div>
                                <?php } ?>
                                <?php
                                if (isset($this->error) && $this->error != '') {
                                    ?>
                                    <div id="exception" class="alert alert-error">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->error; ?>
                                    </div>
                                    <?php
                                }
                            ?>
<form role="form" action="" method="post" id="saveForm"  enctype="multipart/form-data">
			<div class="col-lg-12"  id="print-div">
				<div class="invoice-wrapper">
					<div class="intro">
						<div class="col-md-2">
						<div class="img">
						<img src="<?php echo $this->baseUrl()?>/images/ashita_logo.png" alt="Ashita Export" />
						</div>
						</div>
						<div class="col-md-10">
						<center><?php echo $this->header?></center>
						<h1><center><?php echo $this->companyName ?></center></h1>

						<center><strong>Supplier Of:</strong> <?php echo $this->supplierOf ?></center>

						<center><?php echo $this->companyAddress ?></center>
						<center>Ph:- <?php echo $this->companyPhone ?></center>
						<center>TIN:- <?php echo $this->companyTin ?></center>
						</div>
					</div>

					<div class="payment-info">
						<div class="row">
							<div class="col-sm-6">

								  <div class="form-group">
                                            <label>Vat Invoice No.</label>
                                            <strong><input class="form-control" readonly="readonly" value="<?php echo (!empty($this->invoice['invoice_no'])) ? $this->invoice['invoice_no'] : $this->invoiceNo?>"></strong>
                                        </div>
							</div>
							<div class="col-sm-6 text-right">





            <div class="form-group">
			<label>Payment Date</label>
                 <input class="form-control" readonly="readonly"
													value="<?php echo date("m/d/Y H:i A", strtotime($this->invoice['payment_date']))  ?>">
            </div>









							</div>
						</div>
					</div>

					<div class="payment-details">
						<div class="row">
							<div class="col-sm-6">
								<span>Client</span>
								    <div class="form-group">

                                            <input type="text" readonly="readonly" class="form-control" value="<?php echo $this->purchaseOrder['client_name']  ?>">

                                        </div>

									 <div class="form-group">

                                            <p>
												<input type="text" readonly="readonly" class="form-control" value="<?php echo $this->purchaseOrder['client_address']  ?>">
											</p>
											 <p>
												<input type="text" readonly="readonly" class="form-control" value="<?php echo $this->purchaseOrder['client_zip']  ?>">
											 </p>
                                        </div>


							</div>
							<div class="col-sm-6 text-left">

												<div class="col-sm-6 text-left">

													<div class="form-group">
													<p>Order No.<input class="form-control" name="order_no" readonly="readonly" value="<?php echo $this->purchaseOrder['id']  ?>"></p>
												  </div>

												  <div class="form-group">
													<p>G.R No.<input class="form-control" readonly="readonly" value="<?php echo $this->invoice['gr_no']  ?>" ></p>
												  </div>



													</div>


									   <div class="col-sm-6 text-left">
											  <div class="form-group">
																   Date
											 <input class="form-control"  readonly="readonly"
													value="<?php echo date("m/d/Y H:i A", strtotime($this->purchaseOrder['payment_date']))  ?>">
											</div>

											 <div class="form-group">
																   Date
											 <input class="form-control"   readonly="readonly"
													value="<?php echo date("m/d/Y H:i A", strtotime($this->invoice['gr_date']))  ?>">
											</div>

										</div>


	<!-- CHallan detail and date--Start-->
	<?php foreach($this->challan as $challan): ?>
	<div class="col-sm-6 text-left">
					<div class="form-group">
						<p>Challan No.
						<input class="form-control" name="challan_ids[]" readonly="readonly" value="<?php echo $challan['challan_id']  ?>"></p>
					  </div>

	</div>

	<div class="col-sm-6 text-left">
					<div class="form-group">
						<p>Challan Date.
						<input class="form-control" readonly="readonly" value="<?php echo date("m/d/Y H:i A", strtotime($challan['payment_date']))  ?>"></p>
					  </div>

	</div>

	<?php endforeach?>



<!-- CHallan detail and date--Start-->


								</div>


							</div>
						</div>


					<div class="line-items">
						<div class="headers clearfix">
							<div class="row">
							<div class="col-xs-1">S.No.</div>
								<div class="col-xs-3">Description</div>
								<div class="col-xs-3">Quantity</div>
								<div class="col-xs-3">Rate</div>
								<div class="col-xs-2 text-right">Amount</div>
							</div>
						</div>

				<!-- Challan product detail and date--Start-->
				 <?php $i=1;
				 foreach($this->challan as $challan): ?>
						<div class="items">

							<div class="row item">
								<div class="col-xs-1 desc">
									<?=$i?>
								</div>
						<div class="col-xs-3 qty">
							<div class="form-group">
								<input type="text" class="form-control" readonly="readonly" value="<?php echo $this->purchaseOrder['product_name']  ?>">


							</div>
						</div>

						<div class="col-xs-3 pack">
							<div class="form-group">
								<input type="number" class="form-control"  value="<?=$challan['quantity']?>" style="width: 60%; float: left;" readonly="readonly" >
								<span class="unit_rate" style="line-height:2"> <?php echo $this->purchaseOrder['unit']  ?></span>

						  </div>
						</div>

						<div class="col-xs-3 pack">
							<div class="form-group">
								<input type="number" class="form-control" readonly="readonly" style="width: 60%; float: left;" required="true" value="<?php echo $this->purchaseOrder['rate']  ?>">
								<span class="unit_rate" style="line-height:2"> /<?php echo $this->purchaseOrder['unit']  ?></span>

						  </div>
						</div>


								<div class="col-xs-2 pack">
									<div class="form-group">
                             <input type="text" class="form-control" readonly="readonly" value="<?php
							 echo  $challan['sub_total'] ?>">
							  </div>
								</div>


							</div>


						</div>
				<?php $i++;
				  endforeach;
					$totalSubtotal 		=	number_format($this->invoice['sub_total'], 2, '.', '');
					$totalVat 			=	number_format($this->invoice['vat'], 2, '.', '');
					$totalShipping 		=	number_format($this->invoice['shipping'], 2, '.', '');
					$totalDiscount 		=	number_format($this->invoice['discount'], 2, '.', '');
					$total 				=	number_format($this->invoice['total'], 2, '.', '');

				?>


						<div class="total text-right">
							<p class="extra-notes text-left" style="color:#7a7a7a; float: left;font-size:13px; line-height:20px; text-align:left; width: 40%">
								<strong>Terms & Conditions</strong>
								1. Subject to Jaipur Jurisdiction Only.<br>
								2. No Claim for shortage or breakage will be entertained after the delivery of Goods.<br>
								3. Interest @20% p.a. will be charged extra on the total invoice amount if not paid to due date.
							<strong>This is an industrial thinner to be used for industrial purpose<br>
							We are not responsible for any missuse.</strong><br>
							</p>

							<div class="field">
								Subtotal <span> <input type="text" name="sub_total" readonly="readonly" value="<?=$totalSubtotal?>"></span>
							</div>
							<div class="field">
								VAT <?php echo  ($this->invoice['vat_value'] > 0) ? "(".$this->invoice['vat_value']."%)" : ""?>
								<span>
									<input type="text" name="vat" readonly="readonly" value="<?=$totalVat?>"  >
								</span>
							</div>
							<div class="field">
								Shipping
								<span>
									<input type="text" name="shipping" value="<?=$totalShipping?>" readonly="readonly" >
								</span>
							</div>
							<div class="field">
								Discount <?php echo  ($this->invoice['discount_value'] > 0) ? "(".$this->invoice['discount_value']."%)" : ""?>
								<span>
									<input type="text" name="discount" value="<?=$totalDiscount?>"  readonly="readonly"  >
								</span>
							</div>
							<div class="field ">
								Total <span> <input type="text" name="total" readonly="readonly" value="<?=$total?>"></span>
							</div>


						</div>

						<div class="total text-left">
							<div class="col-md-12">
								<p class="AmountInWords">
									<strong>Amount In words:</strong>
									<?php
										echo amountInWords($total);
										//echo $this->invoice['totalInWords'];
										?>


								</p>
							</div>
						</div>


					</div>
				</div>
				<div class="footer" style="padding-top:15%;" >
				<div class="col-md-6 text-left">
				Receiver's Signature
				</div>
				<div  class="col-md-6 text-right" >
				Authorised Signatory
				</div>
				<div class="col-md-12" style="text-align:center">
					Copyright © 2016. Ashita Chemicals
					</div>
				</div>

			</div>

			<div class="col-lg-12 text-center">
						<div class="print">
							<a href="#">
								<i class="fa fa-print"></i>
								Print this receipt
							</a>
						</div>

			</div>

</form>
		</div>

	</div>
</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
