<?php
 $challan  =  $this->challan[0];
?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
           <div class="row">

<div class="receipt-content">
    <div class="container bootstrap snippet">
 <?php if (isset($this->success) && $this->success != '') { ?>
                                    <div id="success" class="alert alert-success">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->success; ?>
                                    </div>
                                <?php } ?>
                                <?php
                                if (isset($this->error) && $this->error != '') {
                                    ?>
                                    <div id="exception" class="alert alert-error">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->error; ?>
                                    </div>
                                    <?php
                                }
                            ?>
		<div class="row">
<form role="form" action="" method="post" id="saveForm"  enctype="multipart/form-data" >
			<div class="col-lg-12"  id="print-div">
				<div class="invoice-wrapper">
					<div class="intro">
						<div class="col-md-2">
						<div class="img">
						<img src="<?php echo $this->baseUrl()?>/images/ashita_logo.png" alt="Ashita Export" />
						</div>
						</div>
						<div class="col-md-10">
						<center><?php echo $this->header?></center>
						<h1><center><?php echo $this->companyName ?></center></h1>

						<center><strong>Supplier Of:</strong> <?php echo $this->supplierOf ?></center>

						<center><?php echo $this->companyAddress ?></center>
						<center>Ph:- <?php echo $this->companyPhone ?></center>
						<center>TIN:- <?php echo $this->companyTin ?></center>
						</div>
					</div>

					<div class="payment-info">
						<div class="row">
							<div class="col-sm-6">

								  <div class="form-group">
                                            <label>Vat Challan No.</label>
                                            <strong><input class="form-control" readonly="readonly" value="<?php echo $challan['id']?>"></strong>
                                        </div>
							</div>
							<div class="col-sm-6 text-right">





            <div class="form-group">
			<label>Payment Date</label>
                <div class='input-group' style="margin-left: 66%;">
                    <input type='text' class="form-control" readonly="readonly" value="<?php echo date("m-d-Y", strtotime($challan['payment_date']))?>"/>
                </div>
            </div>


							</div>
						</div>
					</div>

					<div class="payment-details">
						<div class="row">
							<div class="col-sm-6">
								<span>Client</span>
								    <div class="form-group">

                                            <input type="text" readonly="readonly" class="form-control" value="<?php echo $challan['client_name']  ?>">  </div>

									 <div class="form-group">

                                            <p>
												<input type="text" readonly="readonly" class="form-control" value="<?php echo $challan['client_address']  ?>">
											</p>
											 <p>
												<input type="text" readonly="readonly" class="form-control" value="<?php echo $challan['client_zip']  ?>">
											 </p>
                                        </div>


							</div>
							<div class="col-sm-6 text-left">
												<div class="col-sm-6 text-left">

													<div class="form-group">
													<p>Order No.<input class="form-control"  readonly="readonly" value="<?php echo $challan['order_no']  ?>"></p>
												  </div>

												  <div class="form-group">
													<p>Bill No.<input class="form-control"  readonly="readonly" value="<?php echo $challan['bill_no']  ?>"></p>
												  </div>



													</div>


												<div class="col-sm-6 text-left">
												 <div class="form-group">
																   Date
											 <input class="form-control"  readonly="readonly"
													value="<?php echo date("m-d-Y", strtotime($challan['payment_date']))  ?>">
												</div>

											 <div class="form-group">
																   Date
												<input class="form-control"  readonly="readonly"
													value="<?php echo date("m-d-Y", strtotime($challan['bill_date']))  ?>">
												</div>



										</div>



								</div>


							</div>
						</div>


					<div class="line-items">
						<div class="headers clearfix">
							<div class="row">
							<div class="col-xs-1">S.No.</div>
								<div class="col-xs-3">Description</div>
								<div class="col-xs-3">Packing</div>
								<div class="col-xs-3">Rate</div>
								<div class="col-xs-2 text-right">Required Quantity</div>
							</div>
						</div>
						<div class="items">

							<div class="row item">
								<div class="col-xs-1 desc">
									1
								</div>
						<div class="col-xs-3 qty">
							<div class="form-group">
								<input type="text" class="form-control" readonly="readonly" value="<?php echo $challan['product_name']  ?>">
							</div>
						</div>

						<div class="col-xs-3 pack">
							<div class="form-group">
							<input type="text" class="form-control" readonly="readonly" style="width: 60%; float: left;" value="<?php echo $challan['quantity']  ?>">
							<span class="unit_rate" style="line-height:2"> <?php echo $challan['unit']  ?></span>

						  </div>
						</div>

						<div class="col-xs-3 pack">
							<div class="form-group">
								<input type="text" class="form-control" readonly="readonly" style="width: 60%; float: left;" value="<?php echo $challan['rate']  ?>">
								<span class="unit_rate" style="line-height:2"> /<?php echo $challan['unit']  ?></span>

						  </div>
						</div>


								<div class="col-xs-2 pack">
									<div class="form-group">
                             <input type="text" class="form-control" readonly="readonly" value="<?php echo ($challan['given_quentity']-$challan['quantity']).' ' .$challan['unit']  ?>">
							  </div>
								</div>


							</div>


						</div>
						<div class="total text-right">
							<p class="extra-notes text-left" style="color:#7a7a7a; float: left;font-size:13px; line-height:20px; text-align:left; width: 40%">
								<strong>Terms & Conditions</strong>
								1. Subject to Jaipur Jurisdiction Only.<br>
								2. No Claim for shortage or breakage will be entertained after the delivery of Goods.<br>
								3. Interest @20% p.a. will be charged extra on the total invoice amount if not paid to due date.
							<strong>This is an industrial thinner to be used for industrial purpose<br>
							We are not responsible for any missuse.</strong><br>
							</p>

							<div class="field">
								Subtotal <span> <input type="number"  value="<?php echo $challan['sub_total']?>" readonly="readonly" name="sub_total"></span>
							</div>
							<div class="field">
								VAT <?php echo  ($this->vat > 0) ? "(".$this->vat."%)" : ""?>
								<span>
									<input type="number" readonly="readonly" value="<?php echo $challan['vat']?>"   name="vat">
								</span>
							</div>
							<div class="field">
								Shipping
								<span>
									<input type="number" readonly="readonly"  value="<?php echo $challan['shipping']?>"  >
								</span>
							</div>
							<div class="field">
								Discount <?php echo  ($this->discount > 0) ? "(".$this->discount."%)" : ""?>
								<span>
									<input type="number"  value="<?php echo $challan['discount']?>" readonly="readonly"  >
								</span>
							</div>
							<div class="field ">
								Total <span> <input type="number" value="<?php echo $challan['total']?>" readonly="readonly" required="true"  ></span>
							</div>


						</div>

						<div class="total text-left">
							<div class="col-md-12">
								<p >
									<strong>Amount In words:</strong> <?php echo $challan['totalInWords']?>
								</p>
							</div>
						</div>


					</div>
				</div>
				<div class="footer" style="padding-top:15%;" >
				<div class="col-md-6 text-left">
				Receiver's Signature
				</div>
				<div  class="col-md-6 text-right" >
				Authorised Signatory
				</div>
				<div class="col-md-12" style="text-align:center">
					Copyright © 2016. Ashita Chemicals
					</div>
				</div>

			</div>

			<div class="col-lg-12 text-center">
						<div class="print">
							<a href="#">
								<i class="fa fa-print"></i>
								Print this receipt
							</a>
						</div>

			</div>

</form>
		</div>

	</div>
</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
