<?php
$adminInfoSession = new Zend_Session_Namespace('adminInfo');
?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">

<div class="receipt-content">
    <div class="container bootstrap snippet">
		<div class="row">
 <form role="form" action="" method="post"  enctype="multipart/form-data">
			<div class="col-lg-12">
				<div class="invoice-wrapper">
                     <?php if(!empty($this->success)){  ?>
						<div id="success" class="alert alert-success">
						   <button class="close" data-dismiss="alert">×</button>
								 <?php echo $this->success;?>
						</div>
                        <?php } if(!empty($this->error)){ ?>
                        <div id="exception" class="alert alert-error">
                              <button class="close" data-dismiss="alert">×</button>
                              <?php echo $this->error;?>
                          </div>
                        <?php } ?>

        <div class="payment-info">
            <div class="row">
                <div class="col-sm-6">

                    <div class="form-group">
                                <label>Client</label>

                                 <select class="form-control selectClient" required="required" name="client_id" id="client_id">
                                    <option value="">Select One</option>

                                    <?php foreach($this->clients  as $clients):
                                        $selected       =   ($this->client == $clients['id']) ? "selected= selected" : "";
                                        $company_name   =   "company_name   = '$clients[company_name]'";
                                        $phone          =   "phone          = '$clients[phone]'";
                                        $address        =   "address        = '$clients[address], $clients[city], $clients[state], $clients[country]'";


                                        echo "<option $address $phone $company_name value='".$clients[id]."' $selected >$clients[name]</option>";
                                    endforeach;?>

                                  </select>
                    </div>
                </div>
		<div class="col-sm-6 text-right">





            <div class="form-group">
			<label>Payment Date</label>
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" name="payment_date"  required="true" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>









							</div>
						</div>
					</div>

					<div class="client-details" style="display: none">
						<div class="row">
							<div class="col-sm-12">
								<span>Client Detail</span>
								    <div class="form-group">

                                            <input class="form-control company_name" readonly="readonly" >
                                        </div>

									 <div class="form-group">

                                            <p><input class="form-control address" readonly="readonly" ></p>
											 <p><input class="form-control phone" readonly="readonly" ></p>
                                        </div>


							</div>



							</div>
						</div>


					<div class="line-items">
						<div class="headers clearfix">
							<div class="row">
								<div class="col-xs-3">Description</div>
                                <div class="col-xs-2">Aval. Quantity</div>
								<div class="col-xs-2">Req. Quantity</div>
								<div class="col-xs-2">Rate</div>
								<div class="col-xs-3">Remarks</div>
							</div>
						</div>
						<div class="items">
							<div class="row item">

								<div class="col-xs-3 desc">
									<div class="form-group">
                                    <select class="form-control selectProduct" required="required" name="product_id" id="product_id">
                                    <option value="">Select One</option>

                                    <?php foreach($this->product  as $product):
                                        $selected       =   ($this->product_id == $product['id']) ? "selected= selected" : "";

                                        $unit           =   "unit           = '$product[unit]'";
                                        $stock          =   "stock          = '$product[stock]'";
										$price          =   "price          = '$product[price]'";



                                        echo "<option $unit $stock $price value='".$product[id]."' $selected >$product[name]</option>";
                                    endforeach;?>

                                  </select>

							  </div>

								</div>

								<div class="col-xs-2 qty">
									<div class="form-group">
                                        <input type="number" readonly="readonly" min="1" alt="If value is 0 that mean this product is not in stock" class="form-control stock" placeholder="50">

                                    </div>
								</div>
                                <div class="col-xs-2 qty">
									<div class="form-group">
                                        <input type="number" name="ordered_quentity" min="1" required="true" class="form-control midBox ordered_quentity"  style="width: 60%; float: left;"   floplaceholder="50">
                                    <span class="unit" style="line-height:2"></span>
                                    </div>
								</div>

								<div class="col-xs-2 rate text-left">
									<input type="number" name="rate" required="true" min="1" class="form-control unit_price" style="width: 60%; float: left;" placeholder="50">
                                    <span class="unit_rate" style="line-height:2"></span>
								</div>
								<div class="col-xs-3 rate text-right">
									<input type="text" name="remark" class="form-control" placeholder="Remarks">
								</div>
							</div>

						</div>
						<div class="total text-right">






							<div class="field grand-total">
								Total &#8377 <input type="text" class="TotalAmount" placeholder="000.00" name="amount" readonly="true">
							</div>


						</div>
						<div style="clear:both"></div>



					</div>

			<div class="payment-info">
            <div class="row">
                <div class="col-sm-6">

                    <div class="form-group">
                                <label> Date of Delivery </label>

                        <div class='input-group date' id='datetimepicker2'>
							<input type='text' class="form-control" required="true" name="delivery_date"  required="true" />
							<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
							</span>
						</div>
                    </div>
                </div>

		<div class="col-sm-6">
            <div class="form-group" style="margin-left: 15%;">
			<label>For</label>
                <div class="checkbox">
							<label>
							  <input type="radio"  name="order_for" id="order_for" value="Our Godown"> Our Godown
							</label>
							<label>
							  <input type="radio" name="order_for" checked="checked" id="order_for" value="Your Godown"> Your Godown
							</label>
				</div>
            </div>
		</div>
						</div>

			 <div class="row">
                <div class="col-sm-12">

                    <div class="form-group">
                                <label>  Payment Term  </label>

                        <textarea class="form-control" placeholer="Payment Term" rows="6" name="term"></textarea>

                    </div>
                </div>

		 <div class="col-sm-12">

                    <div class="form-group">
                                <label>  Other Conditions   </label>

                        <textarea class="form-control" placeholer="Other Conditions" rows="6" name="condition"></textarea>

                    </div>
                </div>
						</div>
					</div>

				</div>


				<div class="col-lg-12 text-center">
						<div class="prints">
							<input type="hidden" class="form-control" name="added_by" value="<?php echo $adminInfoSession->adminData['admin_user_id']?>">
							 <button class="btn btn-default" type="submit">Placed Order</button>
						</div>
				</div>


            </div>
 </form>
		</div>

	</div>
</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
