
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">

<div class="receipt-content">
    <div class="container bootstrap snippet">
		<div class="row">
			<div class="col-lg-12">
				<div class="invoice-wrapper">

					<div class="payment-info">
						<div class="row">
							<div class="col-sm-6">

								  <div class="form-group">
                                            <label>P.O No.</label>
                                            <strong><input class="form-control" placeholder="1234567"></strong>
                                        </div>
							</div>
							<div class="col-sm-6 text-right">





            <div class="form-group">
			<label>Payment Date</label>
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>









							</div>
						</div>
					</div>

					<div class="payment-details">
						<div class="row">
							<div class="col-sm-12">
								<span>Client</span>
								 <form role="form">
								    <div class="form-group">

                                            <input class="form-control" placeholder="Name">
                                        </div>

									 <div class="form-group">

                                            <p><input class="form-control" placeholder="Add1"></p>
											 <p><input class="form-control" placeholder="Add2"></p>
											 <p><input class="form-control" placeholder="Pin"></p>
                                        </div>


								</form>
							</div>



							</div>
						</div>


					<div class="line-items">
						<div class="headers clearfix">
							<div class="row">
							<div class="col-xs-1">S.No.</div>
								<div class="col-xs-4">Description</div>
								<div class="col-xs-2">Quantity</div>
								<div class="col-xs-2">Rate</div>
								<div class="col-xs-3 text-right">Remarks</div>
							</div>
						</div>
						<div class="items">
						<form role="form">
							<div class="row item">
								<div class="col-xs-1 sno">
									1
								</div>
								<div class="col-xs-4 desc">
									<div class="form-group">
                              <input type="text" class="form-control" placeholder="Syn. Thinner">

							  </div>

								</div>

								<div class="col-xs-2 qty">
									<div class="form-group">
                              <input type="number" class="form-control" placeholder="50">

							  </div>
								</div>
								<div class="col-xs-2 rate text-left">
									50 Ltr
								</div>
								<div class="col-xs-3 rate text-right">
									10245
								</div>
							</div>

					<div class="row item">
								<div class="col-xs-1 sno">
									1
								</div>
								<div class="col-xs-4 desc">
									<div class="form-group">
                              <input type="text" class="form-control" placeholder="Syn. Thinner">

							  </div>

								</div>

								<div class="col-xs-2 qty">
									<div class="form-group">
                              <input type="number" class="form-control" placeholder="50">

							  </div>
								</div>
								<div class="col-xs-2 rate text-left">
									50 Ltr
								</div>
								<div class="col-xs-3 rate text-right">
									10245
								</div>
							</div>


							</form>
						</div>
						<div class="total text-right">






							<div class="field grand-total">
								Total <span>$332.00</span>
							</div>


						</div>
						<div style="clear:both"></div>



					</div>
				</div>

				<div class="footer">
					<div class="total text-left">
						<div class="col-md-12">

							<div class="col-md-6">
						Date of Delivery
						<div class='input-group date' id='datetimepicker1'>
												<input type='text' class="form-control" />
												<span class="input-group-addon">
													<span class="glyphicon glyphicon-calendar"></span>
												</span>
											</div>
						For
						 <div class="checkbox">
    <label>
      <input type="checkbox"> Our Godown
    </label>
	<label>
      <input type="checkbox"> Your Godown
    </label>
  </div>
						</div>
								<div class="col-md-6">
						Payment Term
						<div class='input-group date' id='datetimepicker1'>
												<input type='text' class="form-control" />
												<span class="input-group-addon">
													<span class="glyphicon glyphicon-calendar"></span>
												</span>
											</div>
						Other Conditions
						<input class="form-control" type="text" >
						</div>

						</div>
						</div>
				<div style="padding-top:30px;" class="col-md-6 text-left">
				Supplier's Signature
				</div>
				<div style="padding-top:30px;" class="col-md-6 text-right" >
				Authorised Signatory
				</div>
				<div class="col-md-12">
					Please Provide original P.O. with bill. After Delivery date goods will be accapted after reasonable discount
					</div>
				</div>
				<div class="col-lg-12 text-center">
						<div class="print">
							<a href="#">
								<i class="fa fa-print"></i>
								Print this receipt
							</a>
						</div>
						</div>
			</div>
		</div>
	</div>
</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
      
