<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="#e0e1e5" style="font-family: 'Arial, Helvetica, sans-serif'; font-size: 14px; color: #4C649B;">
        <p>Hi Admin,</p>
        <p><?php echo $this->message; ?></p>    
        <p>
            <span>From: <?php echo $this->name; ?></span><br />
            <span>Website: <?php echo $this->website; ?></span>
        </p>                                                  
    </body>
</html>




