 <!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
 


         <?php if(isset($this->success) && $this->success != ''){
		 ?>
		
		 <?php
		 ?>
		 
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
				 
				
        	 ?>
<div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							 <li><a href="<?php echo $this->url(array('controller'=>'manages','action'=>'list', 'module' => 'admin'), null, true);?>">Manage Admin Users</a> <span class="divider">/</span> </li>
							<li><a  href="javascript:void(0)">Add</a></li>
							</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                         <div class="widget-title">
                           <h4><i class="icon-reorder"></i>Add Admin</h4>
                          
                        </div>
						
                        
						<div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form name="cms" id="cms" action="<?php array('controller' =>'manages', 'action' =>'add', 'module' =>'admin');?>" method="post" class="form-horizontal" onsubmit="return validateManages('add')" enctype="multipart/form-data">
                              
                              <table width="90%" class="" cellspacing="8" cellpadding="8">
                   			    
                   				  <tr>
                   				   <td width="14%"><label class="control-label Grey" for="input3"><span class="error">*</span>Username:</label></td>
                   				   <td colspan="3">
                   				   			<input type="text"  class="span6 popovers" id="username" name="username" data-trigger="hover" value="<?php  echo $this->username; ?>" maxlength="20"  />
                   				   			<div style="color:#FF0000;display:none" id="username_error" ></div>
                                 			
                                 	</td>
                              </tr>
							  
							  <tr>
                   				   <td width="14%"><label class="control-label Grey" for="input3"><span class="error">*</span>Password:</label></td>
                   				   <td colspan="3">
								  
								  <input type="password"  class="span6 popovers" id="password" name="password" data-trigger="hover" value="<?php  echo $this->password ; ?>" maxlength="16"  />
                   				   	<div style="color:#FF0000;display:none" id="passwordError"></div>		
                                 			
                               	</td>
                              </tr>
							  
							  <tr>
                   				   <td width="14%"><label class="control-label Grey" for="input3"><span class="error">*</span>Name:</label></td>
                   				   <td colspan="3">
								  
								  <input type="text"  class="span6 popovers" id="name" name="name" data-trigger="hover" value="<?php  echo $this->name ; ?>" maxlength="20"  />
                   				   	<div style="color:#FF0000;display:none" id="name_error" ></div>	
                                 			
                               	</td>
                              </tr>
							   <tr>
                   				   <td width="14%"><label class="control-label Grey" for="input3"><span class="error">*</span>Email:</label></td>
                   				   <td colspan="3">
								  
								  <input type="text"  class="span6 popovers" id="email" name="email" data-trigger="hover" value="<?php  echo $this->email ; ?>"   />
                   				   		<div style="color:#FF0000;display:none" id="email_error" ></div>	
                                 			
                               	</td>
                              </tr>
							   <tr>
                   				   <td width="14%"><label class="control-label Grey" for="input3"><span class="error">*</span>Phone:</label></td>
                   				   <td colspan="3">
								  
								  <input type="text"  class="span6 popovers" id="phone" name="phone" data-trigger="hover" value="<?php  echo $this->phone ; ?>" maxlength="12"  />
                   				   	<div style="color:#FF0000;display:none" id="phone_error" ></div>		
                                 			
                               	</td>
                              </tr>
							  <tr>
               				    <td width="14%"><label class="control-label Grey" for="input3">Upload Image:</label><br /> </td>
                   				   <td colspan="2">
								   <img src="<?php echo $this->baseUrl();?>/assets_admin/images/loading.gif" id="load" style="display:none;">
                   				   			<div class="UsrBrowseImg"> 
                   				   			
							   <input type="file" name="images" id="images" title="Add Image" class="Browse4"> 
     <div style="color:#FF0000;display:none" id="image_error" ></div>
    </div>
                                 			
                               	</td>
									<td width="68%"> <a href="#" id="imageblock">
	  <?php 
	  	  if($this->image!=''){?>
	  <img id="image-item" src="<?php echo $this->baseUrl();?>/images/user/<?php echo $this->image;?>" class="UserImgBig"  alt="photo">
	 <?php } else {?>
     <img id="image-item" src="<?php echo $this->baseUrl();?>/images/user/no-image.jpg" class="UserImgBig"  alt="photo" height="100" width="100">
	 <?php }?>
	   
     			   </a> <br />
     			    PNG / BMP / JPEG / JPG / TIFF / GIF</td>
                              </tr>
							  
                              </table>
							 <div class="form-actions">
							  
							   <input type="hidden" name="controller_pathImage" id="controller_pathImage" value="admin/manages/uploadimage" >
							   <input type="hidden" name="image_file_name" id="image_file_name" value="<?php echo $this->image; ?>"><br />
                              <input type ="submit" class="btn btn-primary" id="checkcategorybutton" value="Add" >
									<input type="button" class="btn"
										 onClick="returnPage('manages','list');" 
										value="Cancel">
                               <input type="hidden" name="SITE_URL" id="SITE_URL" value="<?php echo $this->baseUrl();?>" >
                                
                             </div>
                           </form>
                       <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 
	  <script src="<?php echo $this->baseUrl();?>/assets_admin/js/jquery.ui.core.js"></script>
	<script src="<?php echo $this->baseUrl();?>/assets_admin/js/jquery.ui.widget.js"></script>
	<script src="<?php echo $this->baseUrl();?>/assets_admin/js/jquery.ui.mask.js"></script>
	
<script src="<?php echo $this->baseUrl();?>/assets_admin/js/uploadManage.js"></script>
<script language="javascript">
$( "#phone" ).mask({ mask: "999-999-9999" }).blur(function(event) {
                        /*if (!$(event.target).mask("valid")) {
                                $(event.target).val("")
                        }*/
                });;



</script>