 <script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php  //echo '<pre>'; print_r($this->categoryData); die;?>
<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Trophy Manager</h3>
            </div>
            
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
         <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						<h3 class="page-title">
							Trophy Manager
							
						</h3>
						
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
				<!-- BEGIN PAGE CONTENT-->
				<div id="page" class="dashboard">
					<div class="row-fluid">
						<div class="span12">
							<!-- BEGIN EXAMPLE TABLE PORTLET-->
							<div class="widget">
								<div class="widget-title">
									<h4><i class="icon-reorder"></i>Trophy List</h4>						
								</div>
								<div class="widget-body">
																		
									
									
									<table class="table table-striped table-bordered" id="trophylist">
										<thead>
											<tr>
												<th>#</th>
												<th>Title</th>
												<th class="hidden-phone">Points</th>
												<th class="hidden-phone">Description</th>
												
												<th class="hidden-phone">Image</th>
												<th class="hidden-phone">Action</th>
												
												
											</tr>
										</thead>
										<tbody>
										
										 <?php 
										 
										
										 if($this->totalRecord>0){
										
										 
									   foreach($this->trophyData as $caq){
									   
									   	
									   	?>
											<tr class="odd gradeX">
											<td class="hidden-phone"><?php echo $caq['trophy_id'];?></td>
												<td class="hidden-phone"><?php echo $caq['title'];?></td>
												<td class="hidden-phone"><?php echo $caq['points'];?></td>
												<td class="hidden-phone center"><?php echo $caq['description'];?></td>
												
												<td class="hidden-phone center">
										<a href="<?php echo $this->url(array('controller' =>'trophy','action'=>'view','module'=>'admin','id' =>$caq['trophy_id']),null,true);?>"><img src="<?php echo $this->baseUrl();?>/assets_admin/images/view.png" alt="View Category Detail" title="View Category Detail" border="0"/></a>		
									 
									   			<a href="<?php echo $this->url(array('controller' =>'trophy','action'=>'edit','module'=>'admin','id' =>$caq['trophy_id']),null,true);?>"><img border="0" title="Edit" alt="Edit" src="<?php echo $this->baseUrl();?>/assets_admin/images/edit.png"></a>
												<a href="javascript:void(0);"><img src="<?php  echo $this->baseUrl();?>/assets_admin/images/delete.png" alt="Delete Category" title="Delete Category" border="0" onClick="deleteData(<?php echo $caq['trophy_id'];?>,'questions','deletecategory')"/></a>
											
												</td>
												
												
											</tr>
									<?php }
										 }else{	?>		
										<tr class="odd gradeX">
										     <td class="hidden-phone" colspan="6" style="text-align: center">NO RECORD FOUND</td>
									   </tr>	
									<?php }?>     
										</tbody>
									</table>
								</div>
								
								
							</div>
							
							      <?php  
							$perPage = $this->perpage;
							      
							      // pagination start
					 if($this->totalRecord>0){
						if($this->totalRecord >$perPage){
							echo $this->paginationControl($this->categoryData, 'Sliding', 'pagination.phtml',array('seachdata' =>$this->searchdata,'perpage' =>$perPage));
						}else{
						}
					}
					// pagination ends ?> 
					
										
									
									
							
							<!-- END EXAMPLE TABLE PORTLET-->
						</div>
					</div>
				</div>
				<!-- END PAGE CONTENT-->
			</div>
			<!-- END PAGE CONTAINER-->
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->

	<script>
	$(document).ready(function(){
		var sorting =[1,2,3,4,5];
		applyDataTable('trophylist',sorting);
	});
	$("#trophylist_length").css('display','none');
	$("#trophylist_filter").css('display','none');
	$("#trophylist_paginate").css('display','none');
	
	</script>
	<script>
	function applyDataTable(tableid,sorting)
	{
		$(document).ready(function() {
			oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
				               {
				                  bSortable: false,
				                  aTargets: sorting,
				               }
				             ]
	        
				
			});
		} );
	}
	
	
	</script>