<script src="<?php echo $this->baseUrl();?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php  $perPage = $this->perpage;?>

<!-- BEGIN PAGE -->

<div id="body">
	<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<div id="widget-config" class="modal hide">
		<div class="modal-header">
			<button data-dismiss="modal" class="close" type="button">×</button>
			<h3>Widget Settings</h3>
		</div>
		<div class="modal-body">
			<p>Here will be a configuration form</p>
		</div>
	</div>
	<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	<!-- BEGIN PAGE CONTAINER-->
	<div class="container-fluid">
    <?php if(isset($this->success) && $this->success != ''){?>
    <div id="success" class="alert alert-success">
			<button class="close" data-dismiss="alert">×</button>
      <?php echo $this->success;?></div>
    <?php }?>
    <?php
				if (isset ( $this->error ) && $this->error != '') {
					?>
    <div id="exception" class="alert alert-error">
			<button class="close" data-dismiss="alert">×</button>
      <?php echo $this->error;?> </div>
    <?php
				}
				?>
    <!-- BEGIN PAGE HEADER-->
		<div class="row-fluid">
			<div class="span12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<ul class="breadcrumb">
					<li><i class="icon-home"></i> <a
						href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a>
						<span class="divider">/</span></li>
					<li><a
						href="<?php echo $this->url(array('controller'=>'manages','action'=>'list', 'module' => 'admin'), null, true);?>">Manage
							Admin Users</a></li>
					<li style="float: right"><a class='iframe'
						href="<?php echo $this->url(array('controller'=>'manages','action'=>'add', 'module' => 'admin'), null, true);?>"><img
							src="<?php echo $this->baseUrl();?>/assets_admin/images/add_trophy.png" /></a></li>
				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>
		<!-- END PAGE HEADER-->
		<!-- BEGIN PAGE CONTENT-->
		<div id="page" class="dashboard">
			<div class="row-fluid">
				<div class="span12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="widget">
						<div class="widget-title">
							<h4>Admin List</h4>
						</div>
						<div class="widget-body">
							<form id="searchfilter" class="Margin_0" method="post"
								name="searchfilter"
								action="<?php array('controller' =>'manages', 'action' =>'list', 'module' =>'admin');?>">
								<div class="row-fluid">
									<div class=""></div>
								</div>
								<div class="row-fluid">
									<div class="control-group Left">
										<input type="text" class="span7 popovers" id="seachdata"
											placeholder="Search Keyword" name="seachdata"
											value="<?php  echo $this->searchdata;?>" /> <input
											type="submit" class="btn btn-primary serach_Button"
											value="Search">
									</div>
								</div>
							</form>
              <?php if($this->searchdata != ''){?>
              <ul class="breadcrumb">
								<li>You have searched for :</li>
								<li> <?php echo $this->searchdata;?> </li>
								<li><span class="divider">/</span> <a
									href="<?php echo $this->url(array('controller'=>'manages','action'=>'list', 'module' => 'admin'), null, true);?>">Clear
										search</a></li>
							</ul>
              <?php }?>
              <table class="table table-striped table-bordered"
								id="manageslist">
								<thead>
									<tr>
										<th width="5%">#</th>
										<th width="16%">Name</th>
										<th width="16%" class="hidden-phone">Username</th>
										<th width="20%" class="hidden-phone">Email ID</th>
										<th width="15%" class="hidden-phone">Phone Number</th>
										<th width="13%" class="hidden-phone">Image</th>
										<th width="10%" class="hidden-phone">Operation</th>
									</tr>
								</thead>
								<tbody>
                  <?php
																		if ($this->totalRecord > 0) {
																			$i = 1;
																			foreach ( $this->Data as $caq ) {
																				
																				
																				?>
                  <tr class="odd gradeX">
										<td class="hidden-phone"><?php echo $i; ?>&nbsp;</td>
										<td class="hidden-phone"><?php echo ucwords(wordwrap($caq['name'], 40, "<br />\n",true));?>&nbsp;</td>
										<td class="hidden-phone"><?php echo wordwrap($caq['username'], 40, "<br />\n",true);?>&nbsp;</td>
										<td class="hidden-phone"><?php echo wordwrap($caq['email'], 40, "<br />\n",true);?>&nbsp;</td>
										<td class="hidden-phone"><?php  echo '+1-'.$caq ['phone'];   ?> </td>
										<td class="hidden-phone center">&nbsp;
                                                                                    <?php
                                                                                    $image = $this->baseUrl('/images/no-image.png');
                                                                                    if ($caq ['image'] != '')
                                                                                            $image = AWS_S3_URL . 'admin/' . $caq ['image'];
                                                                                    else
                                                                                        
                                                                                    ?>
                      <img
											src="<?php echo $image;?>"
											border="0" style="width: 100px; height: 100px;" />&nbsp;
										</td>
										<td class="hidden-phone center">&nbsp;<?php /*?> <a href="<?php echo $this->url(array('controller' =>'manages','action'=>'view','module'=>'admin','id' =>$caq['admin_user_id']),null,true);?>" class='iframe'><img src="<?php echo $this->baseUrl();?>/assets_admin/images/preview.png" alt="View Detail" title="View Detail" border="0" /></a><?php */?> <a
											href="<?php echo $this->url(array('controller' =>'manages','action'=>'edit','module'=>'admin','id' =>$caq['admin_user_id']),null,true);?>"
											class='iframe'><img border="0" title="Edit this admin user"
												alt="Edit"
												src="<?php echo $this->baseUrl();?>/assets_admin/images/edit_icon.png"></a>


											<a onclick="AdminStatus('<?php echo $caq['is_active'];?>','<?php echo $caq['admin_user_id'];?>');"
											href="javascript:void(0)"><img
												border="0"
												src="<?php echo $this->baseUrl();?>/assets_admin/images/active_<?php echo $caq['is_active'];  ?>.png"
												title="Change status"></a> <a
											href="<?php echo $this->url(array('controller' =>'manages','action'=>'resetpassword','module'=>'admin','id' =>$caq['admin_user_id']),null,true);?>"><img
												src="<?php  echo $this->baseUrl();?>/assets_admin/images/resetpass.png"
												alt="Reset Password" title="Reset Password" border="0"
												height="17" width="16" /></a><?php ?> </td>
									</tr>
                  <?php
																				
$i ++;
																			}
																		} else {
																			?>
                  <tr class="odd gradeX">
										<td class="hidden-phone" colspan="7"
											style="text-align: center">NO RECORD FOUND</td>
									</tr>
                  <?php }?>
                </tbody>
							</table>
						</div>
					</div>
          <?php
										if ($this->totalRecord > $perPage) {
											?>
          <form name="searchFormSort" id="searchFormSort"
						action="<?php  echo $this->url(array('controller' => 'manages', 'action' => 'list', 'module' => 'admin'),null,true);?>"
						method="post" class="RecordPerPage">
						<span class="RecordPerPageSpan">Show&nbsp;</span><select
							name="perpage" onchange="javascript:sub_per_page();"
							class="span6" tabindex="1" id="">
							<option value="10"
								<?php if($perPage == '10'){ echo 'selected=selected';}?>>10</option>
							<option value="20"
								<?php if($perPage == '20'){ echo 'selected=selected';}?>>20</option>
							<option value="30"
								<?php if($perPage == '30'){ echo 'selected=selected';}?>>30</option>
						</select><span class="RecordPerPageSpan">&nbsp;entries</span> <input
							type="hidden" name="seachdata" class="searchdata"
							value="<?php  echo $this->searchdata;?>" />
					</form>
          <?php }?>
             <script language="javascript">
							function sub_per_page()
							{
							$('.searchdata').val($('#seachdata').val());
							document.searchFormSort.submit();
							}
							</script>
          <?php
										// pagination start
										if ($this->totalRecord > 0) {
											if ($this->totalRecord > $perPage) {
												echo $this->paginationControl ( $this->Data, 'Sliding', 'paginationquestion.phtml', array (
														'seachdata' => $this->searchdata,
														'perpage' => $perPage 
												) );
											} else {
											}
										}
										// pagination ends										?>
          <!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
		</div>
		<!-- END PAGE CONTENT-->
	</div>
	<!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<!--  <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets_admin/css/colorbox.css" />
<script src="<?php echo $this->baseUrl();?>/assets_admin/js/jquery.colorbox.js"></script>
<script>
			$(document).ready(function(){
				//Examples of how to assign the Colorbox event to elements
				
				//$(".iframe").colorbox({iframe:true, width:"70%", height:"90%"});
				$(".iframe").colorbox({iframe:true, width:"70%", height:"85%",onClosed:function(){ location.href='<?php $_SERVER["REQUEST_URI"];?>'  }});
				
			});
		</script>-->
<?php  if($this->totalRecord>0){ ?>
<script>
	
	$(document).ready(function(){
		var sorting =[ 0,4,5,6];
		applyDataTable('manageslist',sorting);
	});
	$("#trophylist_length").css('display','none');
	$("#trophylist_filter").css('display','none');
	$("#trophylist_paginate").css('display','none');
	
	</script>
<script>
	
	function applyDataTable(tableid,sorting)
	{
		oTable = $('#'+tableid).dataTable({
				"bPaginate": false,
				"bFilter": false,
				"bInfo":false,
				"aaSorting": [],
				aoColumnDefs: [
				   {   
					  bSortable: false,
					  aTargets: sorting
				   }
				 ]
	        
				
			});
		
	}
	</script>
<?php }?>