<div id="Paging">   
    <div class="Pageing_admin">
  
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
             <a href="<?php echo $this->url(array('page' => $this->previous,'child_Device_Id' => $this->child_Device_Id, 'date_search' =>$this->date_search)); ?>">&lt; </a>   
        <?php else: ?>
          <span class="disabled">&lt; </span> 
        <?php endif; ?>
        <!-- start page link -->
        <?php if (isset($this->first) && ($this->current-$this->first) >= 5 && $this->first != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $this->first, 'child_Device_Id' => $this->child_Device_Id, 'date_search' =>$this->date_search)); ?>">1 </a> ... 
        <?php else: ?>
            <span class="disabled"></span>
        <?php endif; ?>
        
        <!-- Numbered page links -->
        <?php 
        foreach ($this->pagesInRange as $page): ?>
           <?php if ($page != $this->current): ?>
               	<a href="<?php echo $this->url(array('page' => $page,'child_Device_Id' => $this->child_Device_Id, 'date_search' =>$this->date_search)); ?>"><?php echo $page; ?></a>
           <?php else: ?>
                <?php echo $page; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>
         <!-- Last page link -->
        <?php if (isset($this->last) && $this->current <= $this->last-5 && $this->last != $this->current): ?>
                    ...  <a href="<?php echo $this->url(array('page' => $this->last,'child_Device_Id' => $this->child_Device_Id, 'date_search' =>$this->date_search)); ?>"><?php echo $this->last;?></a> 
        <?php else: ?>
            <span class="disabled"></span>
        <?php endif; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
                      <a href="<?php echo $this->url(array('page' => $this->next,'child_Device_Id' => $this->child_Device_Id, 'date_search' =>$this->date_search)); ?>"> &gt;</a>
        <?php else: ?>
               <span class="disabled"> &gt;</span>
        <?php endif; ?>
       
	</div> 
 </div>