<div id="Paging">   
    <div class="Pageing_admin">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
          <div class="Link12" >        <a href="<?php echo $this->url(array('page' => $this->first,'seachdata' => $this->seachdata,'perpage' =>$this->perpage)); ?>">&lt;&lt;</a> </div>
        <?php else: ?>
           <div class="Link13" >       <a>&lt;&lt;</a> </div>
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
            <div class="Link12">    <a href="<?php echo $this->url(array('page' => $this->previous,'seachdata' => $this->seachdata,'perpage' =>$this->perpage)); ?>">&lt;</a> </div>
        <?php else: ?>
          <div class="Link13">    <a>&lt;</a> </div>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php //foreach ($this->pagesInRange as $page): ?>
            <?php //if ($page != $this->current): ?>
          <?php //echo $page; ?><div class="Link10">&nbsp;&nbsp;<?php echo "Page ".$this->current." of ".$this->last; ?>&nbsp;&nbsp;</div>
            <?php //else: ?>
             <!--<div class="Link11"> <a><?php //echo $page; ?></a></div>
            --><?php //endif; ?>
        <?php //endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
           <div class="Link12">      <a href="<?php echo $this->url(array('page' => $this->next,'seachdata' => $this->seachdata,'perpage' =>$this->perpage)); ?>">&gt;</a> </div>
        <?php else: ?>
          <div class="Link13">     <a>&gt;</a> </div>
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
            <div class="Link12">    <a href="<?php echo $this->url(array('page' => $this->last,'seachdata' => $this->seachdata,'perpage' =>$this->perpage)); ?>">&gt;&gt;</a></div>
        <?php else: ?>
          <div class="Link13"><a>&gt;&gt;</a></div>
        <?php endif; ?>
   </div>
 </div>