<!-- BEGIN PAGE -->  
      <div id="body">
         <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <div id="widget-config" class="modal hide">
            <div class="modal-header">
               <button data-dismiss="modal" class="close" type="button">×</button>
               <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
               <p>Here will be a configuration form</p>
            </div>
         </div>
         <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
        <?php if(isset($this->success) && $this->success != ''){?>
           	<div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success;?></div>
           	<?php }?>
         <?php 
         		if(isset($this->error) && $this->error != ''){
         	?>		 <div id="exception" class="alert alert-error">
         				<button class="close" data-dismiss="alert">×</button>
         				<?php echo $this->error;?>
         			</div>
    		 <?php     	
        		 }
        	 ?>
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                      <!-- BEGIN PAGE TITLE & BREADCRUMB-->		
						
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="<?php echo $this->url(array('controller'=>'index','action'=>'dashboard', 'module' => 'admin'), null, true);?>">Home</a> <span class="divider">/</span>
							</li>
							<li><a href="<?php echo $this->url(array('controller'=>'login','action'=>'changepassword', 'module' => 'admin'), null, true);?>">Change Password</a>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div id="page">
               <div class="row-fluid">
                  <div class="span12">
                     <!-- BEGIN SAMPLE FORM PORTLET-->	
                     <div class="widget">
                        <div class="widget-body form">
                           <!-- BEGIN FORM-->
                            <form onsubmit ="return validateChangePassword();" name="cms" id="cms" action="<?php echo $this->url(array('controller' =>'login', 'action' =>'changepassword', 'module' =>'admin'), null, true);?>" method="post" class="form-horizontal">
                              <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>Current password:</label>
                                 <div class="controls">
                                
                                    <input type="password" class="span3 popovers" id="oldPassword" name="oldPassword" maxlength="16"/>
                                     <div style="color:#FF0000;display:none" id="oldPasswordError" ></div>
                                 	</div>
                              </div>
                             <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>New password:</label>
                                 <div class="controls">
                                 
                                    <input type="password" class="span3 popovers" id="newPassword" name="newPassword" maxlength="16"/>
                                    <div style="color:#FF0000;display:none" id="newPasswordError" ></div>
                                 	</div>
                              </div>
                               <div class="control-group">
                                 <label class="control-label Grey" for="input3"><span class="error">*</span>Confirm new password:</label>
                                 <div class="controls">
                                 
                                    <input type="password" class="span3 popovers" id="confirmPassword" name="confirmPassword" maxlength="16"/>
                                    <div style="color:#FF0000;display:none" id="confirmPasswordError" ></div>
                                 	</div>
                              </div>
                             
                              <div class="form-actions">
                                 <button type="submit" class="btn btn-primary" >Update</button>
								  <button type="button" class="btn" onClick="returnPage('index','index');">Cancel</button>
                              </div>
                           </form>
                           <!-- END FORM-->				
                        </div>
                     </div>
                     <!-- END SAMPLE FORM PORTLET-->
                  </div>
               </div>
            </div>
            <!-- END PAGE CONTENT-->			
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE --> 