<?php
/**
 *
 * This page is created for login
 * @author Dharmendra Mishra
 * @created date Tuesday, February 19 2013
 * @company A3logics (I) Ltd.
 */
?>
<script type="text/javascript">
function closeThisError(id){
	$('#'+id).css("display","none");
}
function validateForGet(){
	var error = false;
	if($('#email').val()==''){
		$("#email").addClass("errorA");
		$("#email_error").html("Please enter your e-mail address to reset <br/>your password");
		$("#email_error").show();
		error = true;
	}else if(!$("#email").val().match( /^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$/)){
		$("#email").addClass("errorA");
		$("#email_error").html("Enter valid e-mail address");
		$("#email_error").show();
		error = true;
}else{
	$("#email").removeClass("errorA");
	$("#email_error").html("");
	$("#email_error").hide();
}
if(error){
	return false;
}else{
	return true;
}
}
</script>
<!-- BEGIN LOGO -->
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div id="login">
	<!-- BEGIN LOGIN FORM -->
	<form id="forgotform" class="form-vertical no-padding no-margin"
		action="<?php echo $this->url(array('module' => 'admin','controller'  =>'login','action' =>'forgotpassword'));?>"
		method="post" onSubmit="return validateForGet();"><?php if(isset($this->errorMsg) && $this->errorMsg !=''){?>
<div class="alert alert-error" id="errorblock" style="display: block;">
<?php echo $this->errorMsg;?> <a class="close" data-dismiss="alert"
				onClick="closeThisError('errorblock');"<?php if(isset($this->errorMsg) && $this->errorMsg !=''){ echo "style='right:-30px;top:-9px;'";}?>>×</a>
		</div>
<?php }?> <?php if(isset($this->success) && $this->success !=''){?>
<div
			class="alert <?php if(isset($this->success) && $this->success !=''){ echo "alert-success";}else{echo "alert-error";}?>"
			id="successblock" style="display: block;"><?php echo $this->success;?>
<a class="close" data-dismiss="alert"
				onClick="closeThisError('successblock');"
				<?php if(isset($this->success) && $this->success !=''){ echo "style='right:-30px;top:-26px;'";}?>>×</a>
		</div>
<?php }?>

	<!-- END LOGIN FORM -->
	<!-- BEGIN FORGOT PASSWORD FORM -->
	
		<p class="center">Enter your e-mail address below to reset your
			password.</p>
		<div class="control-group">
			<div class="controls">
				<div class="input-prepend">
					<span class="add-on"><i class="icon-envelope"></i></span><input
						id="email" name="email" type="text" placeholder="Email" />
					<div class="errorMgsBox" id="email_error"></div>
				</div>
			</div>
			<div class="block-hint pull-right">
				<a href="<?php echo $this->url(array('controller'=>'login','action'=>'login', 'module' => 'admin'), null, true);?>" class="" id="forget-password">Go back and login</a>
			</div>
			<div class="space10"></div>
		</div>
		<input type="submit" id="forget-btn" class="CreateAccount"
			value="Submit" />
	</form>
	<!-- END FORGOT PASSWORD FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div id="login-copyright"><?php echo date("Y"); ?> &copy; My Finny</div>
<!-- END COPYRIGHT -->
