<?php
/**
 *
 * This page is created for login
 * @author Dharmendra Mishra
 * @created date Tuesday, Date 25 Apr 2014
 * @company A3logics (I) Ltd.
 */
?>
<script type="text/javascript">
    function validatePasswordReset() {
        var error = false;
        var newPasswordflag = 0;
        var newPassword = $('#password').val();
        var confirmPassword = $('#confirmpassword').val();
        if (newPassword == '') {
            $("#passwordError").html("Please enter password");
            newPasswordflag = 1;
            error = true;
        } else if (newPassword != '') {
            //var space = newPassword.indexOf(' ');
            var space = newPassword.indexOf(' ');
            if (space >= 0) {
                $("#passwordError").html("Invalid Password");
                newPasswordflag = 1;
                error = true;
            } else if (validateminLength('8', newPassword) == false) {
                $("#passwordError").html("Please enter Password of min 8 characters");
                newPasswordflag = 1;
                error = true;
            } else if (!/^(?=.*?[A-Za-z])(?=(.*[\d]))(?=(.*[\W]))(?!.*\s).{8,16}$/.test(newPassword)) {
                $("#passwordError").html("Password must have at least one number, one special character and one alphabet.");
                newPasswordflag = 1;
                error = true;
            } else if (validatemaxLength('16', newPassword) == false) {
                $("#passwordError").html("Please enter Password of max 16 characters");
                newPasswordflag = 1;
                error = true;
            }
        }

        if (newPasswordflag == 1) {
            $("#password").addClass("errorA");
            $("#passwordError").show();
        } else {
            $("#password").removeClass("errorA");
            $("#passwordError").hide();
        }

        if (confirmPassword == '') {
            $("#confirmpassword").addClass("errorA");
            $("#confirmpassword_error").html("Please enter confirm password");
            $("#confirmpassword_error").show();
            error = true;
        } else if (confirmPassword != '') {
            //var space = confirmPassword.indexOf(' '); 
            if (confirmPassword != newPassword) {
                $("#confirmpassword").addClass("errorA");
                $("#confirmpassword_error").html("Passoword and confirm password are not matched");
                $("#confirmpassword_error").show();
                error = true;
            } else {
                $("#password").removeClass("errorA");
                $("#confirmpassword_error").hide();
            }
        }

        if (error) {
            return false;
        } else {
            return true;
        }
    }
    function closeThisError(id) {
        $('#' + id).css("display", "none");
    }
    function validateminLength(minlength, entity)
    {
        var len = $.trim(entity).length;
        if (len < minlength)
        {

            return false;
        }
        else
        {

            return true;
        }
    }
    /*function to validate Max length*/
    function validatemaxLength(maxlength, entity)
    {
        var len = $.trim(entity).length;
        if (len > maxlength)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
</script>
<!-- BEGIN LOGO -->
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div id="login">
    <!-- BEGIN LOGIN FORM -->
    <form id="resetForm" class="form-vertical no-padding no-margin"
          action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'login', 'action' => 'resetpassword')); ?>"
          onSubmit="return validatePasswordReset();" method="post"><?php if (isset($this->errorMsg) && $this->errorMsg != '') { ?>
            <div class="alert alert-error" id="errorblock" style="display: block;">
                <?php echo $this->errorMsg; ?> <a class="close" data-dismiss="alert"
                   onClick="closeThisError('errorblock');">×</a>
            </div>
        <?php } ?> <?php if (isset($this->message) && $this->message != '') { ?>
            <div
                class="alert <?php
                if (isset($this->success) && $this->success != '') {
                    echo "alert-success";
                } else {
                    echo "alert-error";
                }
                ?>"
                id="successblock" style="display: block;"><?php echo $this->message; ?>
                <a class="close" data-dismiss="alert"
                   onClick="closeThisError('successblock');"
                   <?php
                   if (isset($this->success) && $this->success != '') {
                       echo "style='right:-30px;top:-50px;'";
                   }
                   ?>>×</a>
            </div>
        <?php } ?>
        <p class="center"></p>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span><input
                        name="password" id="password" type="password" maxlength="16"
                        placeholder="Password" />
                    <div class="errorMgsBox" id="passwordError"></div>
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span><input
                        name="confirmpassword" id="confirmpassword" type="password" maxlength="16"
                        placeholder="Confirm Password" />
                    <div class="errorMgsBox" id="confirmpassword_error"></div>
                </div>


                <div class="clearfix space5"></div>
            </div>
        </div>
        <input name="userId" id="userId" type="hidden" value="<?php echo $this->userId; ?>"/>
        <input name="verficationCode" id="verficationCode" type="hidden" value="<?php echo $this->verficationCode; ?>"/>
        <input type="submit" id="login-btn" class="CreateAccount"
               value="Reset Password" />
    </form>
    <!-- END LOGIN FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div id="login-copyright"><?php echo date("Y"); ?> &copy; My Finny</div>
<!-- END COPYRIGHT -->
