<?php
$subjectList = $this->subjectList;
$subjectWiseData = $this->subjectWiseData; //echo "<pre>";print_r($subjectWiseData);die;
$gradeWiseTotalQuestions = $this->gradeWiseTotalQuestions;
$gradeList = $this->gradeList;
$search_val = $this->searchSubject;
?>
<script src="<?php echo $this->baseUrl(); ?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php
if (isset($this->standard_id)) {
    $standard_ids = $this->standard_id;
}
?>
<?php $perPage = $this->perpage; ?>
<!-- BEGIN PAGE -->

<div id="body">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="widget-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            <h3>Widget Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here will be a configuration form</p>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <?php if (isset($this->success) && $this->success != '') { ?>
            <div id="success" class="alert alert-success">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->success; ?></div>
        <?php } ?>
        <?php
        if (isset($this->error) && $this->error != '') {
            ?>
            <div id="exception" class="alert alert-error">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->error; ?> </div>
            <?php
        }
        ?>
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li><i class="icon-home"></i> <a
                            href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                        <span class="divider">/</span></li>
                    <li><a
                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'index', 'module' => 'admin'), null, true); ?>">
                            Stats</a></li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div id="page" class="dashboard">
            <div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="widget">
                        <div class="widget-title TabsTop">
                            <ul>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'index');" class="active">
                                        Grade
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'personstats');">
                                        Person
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="widget-body">
                            <form id="searchfilter" method="post" name="searchfilter"
                                  class="Margin_0">
                                <div class="row-fluid">
                                    <div class="">
                                        <div id="domain_div" class="dataTables_length">
                                            <input type="button" class="btn btn-primary"
                                                   id="search_subject1" value="Search"
                                                   onclick="getfilterestas();" style="float: right;"> <input
                                                   type="text" style="width: 200px !important; float: right;"
                                                   class="span6 popovers SearchAdmin"
                                                   placeholder="Search Keyword" id="search_subject"
                                                   name="search_subject" value="<?php echo $search_val; ?>" />
                                        </div>

                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="ApprovedTotalQuestionCountTag">
                                        <div id="domain_div" class="dataTables_length">
                                            *(Approved / Total Question)
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <?php
                            if ($search_val != '') {
                                ?>
                                <ul class="breadcrumb">
                                    <li>You have searched for :</li>
                                    <li> <?php echo $search_val; ?> </li>
                                    <li><span class="divider">/</span> <a
                                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'index', 'module' => 'admin'), null, true); ?>">Clear
                                            search</a></li>
                                </ul>
                            <?php } ?>
                            <div class="overFlow">
                                <table class="table table-striped table-bordered"
                                       id="statsListsView">
                                    <thead>
                                        <tr>
                                            <th>Grade/Framework</th>
                                            <?php foreach ($gradeList as $gradeListV) { ?>
                                                <th><?php echo $gradeListV['grades_id']; ?></th>
                                            <?php } ?>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Total Questions</td>
                                            <?php
                                            if (!empty($subjectList)) {
                                                $standardId = 1;
                                                foreach ($gradeList as $gradeListV) {
                                                    ?>
                                                    <td><?php
                                                        if (!empty($gradeWiseTotalQuestions[$gradeListV['grades_id']]['totalApproved'])) {
                                                            echo $gradeWiseTotalQuestions[$gradeListV['grades_id']]['totalApproved'] . " / ";
                                                        } else {
                                                            echo "0 / ";
                                                        }
                                                        if (!empty($gradeWiseTotalQuestions[$gradeListV['grades_id']]['total'])) {
                                                            echo $gradeWiseTotalQuestions[$gradeListV['grades_id']]['total'];
                                                        } else {
                                                            echo "0";
                                                        }
                                                        ?></td>
                                            <?php } ?>
                                            </tr>
                                            <?php
                                            foreach ($subjectList as $subjectListA) {
                                                $subjectId = $subjectListA ['subject_id'];
                                                if ($subjectListA['standard_id'] == $standardId && $standardId == 1) {
                                                    $standardId = 2;
                                                    ?>
                                                    <tr>
                                                        <td colspan="13" class="Stdseperater">CCSS</td>
                                                    </tr>
                                                    <?php
                                                } else if ($subjectListA['standard_id'] == $standardId && $standardId == 2) {
                                                    $standardId = 0;
                                                    ?>
                                                    <tr>
                                                        <td colspan="13" class="Stdseperater">PSV</td>
                                                    </tr>
        <?php } ?>
                                                <tr>
                                                    <td><a
                                                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'statslist', 'subjectId' => base64_encode($subjectId), 'module' => 'admin'), null, true); ?>"><?php echo ucwords($subjectListA['subject_name']); ?></a></td>
                                                        <?php
                                                        foreach ($gradeList as $gradeListV) {
                                                            ?>
                                                        <td><?php
                                                            if (!empty($subjectWiseData[$subjectId][$gradeListV['grades_id']]['totalApproved'])) {
                                                                echo $subjectWiseData[$subjectId][$gradeListV['grades_id']]['totalApproved'] . " / ";
                                                            } else {
                                                                echo '0 / ';
                                                            }
                                                            if (!empty($subjectWiseData[$subjectId][$gradeListV['grades_id']]['total'])) {
                                                                echo $subjectWiseData[$subjectId][$gradeListV['grades_id']]['total'];
                                                            } else {
                                                                echo 0;
                                                            }
                                                            ?></td>
                                                        <?php
                                                    }
                                                    ?>
                                                <?php }
                                            } else {
                                                ?>
                                                <td style="text-align:left" colspan="<?php echo count($gradeList) + 2; ?>">No data available in table</td>
<?php } ?>
                                        </tr>	                 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <script language="javascript">
                        function sub_per_page(url, value)
                        {
                            var p = url.indexOf("/perpage");
                            if (p == -1)
                            {
                                var urlone = url;
                            }
                            else
                            {
                                var urlone = url.split('/perpage')[0];
                            }
                            url = urlone + '/perpage/' + value;
                            window.location = url;
                        }
                    </script>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>
    $(document).ready(function () {
        var sorting = [0];
        //applyDataTable('statsListsView',sorting);
    });
    $("#questionlist_length").css('display', 'none');
    $("#questionlist_filter").css('display', 'none');
    $("#questionlist_paginate").css('display', 'none');

</script>
<script>
    function applyDataTable(tableid, sorting)
    {
        $(document).ready(function () {
            oTable = $('#' + tableid).dataTable({
                "bPaginate": false,
                "bFilter": false,
                "bInfo": false,
                "aaSorting": [],
                aoColumnDefs: [
                    {
                        bSortable: false,
                        aTargets: sorting,
                    }
                ]
            });
        });
    }
</script>
