<?php
$dataResult = $this->dataResult; //echo "<pre>";print_r($dataResult);die;
$persionName = $this->searchName;
?>
<script src="<?php echo $this->baseUrl(); ?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php
if (isset($this->standard_id)) {
    $standard_ids = $this->standard_id;
}
?>
<?php $perPage = $this->perpage; ?>
<!-- BEGIN PAGE -->

<div id="body">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="widget-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            <h3>Widget Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here will be a configuration form</p>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <?php if (isset($this->success) && $this->success != '') { ?>
            <div id="success" class="alert alert-success">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->success; ?></div>
        <?php } ?>
        <?php
        if (isset($this->error) && $this->error != '') {
            ?>
            <div id="exception" class="alert alert-error">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->error; ?> </div>
            <?php
        }
        ?>
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li><i class="icon-home"></i> <a
                            href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                        <span class="divider">/</span></li>
                    <li><a
                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'index', 'module' => 'admin'), null, true); ?>">
                            Stats</a></li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div id="page" class="dashboard">
            <div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="widget">
                        <div class="widget-title TabsTop">
                            <ul>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'index');" >
                                        Grade
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'personstats');" class="active">
                                        Person
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="widget-body">
                            <form id="searchfilterPN" method="post" name="searchfilterPN" action="<?php echo $this->url(array('controller' => 'stats', 'action' => 'personstats', 'module' => 'admin'), null, true); ?>"
                                  class="Margin_0" >

                                <div class="row-fluid">
                                    <div class="">
                                        <div id="domain_div" class="dataTables_length">
                                            <input type="button" class="btn btn-primary"
                                                   id="search_category" value="Search"
                                                   onclick="getPersionsearchName();" style="float: right;"> <input type="text"
                                                   style="width: 200px !important; float: right;"
                                                   class="span6 popovers SearchAdmin" name="persion_name" id="persion_name"
                                                   placeholder="Search Keyword" value="<?php echo $persionName; ?>">
                                        </div>

                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="ApprovedTotalQuestionCountTag">
                                        <div id="domain_div" class="dataTables_length">
                                            *(Approved / Total Question)
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <?php
                            if ($persionName != '') {
                                ?>
                                <ul class="breadcrumb">
                                    <li>You have searched for :</li>
                                    <li> <?php echo $persionName; ?> </li>
                                    <li><span class="divider">/</span> <a
                                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'personstats', 'module' => 'admin'), null, true); ?>">Clear
                                            search</a></li>
                                </ul>
<?php } ?>
                            <div class="overFlow">
                                <table class="table table-striped table-bordered"
                                       id="questionlist">
                                    <thead>
                                        <tr>
                                            <th>Admin</th>
                                            <th>Question of this Week</th>
                                            <th>Question of last Week</th>
                                            <th>Question of Last Month</th>
                                            <th>Total Questions enter until yesterday</th>
                                            <th># of updates-how many questions were updated overall (until yesterday)</th>


                                        </tr>
                                    </thead>
                                    <tbody>

<?php if (!empty($dataResult)) {
    foreach ($dataResult as $dataResultA) {
        ?><tr>
                                                    <td><a href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'personstatslist', 'userId' => base64_encode($dataResultA['admin_id'][0]['id']), 'module' => 'admin'), null, true); ?>"><?php echo $dataResultA['admin_name'][0]['name']; ?></a></td>
                                                    <td><?php echo $dataResultA['this_week'][0]['totalApproved'] ? $dataResultA['this_week'][0]['totalApproved'] . " / " : '0 / ';
                                        echo $dataResultA['this_week'][0]['total'] ? $dataResultA['this_week'][0]['total'] : 0;
                                        ?></td>
                                                    <td><?php echo $dataResultA['last_week'][0]['totalApproved'] ? $dataResultA['last_week'][0]['totalApproved'] . " / " : '0 / ';
                                        echo $dataResultA['last_week'][0]['total'] ? $dataResultA['last_week'][0]['total'] : 0;
        ?></td>
                                                    <td><?php echo $dataResultA['last_month'][0]['totalApproved'] ? $dataResultA['last_month'][0]['totalApproved'] . " / " : '0 / ';
                                                echo $dataResultA['last_month'][0]['total'] ? $dataResultA['last_month'][0]['total'] : 0;
                                                ?></td>
                                                    <td><?php echo $dataResultA['total_question'][0]['totalApproved'] ? $dataResultA['total_question'][0]['totalApproved'] . " / " : '0 / ';
                                                echo $dataResultA['total_question'][0]['total'] ? $dataResultA['total_question'][0]['total'] : 0;
        ?></td>
                                                    <td><?php echo $dataResultA['questions_edited'][0]['totalApproved'] ? $dataResultA['questions_edited'][0]['totalApproved'] . " / " : '0 / ';
                                                echo $dataResultA['questions_edited'][0]['total'] ? $dataResultA['questions_edited'][0]['total'] : 0;
                                                ?></td>
                                                </tr>
                                            <?php }
                                        } else { ?>
                                            <tr>
                                                <td class="hidden-phone" colspan="6" style="text-align: center">NO RECORD FOUND</td>
                                            </tr>
<?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <script language="javascript">
                        function sub_per_page(url, value)
                        {
                            var p = url.indexOf("/perpage");
                            if (p == -1)
                            {
                                var urlone = url;
                            }
                            else
                            {
                                var urlone = url.split('/perpage')[0];
                            }
                            url = urlone + '/perpage/' + value;
                            window.location = url;
                        }
                    </script>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>

    $(document).ready(function () {
        var sorting = [0, 4];
        applyDataTable('questionlist', sorting);
    });
    $("#questionlist_length").css('display', 'none');
    $("#questionlist_filter").css('display', 'none');
    $("#questionlist_paginate").css('display', 'none');

</script>
<script>
    function applyDataTable(tableid, sorting)
    {
        $(document).ready(function () {
            oTable = $('#' + tableid).dataTable({
                "bPaginate": false,
                "bFilter": false,
                "bInfo": false,
                "aaSorting": [],
                aoColumnDefs: [
                    {
                        bSortable: false,
                        aTargets: sorting,
                    }
                ]
            });
        });
    }
</script>

