<?php
$weekDateWiaseDat = $this->weekDateWiaseDat; //echo "<pre>";print_r($weekDateWiaseDat);die;
$weekCount = $this->weekCount;
$subjectList = $this->subjectList;
$weekDate = $this->weekDate;
$weekTotalQuestion = $this->weekTotalQuestion;
$weekTotalApprovedQuestion = $this->weekTotalApprovedQuestion; //echo "<pre>";print_r($weekTotalApprovedQuestion);die;
$subjectWiseTotal = $this->subjectWiseTotal; //echo "<pre>";print_r($subjectWiseTotal);die;
$totalWeekDataQuestion = $this->totalWeekDataQuestion;
$totalWeekDataApprovedQuestion = $this->totalWeekDataApprovedQuestion;
$userId = $this->userId;
$search_val = $this->searchDate;
?>
<script src="<?php echo $this->baseUrl(); ?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php
if (isset($this->standard_id)) {
    $standard_ids = $this->standard_id;
}
?>
<?php $perPage = $this->perpage; ?>
<!-- BEGIN PAGE -->

<div id="body">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="widget-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            <h3>Widget Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here will be a configuration form</p>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <?php if (isset($this->success) && $this->success != '') { ?>
            <div id="success" class="alert alert-success">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->success; ?></div>
        <?php } ?>
        <?php
        if (isset($this->error) && $this->error != '') {
            ?>
            <div id="exception" class="alert alert-error">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->error; ?> </div>
            <?php
        }
        ?>
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li><i class="icon-home"></i> <a
                            href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                        <span class="divider">/</span></li>
                    <li><a
                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'index', 'module' => 'admin'), null, true); ?>">
                            Stats</a></li>
                </ul>
                <button style="float: right;" type="button" class="btn btn-primary"
                        onClick="returnPage('stats', 'personstats');">Go to Person</button>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div id="page" class="dashboard">
            <div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="widget">
                        <div class="widget-title TabsTop">
                            <ul>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'index');">
                                        Grade
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'personstats');" class="active">
                                        Person
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="widget-body">
                            <form id="searchfilterP" method="post" name="searchfilter" action="<?php echo $this->url(array('controller' => 'stats', 'action' => 'personstatslist', 'userId' => base64_encode($userId), 'module' => 'admin'), null, true); ?>"
                                  class="Margin_0">
                                <div class="row-fluid">
                                    <div class="">
                                        <div id="domain_div" class="dataTables_length">
                                            <input type="button" class="btn btn-primary"
                                                   id="search_category" value="Search"
                                                   onclick="getPersionsearch();" style="float: right;"> <input type="text"
                                                   style="width: 200px !important; float: right;"
                                                   class="span6 popovers SearchAdmin" name="fromDatePersion" id="fromDatePersion"
                                                   placeholder="YYYY-MM-DD" value="<?php echo $search_val; ?>">
                                        </div>

                                    </div>

                                </div>
                                <div class="row-fluid">
                                    <div class="ApprovedTotalQuestionCountTag">
                                        <div id="domain_div" class="dataTables_length">
                                            *(Approved / Total Question)
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <?php
                            if ($search_val != '') {
                                ?>
                                <ul class="breadcrumb">
                                    <li>You have searched for :</li>
                                    <li> <?php echo $search_val; ?> </li>
                                    <li><span class="divider">/</span> <a
                                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'personstatslist', 'userId' => base64_encode($userId), 'module' => 'admin'), null, true); ?>">Clear
                                            search</a></li>
                                </ul>
<?php } ?>
                            <div class="overFlow">
                                <table class="table table-striped table-bordered"
                                       id="persionList">
                                    <thead>
                                        <tr>
                                            <th width="20%">Date</th>
                                            <th># of Question</th>
<?php foreach ($subjectList as $subjectListA) { ?>
                                                <th> <?php echo $subjectListA['subject_name']; ?></th>
                                            <?php } ?>
                                        </tr>
                                    </thead>
                                    <tbody>

<?php
if (!empty($weekDate)) {
    foreach ($weekDate as $weekDateA) {
        ?><tr>

                                                    <td><?php echo $weekDateA['week']; ?></td>
                                                    <td><?php echo $weekTotalApprovedQuestion[$weekDateA['week']] ? $weekTotalApprovedQuestion[$weekDateA['week']] . " / " : '0 / ';
                                        echo $weekTotalQuestion[$weekDateA['week']] ? $weekTotalQuestion[$weekDateA['week']] : "0";
                                        ?></td>
                                                        <?php foreach ($subjectList as $subjectListA) {
                                                            ?>
                                                        <td><?php
                                                        if (!empty($weekDateWiaseDat[$weekDateA['week']][$subjectListA['subject_id']])) {
                                                            echo $weekDateWiaseDat[$weekDateA['week']][$subjectListA['subject_id']]['totalApproved'] ? $weekDateWiaseDat[$weekDateA['week']][$subjectListA['subject_id']]['totalApproved'] . " / " : '0 / ';
                                                            echo $weekDateWiaseDat[$weekDateA['week']][$subjectListA['subject_id']]['total'] ? $weekDateWiaseDat[$weekDateA['week']][$subjectListA['subject_id']]['total'] : 0;
                                                        } else {
                                                            echo "0 / 0";
                                                        }
                                                        ?></td>
                                                <?php } ?>
                                                </tr>
    <?php } ?>
                                            <tr>
                                                <td>Total = <?php echo $weekCount . " Weeks"; ?></td>
                                                <td><?php echo $totalWeekDataApprovedQuestion ? $totalWeekDataApprovedQuestion . " / " : '0 / ';
    echo $totalWeekDataQuestion ? $totalWeekDataQuestion : "0";
    ?></td>
                                                <?php
                                                foreach ($subjectWiseTotal as $subjectWiseTotal) {
                                                    ?>
                                                    <td><?php echo $subjectWiseTotal['totalApprove'] ? $subjectWiseTotal['totalApprove'] . " / " : '0 / ';
                                                    echo $subjectWiseTotal['total'] ? $subjectWiseTotal['total'] : "0";
                                                    ?></td>
                                            <?php }
                                        } else { ?>
                                            <tr><td style="text-align:left" colspan="<?php echo count($subjectList) + 2; ?>">No data available in table</td></tr>
<?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <script language="javascript">
                        function sub_per_page(url, value)
                        {
                            var p = url.indexOf("/perpage");
                            if (p == -1)
                            {
                                var urlone = url;
                            }
                            else
                            {
                                var urlone = url.split('/perpage')[0];
                            }
                            url = urlone + '/perpage/' + value;
                            window.location = url;
                        }
                    </script>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<
<script type="text/javascript">

    $(function () {
        $("#fromDatePersion").datepicker({
            dateFormat: "yy-mm-dd"});
    });

    $(document).ready(function () {
        var sorting = [0];
        applyDataTable('persionList1', sorting);
    });
    $("#questionlist_length").css('display', 'none');
    $("#questionlist_filter").css('display', 'none');
    $("#questionlist_paginate").css('display', 'none');


    function applyDataTable(tableid, sorting)
    {
        $(document).ready(function () {
            oTable = $('#' + tableid).dataTable({
                "bPaginate": false,
                "bFilter": false,
                "bInfo": false,
                "aaSorting": [],
                aoColumnDefs: [
                    {
                        bSortable: true,
                        aTargets: sorting,
                    }
                ]
            });
        });
    }
</script>

