<?php
$statsList = $this->statsList; //echo "<pre>";print_r($statsList);die;
$searchVal = $this->searchKeyword;
$subjectId = $this->subjectId;
?>
<script src="<?php echo $this->baseUrl(); ?>/assets_admin/data-tables/jquery.dataTables.min.js"></script>
<?php
if (isset($this->standard_id)) {
    $standard_ids = $this->standard_id;
}
?>
<?php $perPage = $this->perpage; ?>
<!-- BEGIN PAGE -->

<div id="body">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="widget-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            <h3>Widget Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here will be a configuration form</p>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <?php if (isset($this->success) && $this->success != '') { ?>
            <div id="success" class="alert alert-success">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->success; ?></div>
        <?php } ?>
        <?php
        if (isset($this->error) && $this->error != '') {
            ?>
            <div id="exception" class="alert alert-error">
                <button class="close" data-dismiss="alert">×</button>
                <?php echo $this->error; ?> </div>
            <?php
        }
        ?>
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li><i class="icon-home"></i> <a
                            href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                        <span class="divider">/</span></li>
                    <li><a
                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'index', 'module' => 'admin'), null, true); ?>">
                            Stats</a></li>
                </ul>
                <button style="float:right;" type="button" class="btn btn-primary" onClick="returnPage('stats', 'index');">Go to Stats</button>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div id="page" class="dashboard">
            <div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="widget">
                        <div class="widget-title TabsTop">
                            <ul>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'index');" class="active">
                                        Grade
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onClick="returnPage('stats', 'personstats');">
                                        Person
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="widget-body">
                            <form id="searchfilter" method="post" name="searchfilter"
                                  class="Margin_0" action="<?php echo $this->url(array('controller' => 'stats', 'action' => 'statslist', 'subjectId' => base64_encode($subjectId), 'module' => 'admin'), null, true); ?>">
                                <div class="row-fluid">
                                    <div class="">
                                        <div id="domain_div" class="dataTables_length">
                                            <input type="button" class="btn btn-primary"
                                                   id="search_category" value="Search"
                                                   onclick="getfilteredStatsList();" style="float: right;"> <input
                                                   type="text" style="width: 200px !important; float: right;"
                                                   class="span6 popovers SearchAdmin"
                                                   placeholder="Search Keyword" id="search_statslist"
                                                   name="search_statslist" value="<?php echo $searchVal; ?>" />
                                        </div>

                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="ApprovedTotalQuestionCountTag">
                                        <div id="domain_div" class="dataTables_length">
                                            *(Approved / Total Question)
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <?php
                            if ($searchVal != '') {
                                ?>
                                <ul class="breadcrumb">
                                    <li>You have searched for :</li>
                                    <li> <?php echo $searchVal; ?> </li>
                                    <li><span class="divider">/</span> <a
                                            href="<?php echo $this->url(array('controller' => 'stats', 'action' => 'statslist', 'subjectId' => base64_encode($subjectId), 'module' => 'admin'), null, true); ?>">Clear
                                            search</a></li>
                                </ul>
<?php } ?>
                            <div class="overFlow">
                                <table class="table table-striped table-bordered"
                                       id="ststslistV">
                                    <thead>
                                        <tr>
                                            <th>Category</th>
                                            <th>Domain Name</th>
                                            <th>Sub Topic Name</th>
                                            <th># of Question</th>
                                        </tr>
                                    </thead>
                                    <tbody>

<?php if ($this->totalRecord > 0) {
    foreach ($statsList as $statsListA) {
        ?><tr>
                                                    <td><?php echo $statsListA['category_code']; ?></td>
                                                    <td><?php echo $statsListA['domain_name']; ?></td>
                                                    <td><?php echo wordwrap($statsListA['subtopic_name'], 50, '<br,>', true); ?></td>
                                                    <td><?php echo $statsListA['totalApproved'] ? $statsListA['totalApproved'] . ' / ' : '0 / ';
                                        echo $statsListA['total'] ? $statsListA['total'] : 0;
                                        ?></td>
                                                <?php }
                                            } else { ?>
                                            <tr>
                                                <td class="hidden-phone" colspan="4" style="text-align: center">NO RECORD FOUND</td>
                                            </tr>
<?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <?php
                    // pagination start
                    if ($this->totalRecord != '') {
                        if ($this->totalRecord > $perPage) {
                            ?>	
                            <form name="searchFormSort" id="searchFormSort" action="<?php echo $this->url(array('controller' => 'stats', 'action' => 'statslist', 'module' => 'admin'), null, true); ?>" method="post" class="RecordPerPage">
                                <span class="RecordPerPageSpan">Show&nbsp;</span><select  name="perpage" onchange="javascript:sub_per_page('<?php echo curPageURL(); ?>', this.value);" class="span6" tabindex="1" id="">
                                    <option value="10" <?php if ($perPage == '10') {
                        echo 'selected=selected';
                    } ?>>10</option>
                                    <option value="25" <?php if ($perPage == '25') {
                        echo 'selected=selected';
                    } ?>>25</option>
                                    <option value="50" <?php if ($perPage == '50') {
                        echo 'selected=selected';
                    } ?>>50</option>
                                    <option value="100" <?php if ($perPage == '100') {
                        echo 'selected=selected';
                    } ?>>100</option>
                                    <option value="250" <?php if ($perPage == '250') {
                        echo 'selected=selected';
                    } ?>>250</option>
                                    <option value="500" <?php if ($perPage == '500') {
                        echo 'selected=selected';
                    } ?>>500</option>
                                </select><span class="RecordPerPageSpan">&nbsp;entries</span>
                                <input type="hidden" name="search_question" class="searchdata" value="<?php echo $search_val; ?>" />
                            </form>
        <?php
        echo $this->paginationControl($this->statsList, 'Sliding', 'paginationquestion.phtml', array('perpage' => $perPage));
    }
}

// pagination ends 
?>
                    <script language="javascript">
                        function sub_per_page(url, value)
                        {
                            var p = url.indexOf("/perpage");
                            if (p == -1)
                            {
                                var urlone = url;
                            }
                            else
                            {
                                var urlone = url.split('/perpage')[0];
                            }
                            url = urlone + '/perpage/' + value;
                            window.location = url;
                        }
                    </script>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<script>

    $(document).ready(function () {
        var sorting = [0, 3];
        applyDataTable('ststslistV', sorting);
    });
    $("#questionlist_length").css('display', 'none');
    $("#questionlist_filter").css('display', 'none');
    $("#questionlist_paginate").css('display', 'none');

</script>
<script>
    function applyDataTable(tableid, sorting)
    {
        $(document).ready(function () {
            oTable = $('#' + tableid).dataTable({
                "bPaginate": false,
                "bFilter": false,
                "bInfo": false,
                "aaSorting": [],
                aoColumnDefs: [
                    {
                        bSortable: true,
                        aTargets: sorting,
                    }
                ]
            });
        });
    }
</script>

