<?php
$adminInfoSession = new Zend_Session_Namespace('adminInfo');
?>
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header ?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <div class="panel panel-default">
                       <?php if(!empty($this->success)){  ?>
						<div id="success" class="alert alert-success">
						   <button class="close" data-dismiss="alert">×</button>
								 <?php echo $this->success;?>
						</div>
                        <?php } if(!empty($this->error)){ ?>
                        <div id="exception" class="alert alert-error">
                              <button class="close" data-dismiss="alert">×</button>
                              <?php echo $this->error;?>
                          </div>
                        <?php } ?>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" action="" method="post"  enctype="multipart/form-data">

										<div class="form-group">
                                            <label>Client Name</label>
                                            <input class="form-control" type="text" required="required" name="name" id="name" placeholder="Client Name" value="<?php echo $this->postData['name']?>">
                                            <p class="help-block">Add Client From Here</p>
                                        </div>
										<div class="form-group">
                                            <label>Company Name</label>
                                            <input class="form-control" type="text" required="required" name="company_name" id="company_name" placeholder="Company Name" value="<?php echo $this->postData['company_name']?>">
                                        </div>
										<div class="form-group">
                                            <label>Phone</label>
                                            <input class="form-control" type="tel" required="required" name="phone" id="phone" placeholder="Client Phone" value="<?php echo $this->postData['phone']?>">
                                        </div>
										<div class="form-group">
                                            <label>Address</label>
                                            <input class="form-control" type="text" required="required" name="address" id="address" placeholder="Client's Address" value="<?php echo $this->postData['address']?>">
                                        </div>
										<div class="form-group">
                                            <label>City</label>
                                            <input class="form-control" type="text" name="city" id="city" placeholder="Client's City" value="<?php echo $this->postData['city']?>">
                                        </div>
										<div class="form-group">
                                            <label>State</label>
                                            <input class="form-control" type="text" name="state" id="state" placeholder="Client's state" value="<?php echo $this->postData['state']?>">
                                        </div>
										<div class="form-group">
                                            <label>Country</label>
                                            <select class="form-control" required="required" name="country" id="country">
                                                <option value="">Select country</option>

												<?php foreach($this->country  as $country):
												    $DefaultCountry =	(!empty($this->postData['country'])) ? $this->postData['country'] : "94";
                                                    $selected       =   ($DefaultCountry == $country['id']) ? "selected= selected" : "";
                                                    echo "<option value='".$country[id]."' $selected >
													$country[country]</option>";

												endforeach;?>

											  </select>
                                        </div>

										<div class="form-group">
                                            <label>zip</label>
                                            <input class="form-control" type="text" maxlength="9" name="zip" id="zip" placeholder="Zip code" value="<?php echo $this->postData['zip']?>">
                                        </div>

                                        <!--Who is going to add this product -->
                                        <input type="hidden" class="form-control" name="added_by" value="<?php echo $adminInfoSession->adminData['admin_user_id']?>">




                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>

                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
