<div id="body">
    <div class="container-fluid">
        <?php if (isset($this->success) && $this->success != '') : ?>
            <div id="success" class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?php echo $this->success; ?></div>
        <?php endif; ?>
        <?php if (isset($this->error) && $this->error != '') : ?>
            <div id="exception" class="alert alert-error"><button class="close" data-dismiss="alert">×</button><?php echo $this->error; ?></div>
        <?php endif; ?>

        <div class="row-fluid">
            <div class="span12">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard', 'module' => 'admin'), null, true); ?>">Home</a>
                        <span class="divider">/</span>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'lcquestion', 'action' => 'index', 'module' => 'admin'), null, true); ?>">Learning Customization</a>
                        <span class="divider">/</span>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'lclock', 'action' => 'index', 'module' => 'admin'), null, true); ?>">Lock Duration</a>
                    </li>
                    <li style="float:right">
                        <a onClick="returnPage('lclock', 'save');" style="cursor:pointer;" title="Add Lock Duration"><img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/add_trophy.png" /></a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="page">
            <div class="row-fluid">
                <div class="span12">
                    <div class="widget">
                        <div class="widget-title TabsTop">
                            <ul>
                                <li>
                                    <a href="<?php echo $this->url(array('controller' => 'lcquestion', 'action' => 'index', 'module' => 'admin'), null, true); ?>">Question Count</a>
                                </li>
                                <li>
                                    <a href="#" class="active">Lock Duration</a>
                                </li>
                            </ul>

                        </div>
                        <div class="widget-body">
                            <table class="table table-striped table-bordered" id="sample_1">
                                <thead>
                                    <tr>
                                        <th width="10%">#</th>
                                        <th width="35%">Lock Duration <i>(Minutes)</i></th>
                                        <th width="20%">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($this->totalRecord > 0): ?>
                                        <?php $sno = 1; ?>
                                        <?php foreach ($this->lcData as $lcDataArray): ?>
                                            <?php $isNever = ($lcDataArray->duration == 0); ?>
                                            <tr class="odd gradeX">
                                                <td><?php echo $sno++ ?></td>
                                                <td ><?php echo $isNever ? 'Never' : stripslashes($lcDataArray->duration); ?></td>
                                                <td class="center">
                                                    
                                                    <?php if (!$isNever) : ?>
                                                        <a href="<?php echo $this->url(array('controller' => 'lclock', 'action' => 'save', 'id' => base64_encode($lcDataArray['id']), 'type' => 'edit', 'module' => 'admin'), null, true); ?>" class="icon huge" title="Edit Lock Duration"><i class="icon-pencil"></i></a>
                                                        &nbsp;
                                                        <a href="javascript:void(0);"><img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/del.png" alt="Delete" title="Delete Lock Duration" border="0" onClick="deleteData(<?php echo $lcDataArray['id']; ?>, 'lclock', 'delete');" /></a>
                                                        &nbsp;
                                                    <?php endif; ?>
                                                        
                                                    <?php if ($lcDataArray->is_default) : ?>
                                                        <img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/active_Y.png" title="Current Default Entry" border="0" />
                                                    <?php else: ?>
                                                        <a href="javascript:void(0);"><img src="<?php echo $this->baseUrl(); ?>/assets_admin/images/active.png" alt="Mark as Default" title="Mark as Default" border="0" onClick="markAsDefaultData(<?php echo $lcDataArray['id']; ?>, 'lclock', 'default');" /></a>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>	
                                        <tr class="odd gradeX">
                                            <td class="center" colspan="4">
                                                <div align="center">NO RECORD FOUND</div>
                                            </td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
</div>