<?php
$adminInfoSession = new Zend_Session_Namespace('adminInfo');
?>
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header ?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <div class="panel panel-default">
                       <?php if(!empty($this->success)){  ?>
						<div id="success" class="alert alert-success">
						   <button class="close" data-dismiss="alert">×</button>
								 <?php echo $this->success;?>
						</div>
                        <?php } if(!empty($this->error)){ ?>
                        <div id="exception" class="alert alert-error">
                              <button class="close" data-dismiss="alert">×</button>
                              <?php echo $this->error;?>
                          </div>
                        <?php } ?>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" action="" method="post"  enctype="multipart/form-data">

										<div class="form-group">
                                            <label>Product Name</label>
                                            <input class="form-control" type="text" required="required" name="name" id="name" placeholder="Product Name" value="<?php echo $this->productName?>">
                                            <p class="help-block">Add Products From Here</p>
                                        </div>
                                        <div class="form-group">
                                            <label>Unit Name</label>
                                            <select class="form-control" required="required" name="unit" id="unit">
                                                <option value="">Select One</option>

												<?php foreach($this->defaultUnits  as $units):
                                                    $selected       =   ($this->productUnit == $units) ? "selected= selected" : "";
                                                    echo "<option value='".$units."' $selected >$units</option>";
                                                endforeach;?>

											  </select>
                                        </div>
                                        <div class="form-group">
                                            <label>Product Stock</label>
                                            <input class="form-control" type="number" placeholder="Product Stock" name="stock" id="stock" value="<?php echo $this->productStock?>">
                                            <p class="help-block">You can spacify stock amount of this product</p>
                                        </div>
                                        <!--Who is going to add this product -->
                                        <input type="hidden" class="form-control" name="added_by" value="<?php echo $adminInfoSession->adminData['admin_user_id']?>">




                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>

                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
