 <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">View Products</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
          <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <?php if (isset($this->success) && $this->success != '') { ?>
                                    <div id="success" class="alert alert-success">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->success; ?>
                                    </div>
                                <?php } ?>
                                <?php
                                if (isset($this->error) && $this->error != '') {
                                    ?>
                                    <div id="exception" class="alert alert-error">
                                        <button class="close" data-dismiss="alert">×</button>
                                    <?php echo $this->error; ?>
                                    </div>
                                    <?php
                                }
                            ?>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                        <tr>
                                            <th>Serial No.</th>
                                            <th>Products</th>
                                            <th>Client</th>
                                            <th>Units</th>
                                            <th>Stock</th>
                                            <th>Price(&#8377)</th>
                                            <th>Added On</th>
                                            <!--<th>Action</th>-->
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    $i          =   1;
                                    foreach($this->products as $product):
                                    $class      =   (($i%2)==0) ? "even gradeA" : "odd gradeA";
                                    ?>
                                        <tr class="<?php echo $class ?>">
                                            <td><?php echo PRODUCT_SERIAL_PREFIX.$product['id'] ?></td>
                                            <td><?php echo $product['name'] ?></td>
                                            <td><?php echo $product['client'] ?></td>
                                            <td><?php echo $product['unit'] ?></td>
                                            <td class="center"><?php echo $product['stock'] ?></td>
                                            <td class="center"><?php echo $product['price'] ?></td>
                                            <td class="center"><?php echo date("d-M-Y", strtotime($product['created_date'])) ?></td>
                                           <!-- <td class="center">
                                            <a href="#" class="btn btn-info btn-lg">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                            <a href="#" class="btn btn-info btn-lg">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </a>
                                            </td>-->



                                        </tr>
                                    <?php endforeach;?>


                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->