<?php
$adminInfoSession = new Zend_Session_Namespace('adminInfo');
?>
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->header ?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <div class="panel panel-default">
                       <?php if(!empty($this->success)){  ?>
						<div id="success" class="alert alert-success">
						   <button class="close" data-dismiss="alert">×</button>
								 <?php echo $this->success;?>
						</div>
                        <?php } if(!empty($this->error)){ ?>
                        <div id="exception" class="alert alert-error">
                              <button class="close" data-dismiss="alert">×</button>
                              <?php echo $this->error;?>
                          </div>
                        <?php } ?>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" action="" method="post"  enctype="multipart/form-data">

										<div class="form-group">
                                            <label>Purchase Order</label>
                                            <select class="form-control selectClient" required="required" name="poId" id="poId">
												 <option value="">Select One</option>

												<?php foreach($this->product  as $po):
												$poName  =  $po['id'].' / '.$po['product_name'].' / '.$po['client_name'];
													echo "<option value='".$po[id]."' >$poName</option>";
												endforeach;?>

									        </select>
                                        </div>

                                        <div class="form-group">
                                            <label>List type</label>
                                            <select class="form-control" required="required" name="type" id="type">
                                                <option value="">Select One</option>
												<option value="challan">Challan</option>
												<option value="invoice">Invoice</option>

											  </select>
                                        </div>

                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>

                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
